### ISSUE TITLE
Точка входа - тизер

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#1]
Сбор и фиксация требований в [wiki репозитория](https://github.com/u-transnet/www-teaser/wiki), планирование работ, формирование задач, назначение исполнителей.
Подготовлены разделы wiki: 
[Концепция](https://github.com/u-transnet/www-teaser/wiki/Концепция)
[Пожелания по стилистике](https://github.com/u-transnet/www-teaser/wiki/Пожелания-по-стилистике)
[Примеры](https://github.com/u-transnet/www-teaser/wiki/Примеры)

**Comment by nat-brit** [comment]
Концепция: переходы по реферальным ссылкам

**Comment by nat-brit** [comment]
Концепция: переходы из Botcointalk, github, криптоплощадок, криптосообществ, криптоканалов в Телеграме, с Голоса (т.е. все криптоориентированные пользователи)
