### ISSUE TITLE
Заглушка на transnet.tech (глитч?)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#11]
Вообще надо на оба домена положить наши заглушки.
У нас в задаче по логотипу было несколько вариантов глитча от @iSergeevich 
[первый](https://github.com/u-transnet/info/issues/11#issuecomment-335385685) и [второй](https://github.com/u-transnet/info/issues/11#issuecomment-336140827), в комменты их продублирую и предлагаю высказываться
@UspenskyDritry @mparkhomenko коллеги, поможете выложиться?
@alecvert создал milestone на 20-е число пока (+2нед) - но, думаю, заглушку-глитч можно и раньше выкатить, нас ничто не держит впринципе

**Comment by cptn-solo** [comment]
![1080x1080-instagram-black](https://user-images.githubusercontent.com/31988874/31374240-95fdf538-adb6-11e7-956d-ac80e90cbb82.gif)

**Comment by kkrupovich** [comment]
![1080x1080-instagram-black2](https://user-images.githubusercontent.com/31988874/31498963-cdc4d6fe-af7c-11e7-91d4-5a8cf6438b0f.gif)

**Comment by DmitryUspensky** [comment]
Блок принятия в работу [#21822378](https://wallet.bitshares.eu/block/21822378) ( @UspenskyDritry 125 скилла, в работе до 18 ноября).

**Comment by cptn-solo** [comment]
@UspenskyDritry  оставил лого, которое надо закинуть. другое, с названиями, убрал

**Comment by cptn-solo** [comment]
давайте на transnet.space тот что выше (черный фон), а  на transnet.tech:
![](https://user-images.githubusercontent.com/31988874/31374264-adb48610-adb6-11e7-9d54-39f7f4cbb273.gif)

**Comment by jackal1527** [comment]
Что мы будем делать с этими заглушками?
1) просто сделаем чтоб застолбить адреса сайтов и просто чтобы люди удивлялись
2) прикрутим кнопки и будем людям высылать на почту новости и инфу
3) плюсом докрутим кнопку "задать вопрос"
4) что то еще или вообще ничего?

**Comment by cptn-solo** [comment]
@jackal1527 мы с @alecvert обсуждали возможность публиковать ссылки на вакансии текущие (в гитхабе, типа той, что [для дизайнера](https://github.com/u-transnet/info/issues/21). Это уже раскрытие информации о проекте, как бы - но мы же видим, что все встало колом без норм. ресурсов, разработчики коллапсируют. 
Плюс была идея добавить тикающий счетчик блоков - но см. выше - разработчиков у нас пока просто нет, они не замотивированы. Нужны люди, которые будут гореть, а не замыкаться в себе на каждом сложном месте.

**Comment by DmitryUspensky** [comment]
@kkrupovich gif-ки поставил, фоном как запаркуются домены (сегодня) можно будет смотреть.

**Comment by cptn-solo** [comment]
@UspenskyDritry 
Сейчас заметил, что:
- transnet.space:80 - сидит морда u-transnet :) так и было задумано? Прикольно :) видел ЮТТ :)) Но ИМХО мы думали на какой-то другой порт посадить, причем хз, но лучше наверное на ssl, @mparkhomenko что думаешь?
- transnet.space:443 - норм, заглушка
- transnet.tech:80 - 404 (page not found) - было бы неплохо 404 ошибку тоже глитчем влепить
- transnet.tech:443 - норм, заглушка
Давайте обсудим чего с этим сделать всем. Свои пожелания я высказал, задачу закрываю как выполненную, спасибо!

**Comment by cptn-solo** [comment]
BLOCK #21991970 uspenskydmitry1970 125UTDEV, возмещение в полном объеме, спасибо!
