### ISSUE TITLE
Запарковать домены на наших серверах

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#12]
@UspenskyDritry @jackal1527 @mparkhomenko парни, можете сюда отписать примерно, как это сделать? Или что от нас с @alecvert  нужно?
обсуждение предварительной заглушки тут #11 

"Новый" дроплет - transnet.space
"Старый" дроплет - transnet.tech

**Comment by DmitryUspensky** [comment]
Блок принятия в работу [#21821637](https://wallet.bitshares.eu/block/21821637) ( @UspenskyDritry 125 скилла, в работе до 17 ноября). По ошибке в блоке нет прямой ссылки на эту задачу.

**Comment by cptn-solo** [comment]
Эта вроде выполнена, можно закрывать. 
Предлагаю исполнителю самостоятельно предъявлять задачи к оплате, когда он считает их выполненными. Для исключения недоразумений - предлагаю заранее **указывать арбитра для разрешения возможных разногласий из команды** 
И еще - в ссылке на блок указываем учетку Bitshares. Зачем тут учетка гитхаба? 
Соорудил лейбл #overdue# (горчичник). буду помечать просроченные задачи. 
Соответственно, если задача выполнена - предлагаю рассчитываться по ней сразу, не дожидаясь расчетного дня. 
@mparkhomenko @alecvert @jackal1527
Жду возражений, если не поступит до завтра - включу в wiki

**Comment by cptn-solo** [comment]
@UspenskyDritry а задача под ssl есть?

**Comment by jackal1527** [comment]
@kkrupovich Кость что значит запарковать домены? зарегать те имена доменные, что нам нужны?

**Comment by cptn-solo** [comment]
@jackal1527 да он вроде все запарковал (прописал в регистре доменных имен айпишнеги наших серверов) - только заглушки не выложил (см. #11) - воткнулся в траблы с конфигурацией nginx, на ск. мне известно - но выходные, чего. Отдыхать изволят-с.

**Comment by DmitryUspensky** [comment]
@kkrupovich есть проблема с конфигурированием nginx, сегодня постараюсь закончить.

**Comment by cptn-solo** [comment]
@UspenskyDritry с учетом других оцененных задач - по заглушкам, #11 в частности, у тебя вроде норм по скиллу, и увеличивать залог особо смысла нет?

**Comment by DmitryUspensky** [comment]
@kkrupovich нет не нужно

**Comment by cptn-solo** [comment]
@UspenskyDritry 
Идея в том, чтобы домен transnet.space смотрел на дроплет с развернутой нодой u-transnet (тогда @mparkhomenko сможет корректно прописать ноду в морде по доменному имени, а не по ip). Соответственно, перепарковываем transnet.space на дроплет с нодой u-transnet. Под это предлагаю заложить скилл за понедельник. 
Плюс предлагаю создать отдельную задачу под разборки с ssl и документирование процесса (согласовали +1 день скилла).

**Comment by cptn-solo** [comment]
Домены норм, закрываю. По развешиванию по портам заглушек/морд в отдельных задачах (или факультативно). Вообще детали расписал в закрытой #11

**Comment by cptn-solo** [comment]
BLOCK #21993250 uspenskydmitry1970 125 DEV, возмещение в полном объеме, но на ск. я понял мы собирались добавить день на эту задачу (понедельник) - не нашел этой транзакции, т.ч. возместил только фактически заложенный скилл
