### ISSUE TITLE
НА САЙТ_Шапка сайта - планшет - проработка концепции и отрисовка

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#13]
Надо смотреть наши скетчи и развивать идею "дополненной реальности" и графиков. 

@RomaRAD исходники сюда плз
[prototyping/mainscreen](https://github.com/u-transnet/www-teaser/tree/prototyping/mainscreen)

**Comment by cptn-solo** [comment]
<img width="1200" alt="screen shot 2017-11-14 at 18 54 29" src="https://user-images.githubusercontent.com/1105555/32789600-4e039b16-c96d-11e7-969b-cd6ff57bb2ac.png">

<img width="437" alt="screen shot 2017-11-14 at 18 55 16" src="https://user-images.githubusercontent.com/1105555/32789628-628813a0-c96d-11e7-9c39-51c43795cdc2.png">

<img width="804" alt="screen shot 2017-11-14 at 18 56 09" src="https://user-images.githubusercontent.com/1105555/32789695-870c164a-c96d-11e7-9745-b665de554bbf.png">

**Comment by cptn-solo** [comment]
@jackal1527 @matusdesign парни, прошу оценить и брать в работу.

**Comment by RomaRAD** [comment]
Разговор с Алексеем
- на экране улыбающийся робот " My name is Uni_c"  и "transnet space loading"
- дополненная реальность из часов
- улыбающийся человек (если позволит ракурс)
- рука человека в ракурсе, что бы были видны часы

**Comment by RomaRAD** [comment]
![screenshot_34](https://user-images.githubusercontent.com/33925750/34069214-509ee8a8-e26d-11e7-993c-76a837abe5e0.jpg)
@kkrupovich @alecvert @jackal1527 
Жду ваших мнений и дополнений. Завтра готов взяться за работу

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich @jackal1527 https://www.youtube.com/watch?v=AJ0tZZ7Eb9M 0.32 cм. картинку 
![image](https://user-images.githubusercontent.com/30151576/34073748-5e93ddc4-e2c2-11e7-830f-27221c134a91.png) как раз женское лицо , часы на руку добавить и место есть для доп. реальности справа и слева, всё достаточно органично

**Comment by RomaRAD** [comment]
@alecvert  
если это конкретная задача, то ок.
Если мы обсуждаем, то на мой взгляд это неудачный ракурс:
- большая голова, которая бесполезно съедает 1/4 картинки + эмоции на ней не показать
- маленькая панель, получается, что акцент на отвернутой голове
- часы расположить можно, но дополненную реальность от них придется делать мелко, либо крупно, но тогда перед носом у девушки...
@kkrupovich @jackal1527  у кого какие мысли?

**Comment by cptn-solo** [comment]
@RomaRAD 
> часы расположить можно, но дополненную реальность от них придется делать мелко, либо крупно, но тогда перед носом у девушки...

не обязательно привязывать доп. реальность к девушке. Источник картинки вполне может проецироваться широкоугольно и изображение будет видно с любой точки перед экраном одинаково. Поэтому можно всю доп. реальность вывалить "в фас" слоем поверх девицы, экрана и часов.

**Comment by cptn-solo** [comment]
@RomaRAD решили развивать прототип:
![screenshot_40](https://user-images.githubusercontent.com/1105555/34095787-dee2b3c0-e3e3-11e7-8a30-007ce987fe24.jpg)

Дополнения: 
- показать вместо столбов деревья/облака - обозначить высоту

**Comment by cptn-solo** [comment]
итерация два дня, смотрим в среду 20 декабря 2017

**Comment by cptn-solo** [comment]
BLOCK #22751887
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 120.00000 UTDEV.SKILL

> итерация два дня, смотрим в среду 20 декабря 2017

**Comment by RomaRAD** [comment]
![default](https://user-images.githubusercontent.com/33925750/34197499-959cf576-e588-11e7-85f3-bfc14d4d256f.jpg)
@alecvert @kkrupovich @jackal1527 
нужна помощь, я уперся не могу посмотреть со стороны.  это не готовая иллюстрация, я еще буду работать, нужно задать вектор

**Comment by jackal1527** [comment]
@RomaRAD я не очень понимаю как это впишется в главный экран, честно говоря....

**Comment by cptn-solo** [comment]
@RomaRAD @jackal1527 но выглядит это прям очень круто. Я впечатлен. Это прям то, как я себе это представлял. Единственное, я бы проекцию вывел в первый план, и сделал ее более "голографичной". 
Считаю надо продолжать развивать, собирать список пожеланий на итерацию и действовать.

**Comment by jackal1527** [comment]
@kkrupovich Кооость, мне тоже нравится как кокпит выглядит, но главное что на 1 экран будем грузить и как!!! Сейчас эта иллюстрация туда никак не встает, уж простите...
Либо надо концепцию первого экрана переделывать

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich @jackal1527 мне нравится то, что получается.

Размер - весь этот экран вот этот, по размерам уточнить лучше у @jackal1527 
![image](https://user-images.githubusercontent.com/30151576/34202535-d2be1ce4-e599-11e7-929e-404d978ee9e6.png)

Теперь по пожеланиям:

1. На этом экране нужно сделать другое лицо робота какое-то, этот типаж отталкивает, либо вообще убрать робота и добавить смайлик цифровой, давайте подумаем, настраивать должно на то, что на экранчике приветствует искусственный интеллект и персональный личный помощник, типа как Siri в эппл или Окей, гуггл в гуглофонах, в юнибайках будет более мощная и интеллектуальная система.

и добавить UNI_C 

![image](https://user-images.githubusercontent.com/30151576/34203076-ace896fa-e59b-11e7-90e8-c16d6bdc1122.png)

2. @RomaRAD Давай сделаем рамы юнибайка и саму консоль наверху, белого матового цвета, в принципе такого цвета они и есть, либо намного более светлого

![image](https://user-images.githubusercontent.com/30151576/34203360-a1e70b64-e59c-11e7-9d86-95012b463f64.png)

3. Вместо проекции экрана нужно добавить то, что есть сутью, фон естественно прозрачный и это тоже проекция, но она должна быть во главе экрана, остальное, как прекрасное красивое дополнение и визуализация ближайшего будущего.

![image](https://user-images.githubusercontent.com/30151576/34202908-07234846-e59b-11e7-8daf-be04f22a718c.png)

То есть вот эта часть: 
![image](https://user-images.githubusercontent.com/30151576/34202971-4e90a584-e59b-11e7-939a-518850de12a6.png)


Номер блока будет меняться, когда это будет настроено с Дмитрием.
Я не знаю получится сделать ли чуть наклонённым эту проекцию, это зависит можно ли будет настроить смену блока, и чтоб это не выглядело топорно.

4. По цифровой части мира , который виден из окна пока что сыро.

Предложения 
![image](https://user-images.githubusercontent.com/30151576/34205299-b21747a4-e5a3-11e7-8bc7-d0aa76a46c9c.png)

![image](https://user-images.githubusercontent.com/30151576/34205374-e144d334-e5a3-11e7-85b0-b109481c6203.png)

Либо голосом уже

Вот мои каракули)) Но всё могу описать) Это должно быть слева

![image](https://user-images.githubusercontent.com/30151576/34205569-ba1565c0-e5a4-11e7-8a4e-2ff572e87bce.png)

**Comment by RomaRAD** [comment]
@jackal1527 ты видишь какую пропорцию у этой иллюстрашки? Более узкую,, типа 1х3?
@alecvert @kkrupovich  Я пока доделываю экраны, поменять размер можно будет как определимся.

**Comment by cptn-solo** [comment]
Решаем взять день на наброски по результатам созвона и кидаем эти варианты в #68 
Эту закрываем

**Comment by cptn-solo** [comment]
BLOCK #22818246
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV
Спасибо!
