### ISSUE TITLE
Итерация №5 (макет, структура)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#14]
Переносим сюда все комментарии с предыдущей итерации, которая была в общей задаче по макетированию #8 

Исходный макет можно смотреть по [ссылке](https://user-images.githubusercontent.com/32764532/32786686-75e4856a-c976-11e7-9c61-57a52f8a0e15.jpg)

Комментарии, зафиксированные по обсуждению последнего макета ниже:

0. Задача по проработке шапки выделена отдельно: #13 

1. Ссылка на краткую ознакомительную презентацию из [info/#14](https://github.com/u-transnet/info/issues/14)

2. Карту попробуем повернуть в фас (не изометрия) и во всю ширину. По цвету - блекло, в стиле серых заголовков разделов (можно с тенью)

3. От Карты провести линии к иконкам типов объектов справа

4. Меняем "бизнес-план" после карты: 
иконка "чеклист" выходит из карты и "отображается" в "проволочный" бизнес-план. При этом сам по себе заголовок секции меняется - это не распределение, это оцифровка. "Распределение" переезжает вниз. При этом можно подписать "бумажный" бизнес-план именно как Бизнес-план, а "проволочный" - больше текста, например "токенизация адресного проекта"

<img width="577" alt="screen shot 2017-11-14 at 18 33 57" src="https://user-images.githubusercontent.com/1105555/32788530-7bfad9e2-c96a-11e7-994a-f9da4bcfc745.png">

5. Внизу, после "шайбы" - убираем иконки бизнес-плана вообще, а заголовок/подпись "Распределение..." перемещаем к диаграмме (справа, сверху, куда-то в общем - но лучше справа)

6. Подписи к выходным картинкам - оставляем по одной подписи к картинке - т.е. одна подпись к возврату инвестиций и одна - к планированию маршрута. А уже внизу - в замыкающей части - можно и нужно оставить три колонки, т.к. надо объяснить разницу интереса для институциональных и крауд-инвесторов

**Comment by cptn-solo** [comment]
1000/20 * 8 = 400 UTDEV.SKILL (с 11 по 20 включительно, примерно 8 дней, чтобы выйти потом на инкрементальный расчет)
**BLOCK #21868526 jackal1527 до пнд, 20 ноября 2017**
В понедельник обсуждаем, [принимаем], формируем след. итерацию

**Comment by jackal1527** [comment]
![transnet_main_06](https://user-images.githubusercontent.com/32764532/33061319-84b90470-cebd-11e7-8cbb-0e2c73ddbbec.jpg)

**Comment by cptn-solo** [comment]
Под прогресс-бар:
v.0.1.0 —--------------------- 156
v.0.1.1 —---------- 20
v.0.2.0 —---5

2. Whitepaper - лучше перевести на символику github (а не pdf)

3. Справа от "башни" узла сети добавить пунктов по аналогии с "стабильность", "безопасность" и т.п.
<img width="383" alt="screen shot 2017-11-21 at 11 37 40" src="https://user-images.githubusercontent.com/1105555/33062457-7014b53a-ceb0-11e7-82a3-ee86b1379ad4.png">

4. Карту расширяем, на "мировую сеть" поднимаются снизу площадки с транс-ботом, транс-сервисом, транс-лайном (в океанах их запарковать) + добавить иконку-площадку под транс-сервис
<img width="580" alt="screen shot 2017-11-21 at 11 41 01" src="https://user-images.githubusercontent.com/1105555/33062663-20e090dc-ceb1-11e7-8997-8c350891677e.png">

5. Оцифровка бизнес-плана - пустые "бары" столбцовой диаграммы должны органично сочетаться с наполненными "барами" столбцовой диаграмы внизу в возврате инвестиций

6. Меняем местами трилистник и подпись к нему, от трилистника таким образом получаем "короткий путь" к пользователям, и "длинный" - к возврату инвестирования

7. Трилистник токенизации - ресурсные токены сделать объемными на манер 
<img width="55" alt="screen shot 2017-11-21 at 11 52 41" src="https://user-images.githubusercontent.com/1105555/33063104-84c2fc60-ceb2-11e7-8402-eaccb163fc29.png">
<img width="251" alt="screen shot 2017-11-21 at 11 51 31" src="https://user-images.githubusercontent.com/1105555/33063088-76a3595e-ceb2-11e7-8f7a-2b9e6de580ae.png">

**Comment by cptn-solo** [comment]
Итерация завершена, работа принята, следующая итерация в задаче #17

**Comment by cptn-solo** [comment]
BLOCK #21990934 jackal1527 +100UTDEV.SKILL перерасчет в св. с оконч. исп. срока
BLOCK #21991053 jackal1527 возмещение в полном объеме, 500UTDEV
