### ISSUE TITLE
Отрисовка иконок в векторе в стиле имеющейся концепции

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#15]
Задача: Нарисовать 3 иконки
1) ИНВЕСТОР
человечек в шляпе и с очками, обозначающий институционального инвестора (профессионального инвестора) + доска с какими то графиками растущими вверх
2) КРАУДФАЙНДИНГОВЫЕ или ЧАСТНЫЕ ИНВЕСТОРЫ
три человечка в рубашках, обозначающих частных инвесторов-криптовалютчиков
Человечки должны чутка друг от друга отличаться.
3) ОБЫЧНЫЕ ПОЛЬЗОВАТЕЛИ
Обычная фигурка обычного человечка. Это обычный пользователь

Сейчас иконки просто отрисованы от руки - нужно отрисовать в векторе

![fkth_x6ysogag9spemz3og](https://user-images.githubusercontent.com/32764532/33038113-698636b8-ce55-11e7-9f37-a61373241f09.png)

Можно ориентироваться на вот такой стиль и цвета:

![default](https://user-images.githubusercontent.com/32764532/33038982-4439e5a0-ce58-11e7-8be7-7c78d0e3ed91.jpg)

**Comment by cptn-solo** [comment]
@matusdesign @jackal1527 просьба сюда залить png в коммент и исходники в [protopyping](https://github.com/u-transnet/www-teaser/tree/prototyping)

**Comment by matusdesign** [comment]
![01](https://user-images.githubusercontent.com/33906014/33187542-8ba6fd40-d0a3-11e7-9355-243db98d3a8f.jpg)

**Comment by matusdesign** [comment]
Думаю иконки пока оставлю, потом если что вернусь, ,буду с главной начинать

**Comment by matusdesign** [comment]
![02](https://user-images.githubusercontent.com/33906014/33187637-39b64986-d0a4-11e7-8c34-e37f6f6fd48d.png)

**Comment by cptn-solo** [comment]
@matusdesign @jackal1527 @alecvert мне больше пред. вариант нравился. Где он кстати, чего его сюда не залили? для референса. 
@matusdesign лучше все-таки предварительно оценивать задачи - чтобы можно было итерации проводить - с итерациями всем удобнее ИМХО - потому что по каждой мы составляем список замечаний и пожеланий и двигаемся более осмысленно к цели. Если планируется работа прям он-лайн - тогда да, можно и не оценивать - но тогда и не пропадать, быть в контакте и после завершения работы отметить факт.

**Comment by cptn-solo** [comment]
Вот, нашел из вакансии первоначальный вариант. 
![t7per0fuamy](https://user-images.githubusercontent.com/32764532/33124895-6b9a5d5c-cfa0-11e7-9b88-bc675b4f3740.jpg)
@jackal1527 @alecvert предлагаю список пожеланий и предложений сформировать и согласовать тут, потом эту задачу закрыть и создать итерацию - чтобы Антон, когда к ней вернется, смог продолжить сразу с конкретикой, и смог предварительно оценить трудозатраты по списку предполагаемых доработок под итерацию. 
Спасибо.

**Comment by alecvert** [comment]
@matusdesign На мой взгляд не нужно отрисовывать подробно одежду как ты сделал здесь http://prntscr.com/helk51 . Достаточно как здесь  http://prntscr.com/helk9f , http://prntscr.com/helkf3

По цветовой гамме см. https://user-images.githubusercontent.com/32764532/33209642-a0a8cbfc-d138-11e7-92f6-bbdee457884c.jpg , только вот этот цвет заменить на зелёный надо http://prntscr.com/hepl86

Теперь отдельно по институциональному инвестору. Давай ему такой костюм http://prntscr.com/hepn7v , цвет как здесь https://user-images.githubusercontent.com/32764532/33209642-a0a8cbfc-d138-11e7-92f6-bbdee457884c.jpg , очки сейчас хорошо а ля рейбан и в правой руке, которая свободна, кейс-чемодан (с деньгами естественно, либо как минимум с кодами на кошельки :) Шляпу посмотри сам убрать или нет. Как она будет смотреться с пиджаком.

Частные инвесторы. Теперь у того у кого был костюм, у него просто будет рубашка без галстука как ранее у институционального инвестора http://prntscr.com/hepopi

http://prntscr.com/hem3sd иконка пользователя отлично, на футболке на груди нарисуй лого наш перекрещивающиеся U , исходники попроси у Владимира @jackal1527

**Comment by cptn-solo** [comment]
@alecvert @jackal1527 не возражаю. Володя, за тобой последнее слово. Исходники лучше сюда ссылку в коммент, чтобы не искать.
Если всем все понятно - просьба оценить трудозатраты и назвать срок когда будем принимать результат, заскилую задачу.

**Comment by matusdesign** [comment]
Всем добрый вечер! Я поясню ,иконки я делал как тестовое задание вполне по конкретному тз,которому обьективно работа соответствует,работа сложная и выполнялась не только в 2d графике но и отстроена полноценно в 3d ,не понимаю придирок и правок,кто то пояснит?это тест или полноценная работа для меня?вы поймите подробно никто не описывает ничего до конца и сразу,так сам я еще буду вникать долго,не проще ли кому то выделить время и пояснить мне задачу от начала до конца?)

**Comment by matusdesign** [comment]
вы поймите это трудоемкий процесс,вы определитесь сначала и точные правки напишите!

**Comment by alecvert** [comment]
@matusdesign так я же расписал вроде с примерами в своём крайнем комменте

**Comment by alecvert** [comment]
@RomaRAD внеси пжлст изменения как я расписал ранее Антону, он так и не внёс их

**Comment by cptn-solo** [comment]
1 день, смотрим завтра, 4го декабря до середины дня

**Comment by cptn-solo** [comment]
BLOCK #22330005
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL
Смотрим в понедельник, 4 декабря 2017

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @jackal1527 
Человечки
![_2](https://user-images.githubusercontent.com/33925750/33549669-20b666c0-d90d-11e7-9683-113bbdb951e6.jpg)
![- -](https://user-images.githubusercontent.com/33925750/33549672-229d6876-d90d-11e7-8ff6-1096b4eb0af1.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD классные чувачки, но переставил местами крауд и институционалов :)) но это ерунда, просто заметил

**Comment by alecvert** [comment]
@RomaRAD мне тоже нравятся иконки, институционалов с частными инвесторами, да поменяй местами пжлст 
![image](https://user-images.githubusercontent.com/30151576/33558145-f92a7812-d92a-11e7-933d-cc936690675a.png)

У частных инвесторов, у одного убери кейс http://prntscr.com/hiy05d, кардиган поменяй зелёный цвет на другой, пусть стильный зелёный пиджак будет только у институционального инвестора. Пиджак здесь  убери и на какой-то другой элемент одежды замени , например просто свиттер, и цвет голубой не надо )

У пользователя тоже какой-нибудь другой неповторяющийся цвет одежды, можно серый 
![image](https://user-images.githubusercontent.com/30151576/33558554-fb1c5982-d92b-11e7-945f-3891c3213606.png)

В остальном всё хорошо!

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @jackal1527 
Убрал голубых...
![default](https://user-images.githubusercontent.com/33925750/33593896-5566a5b4-d9b3-11e7-8dd8-a2a491df7921.jpg)

**Comment by cptn-solo** [comment]
1. сетка - тоньше;
2. институционал - черные очки;
3. пользователь - блеклая серая футболка;
4. крауд - вместо зеленого пиджака - зеленый свитер;

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @jackal1527 
![default](https://user-images.githubusercontent.com/33925750/33595404-dab4f076-d9b9-11e7-804a-c1d5d60d1e3a.jpg)

**Comment by cptn-solo** [comment]
мне нравится.

**Comment by RomaRAD** [comment]
Залил исходники https://github.com/u-transnet/www-teaser/tree/prototyping/benefits
@kkrupovich @alecvert

**Comment by cptn-solo** [comment]
Перенес в [people](https://github.com/u-transnet/www-teaser/tree/prototyping/people)
@RomaRAD ты на своем компе тоже в кучу валишь всю графику? ;))) ладно, я тоже грешу бардаком в документах, т.ч. норм. 
@alecvert если тебе норм - закрываю задачу

**Comment by RomaRAD** [comment]
@kkrupovich не туда загружаю исходники?) Я то в полной уверенности, что все правильно делаю)

**Comment by cptn-solo** [comment]
@RomaRAD там куча папок сейчас есть. я создаю под основные блоки папки, остальное - в icons-misk - но буду стараться явно просто под задачи создавать папки, пока не привыкнете.

**Comment by alecvert** [comment]
@RomaRAD всё ок

**Comment by cptn-solo** [comment]
BLOCK #22418948
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 60.00000 UTDEV

Спасибо!
