### ISSUE TITLE
Поиск, отбор и собеседования с дизайнерами/иллюстраторами

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#16]
Процесс поиска и собеседования с новыми сотрудниками
UP от @kkrupovich: @jackal1527 , полагаю, этот кандидат проходит по [вакансии](https://github.com/u-transnet/info/issues/21)?

**Comment by jackal1527** [comment]
Написал троим:
Олег https://vk.com/walofoleg - отвалился (сказал что не справится)
Антон https://vk.com/idmatusmar (задача дана + предоплата)
Роман https://vk.com/rad8000 задачу дал (22.11.17)

**Comment by cptn-solo** [comment]
@jackal1527 
Считаем по ставке 100скилл/день, сегодняшний день весь, плз подтверди в комменте или лайкни этот

**Comment by jackal1527** [comment]
Антон сделал промежуточный вариант
![ari4vmzbyoe](https://user-images.githubusercontent.com/32764532/33114715-e670fc78-cf7f-11e7-825e-7bd0bfe05c7e.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert имхо как минимум обводить мэджик лассой кандидат явно умеет. Только главное чтобы инициатива все-таки была, ИМХО. Иначе ты, @jackal1527 , убьешься рисовать для всех "от руки" скетчи, которые потом за тобой просто обводить будут. 
Но картинка мне нравится. Норм.

**Comment by jackal1527** [comment]
ну обводить не так то просто) и мне на самом деле легче так задачи давать пока что....

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert вы главное отпишитесь сюда как выберете кого-то или закройте задачу. Просто Володя ее заскилловал, мне ее надо рассчитать по регламенту, а для этого ее лучше закрыть как выполненную. Потом такие задачи прото не будем скилловать, будем закладывать в текущую деятельность просто трудозатраты с учетом доп. функций, которые выполняем в процессе поиска и т.п.

**Comment by jackal1527** [comment]
Это доделал Антон.
По мне так он подходит
![t7per0fuamy](https://user-images.githubusercontent.com/32764532/33124895-6b9a5d5c-cfa0-11e7-9b88-bc675b4f3740.jpg)

**Comment by alecvert** [comment]
@jackal1527 @kkrupovich мне кажется хорошо, доделывать надо, но это уже по ходу.

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert отлично. Парень в теме.

**Comment by cptn-solo** [comment]
@matusdesign принят, задачу закрываю.

**Comment by cptn-solo** [comment]
BLOCK #22019979 jackal1527 21 ноября 2017 100UTDEV.SKILL

**Comment by cptn-solo** [comment]
BLOCK #22020026 jackal1527 подобрали, спасибо!

**Comment by cptn-solo** [comment]
@matusdesign принят.
Статья бюджета UTD-DESIGN (до $2000/мес, испытательный срок - 1мес - $1000)
Дневная ставка 1/20 месячной, сверх 20 раб. дней - бонус (переработки только по согласованию с командой).

@RomaRAD принят.
Статья бюджета UTD-DESIGN (до $2000/мес, испытательный срок - 1мес - $1000)
Дневная ставка 1/20 месячной, сверх 20 раб. дней - бонус (переработки только по согласованию с командой).

Закрываю.

**Comment by cptn-solo** [comment]
@matusdesign проявил себя крайне некоммуникабельным и не обязательным. На будущее из кандидатов исключается. 
Из проекта вышел по собственному желанию, но, очевидно, наш темп и требования ему не подходят. 
@jackal1527 @alecvert 
Задачу переоткрываем, ищем нового [кандидата](https://github.com/u-transnet/info/issues/21). Отписываемся сюда.

**Comment by cptn-solo** [comment]
@RomaRAD условия обновлены по соглашению сторон. Ранее возмещенный скилл  возвращается (100) + добавляется 200, 
BLOCK #22182946
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 300.00000 UTDEV.SKILL
Memo / Message | Увеличение ставки до 1200, далее по схеме 1500-1700-2000 по мере выработки скилла и при условии продления контракта. После достижения максимальной ставки в 2000 отдельное собеседование

**Comment by cptn-solo** [comment]
Задача закрывается, т.к. пока потребность в дизайне полностью удовлетворена.

**Comment by cptn-solo** [comment]
Все-таки переоткрываем. Поток работ зашкаливает (см. [задачи с тегом art](https://github.com/u-transnet/www-teaser/issues?q=is%3Aopen+is%3Aissue+label%3Aart))
