### ISSUE TITLE
Итерация №6 (макет, структура)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#17]
Предыдущая итерация #14 

1. Под прогресс-бар закладываем механизм версий и баров/номеров блоков:
v.0.1.0 —--------------------- 156
v.0.1.1 —---------- 20
v.0.2.0 —---5

2. Whitepaper - лучше перевести на символику github (а не pdf)

3. Справа от "башни" узла сети добавить пунктов по аналогии с "стабильность", "безопасность" и т.п.
<img width="383" alt="screen shot 2017-11-21 at 11 37 40" src="https://user-images.githubusercontent.com/1105555/33062457-7014b53a-ceb0-11e7-82a3-ee86b1379ad4.png">

4. Карту расширяем, на "мировую сеть" поднимаются снизу площадки с транс-ботом, транс-сервисом, транс-лайном (в океанах их запарковать) + добавить иконку-площадку под транс-сервис
<img width="580" alt="screen shot 2017-11-21 at 11 41 01" src="https://user-images.githubusercontent.com/1105555/33062663-20e090dc-ceb1-11e7-8997-8c350891677e.png">

5. Оцифровка бизнес-плана - пустые "бары" столбцовой диаграммы должны органично сочетаться с наполненными "барами" столбцовой диаграмы внизу в возврате инвестиций

6. Меняем местами трилистник и подпись к нему, от трилистника таким образом получаем "короткий путь" к пользователям, и "длинный" - к возврату инвестирования

7. Трилистник токенизации - ресурсные токены сделать объемными на манер 
<img width="55" alt="screen shot 2017-11-21 at 11 52 41" src="https://user-images.githubusercontent.com/1105555/33063104-84c2fc60-ceb2-11e7-8402-eaccb163fc29.png">
<img width="251" alt="screen shot 2017-11-21 at 11 51 31" src="https://user-images.githubusercontent.com/1105555/33063088-76a3595e-ceb2-11e7-8f7a-2b9e6de580ae.png">

**Comment by cptn-solo** [comment]
@jackal1527 
Считаем ставку 2000, день = 2000/20 = 100.
В работе до вечера среды 22 ноября 2017, условно - день, 100UTDEV.SKILL
Подтверди в комментарии плз или лайкни просто.

**Comment by cptn-solo** [comment]
BLOCK #21991710 jackal1527 100UTDEV.SKILL до вечера 22 ноября 2017

**Comment by jackal1527** [comment]
![transnet_main_07](https://user-images.githubusercontent.com/32764532/33127383-143deef2-cfaa-11e7-8236-1962262f3f66.jpg)

**Comment by jackal1527** [comment]
![transnet_main_07](https://user-images.githubusercontent.com/32764532/33127427-41162a52-cfaa-11e7-9686-e81149c043dc.jpg)

**Comment by kkrupovich** [comment]
1. прогресс бар:
1.1. отсечка раз в 100 блоков на период отсутствия дедлайна. (цвет - пассивный - белый, серый)
1.2. без отсечки, процент завершения до дедлайна. (с заменой цвета на зеленый)
1.3. видимое количество баров (история) - штук 3-5

**Comment by cptn-solo** [comment]
Следующая итерация #20 
Эту закрываем как выполненную

**Comment by cptn-solo** [comment]
BLOCK #22018995 jackal1527 100UTDEV, расчет в полном объеме, спасибо
