### ISSUE TITLE
НА САЙТ_Отрисовка изображения сервера

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#18]
Нарисовать изображения серверного узла
![default](https://user-images.githubusercontent.com/32764532/33113984-861e1e94-cf7c-11e7-93bf-7cf6c47d1b84.jpg)
в стиле референсов
![default](https://user-images.githubusercontent.com/32764532/33113985-863bf824-cf7c-11e7-867f-b35bc6d28338.jpg)
(логотипы те которые будут на изображении)
![default](https://user-images.githubusercontent.com/32764532/33113986-8659573e-cf7c-11e7-9379-81e7d14e61db.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 главное потом логотип U-TECH актуализировать. Остальные ладно.

**Comment by cptn-solo** [comment]
@jackal1527 @matusdesign парни, просьба оценить и поставить дату, когда проверять. 
коммитить результат просьба в бранч [prototyping](https://github.com/u-transnet/www-teaser/tree/prototyping). png-шки - как обычно, прям тут в комментах обсуждаем. И еще, чтобы не получилось как с логотипом, предлагаю все же оценивать работу по итерациям - т.е. примерно прикидывайте, сколько времени вам надо на итерацию, фиксируйте png результата, и создавайте следующую задачу на доработку (с указанием списка - чего не устраивает - как мы пилим итеративно сайт сейчас).

**Comment by jackal1527** [comment]
Эту задачу как тестовую отрисовал Роман
Смотрим / коментим
![w-asvebmt8u](https://user-images.githubusercontent.com/32764532/33163871-45529530-d052-11e7-92ec-44870c9326d7.jpg)
![_1](https://user-images.githubusercontent.com/32764532/33163872-4577b5a4-d052-11e7-8883-90aad5ca754f.jpg)
![_2](https://user-images.githubusercontent.com/32764532/33163873-459bbfda-d052-11e7-88b7-84e277c6e658.jpg)
![_](https://user-images.githubusercontent.com/32764532/33163874-45bf2a4c-d052-11e7-9740-17329674c6ac.png)

**Comment by cptn-solo** [comment]
@jackal1527 @RomaRAD оценивайте тогда?

**Comment by cptn-solo** [comment]
@jackal1527 @RomaRAD исходники от @iSergeevich у нас в бранче [logo](https://github.com/u-transnet/info/tree/logo) репозитория info - гляньте, то/не то

**Comment by RomaRAD** [comment]
Допилил сервер.
Вопросы следующие: 
- есть ли эти лого в векторе? Я только наел в небольших JPG и загибать их по форме не очень эстетично получается.
- как на мой взгляд, одна иллюстрация с большим количеством лого смотрится перегружено
 (напоминает кар формулы 1 в наклейках спонсоров). Если есть возможность сократить количество лого до 3-4 это было бы визуально гораздо приятнее.
 
![default](https://user-images.githubusercontent.com/33925750/33304139-f857c6da-d428-11e7-817b-b80fd681af67.jpg)

**Comment by alecvert** [comment]
@RomaRAD цвет сервера лучше как в первом варианте.

У лого свой смысл, при наведении на них, можно посмотреть а какую функцию эта технология у нас будет выполнять. Кстати @EvgeniyPolyakov как вариант наводить можно типа как лазерной указкой.

Bitshares лучше сместить левее, по середине поставить graphene и справа U-tech

Основание с @kkrupovich абсолютно согласен надо потоньше.

http://prntscr.com/hgcvsx здесь две линии оставь пжлст, так как подразумевается это как и провода и символ путевой структуры

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov коллега, зафиксируй плз в каких размерах тебе нужна нарезка сервера, и @RomaRAD сделает эту нарезку. тогда можно будет эту задачу закрыть.
Изображение подсвеченной надписи есть [тут](https://github.com/u-transnet/www-teaser/issues/42#issuecomment-348425341)

**Comment by cptn-solo** [comment]
Решили делать в составе #55
