### ISSUE TITLE
Отрисовка иконок преимуществ блокчейн платформы

### ISSUE THREAD

**Issue by alecvert** [u-transnet/www-teaser#21]
![photo_2017-11-23_16-55-52](https://user-images.githubusercontent.com/30151576/33172237-199881ba-d071-11e7-8ef0-bc0ffa25f3db.jpg)

Пока не надо отрисовывать токенизацию, так как наверняка не будет понятно, как это представить.
Нужно добавить Автоматизация ( можно изобразить в виде улыбающегося робота )

![2](https://user-images.githubusercontent.com/30151576/33172234-145d752a-d071-11e7-8cc0-2915c2aff9e3.jpg)

Тут ускоренный ROI не нужен на сайте, подумаем как его заменить.

Ваня отрисовал эти иконки не в стилистике сайта, для презы это подходило , для сайта не подходит.

Сайт см. здесь https://user-images.githubusercontent.com/32764532/33061319-84b90470-cebd-11e7-8cbb-0e2c73ddbbec.jpg . Эти иконки с описанием будут располагаться слева и справа , см. http://prntscr.com/he7eyg. Можно посмотреть по "свежей" версии вида сайта итерацию номер 7 https://github.com/u-transnet/www-teaser/issues/20

**Comment by RomaRAD** [comment]
Вопросы следующие:
- перерабатываем это в стилистике шаблона сайта? (Белый, серый, синий, зеленый)?
- эти круги контейнеры оставляем или делаем чисто иконки?
- время на исполнение (нужно учесть, что браться в полную силу пока не могу пока не сдам текущий проект ). 
- стоимость работы ? Это как проектный заказ или это заказ по фул тайму?

**Comment by alecvert** [comment]
перерабатываем это в стилистике шаблона сайта? (Белый, серый, синий, зеленый)?
эти круги контейнеры оставляем или делаем чисто иконки? - пообщайся по стилистике с Вовой. 
время на исполнение (нужно учесть, что браться в полную силу пока не могу пока не сдам текущий проект ).- оцени пдлст сам. Несколько дней достаточно?
стоимость работы ? Это как проектный заказ или это заказ по фул тайму?- работа чисто на эти иконки. Далее соответственно следующая. Оцери пжлст. Мы согласуем

**Comment by cptn-solo** [comment]
@RomaRAD вообще схема работы у нас [такая](https://github.com/u-transnet/info/wiki/2.-Принять-участие), но "гуманитариям" я предоставляю свои услуги (бесплатно) няньки. 
Пояснения в контексте твоего вопроса об оплате все же приведу, мало ли потом кто-то еще спросит - будем показывать этот мой комментарий:

НЕ зависимо от того, проектный это заказ или нет - твою ставку мы зафиксировали в [задаче](https://github.com/u-transnet/www-teaser/issues/16#issuecomment-346579403), в которой тебя приняли в команду. Ставка за день работы (можно дробить хоть до минуты - решать тебе) исчисляется исходя из 1/20 месячной ставки. Пожалуйста, оцени - сколько твоего _рабочего_ времени займет итерация по этой задаче, и дату обсуждения с командой результата этой итерации и зафиксируй предполагаемый результат итерации здесь. Мы решаем, понятен ли нам ожидаемый результат, и адекватна ли оценка трудозатрат - и если все ок - я завожу под твое время резерв средств в блокчейне и ты можешь приступать. 
Если все прошло гладко и работа по итерации считается принятой - ты коммитишь промежуточный результат (исходники) в бранч [prorotyping](https://github.com/u-transnet/www-teaser/tree/prototyping) и после этого сразу получаешь оплату (хочешь - копишь на счету, хочешь - выводишь сразу, как удобно). 
Если к назначенному сроку заявленные результаты итерации не предоставлены - начинаем арбитраж. 
Это все не так страшно, но у нас команда, и все друг от друга реально зависят. И у нас не обманывают - блокчейн штука дерзкая и бескомпромиссная. Что пообещал - потом не съехать (работает в оба конца. если тебе кто-то должен - не отвертеться).

**Comment by cptn-solo** [comment]
Результаты обсуждения концепции иконок перенес в задачу на итерацию ( #24 )

**Comment by RomaRAD** [comment]
27 в ПН начну работу по созданию трех первых иконок. Во ВТ 28 к 13:00 вышлю варианты в двух возможных подходящих для сайта видах. 2 дня .

**Comment by cptn-solo** [comment]
> 27 в ПН начну работу по созданию трех первых иконок. Во ВТ 28 к 13:00 вышлю варианты в двух возможных подходящих для сайта видах. 2 дня .

Понял. Оценка переезжает в задачу на итерацию №1 ( #24 ) 
Эту закрываем.

**Comment by RomaRAD** [comment]
Салют! 
Сделал иконки + поправил башню. Жду ваших мыслей и комментариев.
![_ 1](https://user-images.githubusercontent.com/33925750/33302316-f747cbe8-d41c-11e7-8d77-b9807cbce702.jpg)
![_ 2](https://user-images.githubusercontent.com/33925750/33302317-f78251be-d41c-11e7-85ed-7a962cd9f479.jpg)

**Comment by kkrupovich** [comment]
@RomaRAD 
Лучше перенеси плз этот шедевр в #24 т.к. мы там фиксировали требования и эта задача уже закрыта. Потом я перенесу туда свои комментарии:
1. Мне нравится больше первый вариант, иконки мне лично понятнее ;
2. Иконки первого варианта вообще не вызывают никаких вопросов, т.ч. по существу лично я бы их принял прямо такими; 💯 
2. Плашка "ПРЕИМУЩЕСТВА" - надо смотреть в общей картине, но имхо по насыщенности перегруз - подавляет само содержимое раздела;
3. Раскладку этикеток технологий по башне надо будет согласовать - подумать какими правилами руководствоваться - что идет в базис, что сверху. Пока очевидно, что мы можем использовать уровни башни для **демонстрации своей компетентности** в технологиях - что на чем построено - это **суперважно**;
4. ИМХО основание башни можно сделать немного тоньше. 

Общий вопрос - мы под башню отдельную задачу заводили - и я бы все же продолжал обсуждение башни в #18 , если технически возможно редактировать башню отдельно.
