### ISSUE TITLE
Разработать структуру сайта 

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#22]
Разработать структуру сайта в виде майндмэпа.
Какие нам разделы нужны?
какие действия будут на страницах?
какой сценарий пользователя?
Ответ на эти и другие вопросы будут доступны после первой итерации, и в последующем допилится все командой

[Вики ПРО РАЗДЕЛЫ САЙТА](https://github.com/u-transnet/www-teaser/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82-%D0%B8-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%8B)

**Comment by cptn-solo** [comment]
@jackal1527 
Отличная задача. Вики бардак. Вот в нем и надо наводить порядок, возможно, в рамках этой задачи

**Comment by alecvert** [comment]
@jackal1527 задача норм после тизера приступим
