### ISSUE TITLE
НА САЙТ_Отрисовка иллюстрации по оцифровке точки системы

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#23]
Показать оцифровку физической точки системы.
Исходники в [prototyping/digital-point](https://github.com/u-transnet/www-teaser/tree/prototyping/digital-point)

За смыслом идем к @alecvert 
А я нарисовал вручную как оно должно быть
Далее нужно творчество
![default](https://user-images.githubusercontent.com/32764532/33175266-00f7d988-d07d-11e7-93b6-2884dcc92f26.jpg)

Референс по стилю:
![default](https://user-images.githubusercontent.com/32764532/33175832-c5c8bd9e-d07e-11e7-9c0e-bdba0af28c35.jpg)

Референс по оцифровке
![maxresdefault](https://user-images.githubusercontent.com/32764532/33176012-5c676eb2-d07f-11e7-8969-83e14ae6e4ce.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert понедельник 27 ноября 2017 в первой половине дня обсуждаем и предварительно формируем свое вИдение для дальнейшего донесения до исполнителя

**Comment by alecvert** [comment]
@kkrupovich @jackal1527 @RomaRAD Как я вижу эту картинку  http://prntscr.com/hgd7vc см. видео  чуть укоротить сделать в изометрии, увеличить и половину сделать реальной , а вторую половину оцифрованной в виде проволоки , которая показана на картинке выше. См. видео https://www.youtube.com/watch?v=ZdcmaXbx9sc 0:29-0:33

Ещё нюанс надо добавить посередине подвижной состав и разрезать его напополам, часть будет реальная, а часть оцифрованная.

Просто если мы будем показывать высотную станцию, которая у нас представлена сервером, то будет повторения на сайте.

**Comment by cptn-solo** [comment]
Решили попробовать посмотреть такой вариант:
<img width="783" alt="screen shot 2017-12-04 at 18 20 16" src="https://user-images.githubusercontent.com/1105555/33560155-f76c875a-d91f-11e7-9f10-ffab5766fd6e.png">

![photo_2017-12-05_10-45-55](https://user-images.githubusercontent.com/1105555/33595542-8854fae8-d9a9-11e7-93c4-3eec0c292c5f.jpg)

<img width="736" alt="screen shot 2017-12-05 at 10 47 17" src="https://user-images.githubusercontent.com/1105555/33595594-b7450262-d9a9-11e7-97c3-1d9ccbf664d3.png">

**Comment by cptn-solo** [comment]
0. изометрия
1. мобильная версия - одна опора (слева) + юнибайк наполовину оцифрованный;
2. сайт - два юнибайка, едущих друг от друга + две станции по краям. Оцифрованы правая станция, рельсы и юнибайк;

**Comment by cptn-solo** [comment]
BLOCK #22590603
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 120.00000 UTDEV.SKILL

> Смотрим в четверг вечером 14 декабря 2017

**Comment by cptn-solo** [comment]
@jackal1527 @RomaRAD есть предложение попробовать разместить изображение по диагонали, а подписи разнести в противоположные углы так же по диагонали (слева подпись будет сверху над реальной, а справа - снизу, под цифровой точкой)
![screenshot_14](https://user-images.githubusercontent.com/1105555/33900717-87cae628-df80-11e7-95b6-4220dffe5f47.jpg)

**Comment by RomaRAD** [comment]
Так это увидел
![_1](https://user-images.githubusercontent.com/33925750/33986854-b1743068-e0e0-11e7-94ce-1828551c4ccf.jpg)

**Comment by RomaRAD** [comment]
Еще был вариант 
@jackal1527 @kkrupovich @alecvert 
![_2](https://user-images.githubusercontent.com/33925750/33986872-c27247c4-e0e0-11e7-9fd9-6b89c29fb782.jpg)

**Comment by alecvert** [comment]
@RomaRAD мне нравится второй вариант. Деталька с облаками классно.

Цифровую половину сетку лучше оставить на земле, спереди и сбоку убрать и добавить то, что на 1 варианте было пунктиром с линиями

**Comment by alecvert** [comment]
@RomaRAD мне нравится второй вариант. Деталька с облаками классно.

Цифровую половину сетку лучше оставить на земле, спереди и сбоку убрать и добавить то, что на 1 варианте было пунктиром с линиями.

Не забудь про станции. Также лучше еще добавить над юнибайком, станцией и путевой структурой названия учетных записей типа. Проконсультируйся с @kkrupovich

**Comment by cptn-solo** [comment]
@RomaRAD 
- за основу берем синий вариант
- добавляем облака (в реальность) 
- добавляем деревья (в реальность)
- цифровой байк - убираем внутренние линии (делаем непрозрачным + пытаемся сделать его полигональным), 
- цифровая опора - убрать детали, внутренности, сделать непрозрачной, добавить проволоку
- подписи на платформе -  TRANSNET SPACE (transnet - заканчивается на точке разделения, space - начинается от точки разделения)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
![__3](https://user-images.githubusercontent.com/33925750/33994387-23d406f4-e0fc-11e7-80f8-a2084330c606.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 @RomaRAD @alecvert 
- Второй (нижний)
- Большое (слева) дерево я бы убрал, имхо перегруз. Или куст туда какой-нибудь может просто воткнуть по-меньше

**Comment by cptn-solo** [comment]
@RomaRAD папка для исходников в бранче prototyping: [prototyping/digital-point](https://github.com/u-transnet/www-teaser/tree/prototyping/digital-point)

**Comment by alecvert** [comment]
@RomaRAD второй вариант нижний супер

По дереву большому можно попробовать еще поменьше сделать, но на мой взгляд перегруза нет, так как показывает визуально то, что струнные рельсы находятся высоко на опорах

**Comment by RomaRAD** [comment]
оцифровка точки 
![screenshot_18](https://user-images.githubusercontent.com/33925750/34002384-46e8e03e-e114-11e7-9f01-db27b552a81d.jpg)
Исходник тут https://github.com/u-transnet/www-teaser/commit/ddb5ba47d1b14de8441053e91660f4edd5088b2b

**Comment by cptn-solo** [comment]
Все, замечания в #60 , эту закрываем как базовую реализацию. 

BLOCK #22647113
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV

Спасибо!
