### ISSUE TITLE
Верстка transnet.tech по предварительному макету

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#26]
собираем все, что нам сейчас хочется воткнуть в 0ю итерацию:
надо выделить функции лендинга. На мой взгляд список задач выглядит так (и мы его сейчас начнем корректировать):
0. Отстраиваем структуру поддоменов (dev.transnet.tech -> test.transnet.tech -> (www.)transnet.tech;
1. берем макет из последней итерации #20  , режем (кто?) и верстаем @UspenskyDritry расскажет где делать бранч, у нас есть репозитории под оба домена;
2. из интерактива (по функционалу, не по всплывающим подсказкам) у нас есть:
2.1 переключение локали - с учетом этой фичи должен отстраиваться движок. Необходимо предусмотреть возможность расширения списка без изменения движка. Изначально - два элемента - русский основной, английский - доступен для выбора;
2.2 периодический запрос номера блока из целевого БЧ ( @UspenskyDritry плз откомменти куда лезть в наших репах, где это сформулировано или может даже уже есть скрипт - а он есть на ск. я помню);
2.3 форма регистрации в блокчейне - это переход на форму регистрации, для которой есть API - пока необходима заглушка в домене (и репозитории)  transnet.space и уход с сайта на эту заглушку;
2.3 ссылки на инфо-каналы (git в первую очередь, т.к. там инфа о продукте, потом - twitter, и, вероятно, какой-то публичный чат в телеге);

3. предлагаю метки локализации компоновать в файлы с разумной структурой и возможностью 
внесения изменений непосредственно через github  и пулл-реквесты.

4. предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация) ;

@EvgeniyPolyakov предлагаю собрать пункты для 0-й итерации и обозначить срок

**Comment by EvgeniyPolyakov** [comment]
в качестве css-фреймворка используем Bootstrap
в качестве методологии - БЭМ от Яндекса

0-я итерация:
  - разворачивание структуры
  - кросс-браузерная верстка 1го экрана
  - база для локализации

время: конец рабочего дня 28.11, при условии получения макета за день минимум

**Comment by EvgeniyPolyakov** [comment]
BLOCK #22157245 eugene-polyakov 100.00000 UTDEV.SKILL

до вечера 28 ноября 
Возможно в изменении объема если не будет макета

**Comment by EvgeniyPolyakov** [comment]
Закомитил 0-ю итерацию по верстке. Десктоп, планшеты и смартфоны.
[В новую ветку MarkUp ](https://github.com/u-transnet/www-teaser/tree/MarkUp)

По локализации - так как данных немного, нет смысла организовывать модульность - все словари будут в 1м файле. Следующим таском уже можно ставить локализацию.

**Comment by cptn-solo** [comment]
> Закомитил 0-ю итерацию по верстке. Десктоп, планшеты и смартфоны.
В новую ветку MarkUp

@EvgeniyPolyakov 
Просьба исходники коммитить (в бранчи по gitflow) в реп u-transnet/transnet.tech ( @UspenskyDritry уже там обосновался с заглушкой )

**Comment by cptn-solo** [comment]
> 0. Отстраиваем структуру поддоменов (dev.transnet.tech -> test.transnet.tech -> (www.)transnet.tech;

Новый сайт - отдельная папка, @UspenskyDritry надо нам с тобой посмотреть можем ли мы это сделать. Под следующую итерацию обязательно сделать, т.к. многие вещи локально просто не посмотреть (особенно из анимации и в мобильном браузере - приходится шаманить)

> 1. берем макет из последней итерации #20  , режем (кто?) и верстаем @UspenskyDritry расскажет где делать бранч, у нас есть репозитории под оба домена;

разрезали, сверстали шапку (1ю страницу) 

> 2. из интерактива (по функционалу, не по всплывающим подсказкам) у нас есть:

> 2.1 переключение локали - с учетом этой фичи должен отстраиваться движок. Необходимо предусмотреть возможность расширения списка без изменения движка. Изначально - два элемента - русский основной, английский - доступен для выбора;

Делаем список выпадашкой/тесла, активный язык на элементе, открывающим список 

> 2.2 периодический запрос номера блока из целевого БЧ ( @UspenskyDritry плз откомменти куда лезть в наших репах, где это сформулировано или может даже уже есть скрипт - а он есть на ск. я помню);

Остается

> 2.3 форма регистрации в блокчейне - это переход на форму регистрации, для которой есть API - пока необходима заглушка в домене (и репозитории)  transnet.space и уход с сайта на эту заглушку;

Остается

> 2.3 ссылки на инфо-каналы (git в первую очередь, т.к. там инфа о продукте, потом - twitter, и, вероятно, какой-то публичный чат в телеге);

Остается, есть задача #7 

> 3. предлагаю метки локализации компоновать в файлы с разумной структурой и возможностью внесения изменений непосредственно через github  и пулл-реквесты.

Решили сделать один большой файл и запилить в следующей итерации совместно с переключателем локали

> 4. предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация) ;

Остается

@EvgeniyPolyakov предлагаю собрать пункты для 1-й итерации и обозначить срок

**Comment by kkrupovich** [comment]
1. Верстаем один блок до "принципов токенизации" включительно и смотрим верстку;
2. Уходим от нескольких элементов управления для выбора языка, делаем выпадающий список с названиями языков на нативном алфавите для каждого ( @jackal1527 предоставляет макет #37)
3. метки локализации: сделать один общий файл и запилить в следующей итерации совместно с переключателем локали
4. Настраиваем стуктуру поддоменов (пробуем мы @UspenskyDritry );
5. Заглушка под форму регистрации - проработать заготовку сайта transnet.space (уже есть [репозиторий](https://github.com/u-transnet/transnet.space) и сам сайт - там тоже надо сделать структуру поддоменов и положить заглушку туда  - @UspenskyDritry нам посмотреть)
6. Подготовить заготовки под Git, Facebook, VK, Twitter, Telegram, Medium ( @jackal1527 предоставляет макет #38 ), реальные ссылки готовятся в задаче #7 ( @alecvert @kkrupovich)
7. предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация) ;

**Comment by cptn-solo** [comment]
Продолжаем в рамках #40 эту принимаем и закрываем

**Comment by cptn-solo** [comment]
BLOCK #22209968 
TRANSFER |  
From | utd-web
To | eugene-polyakov
Quantity | 100.00000 UTDEV
Спасибо!
