### ISSUE TITLE
ДЛЯ САЙТА_Иконки услуга_пассажир_груз

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#28]
Услуга/пассажир/груз (создать задачу для иконок)
Плашку развернуть горизонтально ( по примеру иконки гитхаба, что рядом)
##  Услуга 
- пицца (может быть коробка с пиццей открытая), можно что то что ассоциируется с доставкой еды

##  Пассажир 
- сидушка/поручень (можно что то близкое к этой ассоциации)

##  Груз
- палет с коробками ( ну коробки вродь тут все ясно)

![default](https://user-images.githubusercontent.com/32764532/33317704-c1e30ba6-d459-11e7-98a9-202ea067d232.jpg)

**Comment by alecvert** [comment]
@jackal1527 @RomaRAD @kkrupovich Пассажир вот хороший пример http://prntscr.com/hgciqs , стилизовать естественно надо

Груз - контейнер, см. https://www.youtube.com/watch?v=ZdcmaXbx9sc , см. http://prntscr.com/hgoady только две паллеты сделать. 
а вообще можно и 2д юнитрака см. http://prntscr.com/hgcy70 , видео https://www.youtube.com/watch?v=UVHbUTsse98 . 

Услуга пицца с лого U-tech (перекрещивающиеся U) в виде колбасок , либо U c двумя линиями справа , см. http://prntscr.com/hgoazz

**Comment by cptn-solo** [comment]
Оцениваем в 1 день. Смотрим в понедельник, 4 декабря, вечером, либо во вторник 5го декабря утром. 
@RomaRAD лайкни плз и я закину скилл

**Comment by kkrupovich** [comment]
BLOCK #22361183
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
> Смотрим в понедельник, 4 декабря, вечером, либо во вторник 5го декабря утром.

**Comment by cptn-solo** [comment]
BLOCK #22361329
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL
> Смотрим в понедельник, 4 декабря, вечером, либо во вторник 5го декабря утром.

Вроде договорились на 12че на 5е декабря

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
![default](https://user-images.githubusercontent.com/33925750/33593606-f6bfebfc-d9b1-11e7-834b-465d07257fb5.jpg)

**Comment by RomaRAD** [comment]
![default](https://user-images.githubusercontent.com/33925750/33594303-41182aa4-d9b5-11e7-8e99-79ea22078441.jpg)
@alecvert  мы хотим сделать акцент именно на услуге доставки еды? Мне кажется что пицца - очень узко для иконки.

**Comment by cptn-solo** [comment]
1. груз - клешню меняем на паллет, ящик визуализируется под контейнер, добавить "скорость" слева (можно даже немного сместить груз вправо);
2. пассажир - голова пассажира - убрать детали;
3. услуга - пробуем пиццу без коробки;
4. подписи - service, travel, freight - в сайте @EvgeniyPolyakov предусмотреть ховер с локализованными метками;

**Comment by cptn-solo** [comment]
@RomaRAD предлагаю в [icons-misk](https://github.com/u-transnet/www-teaser/tree/prototyping/icons-misk) исходники по готовности сливать (для всех иконок явно не относящихся к какому-то значимому куску)

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert 
![default](https://user-images.githubusercontent.com/33925750/33599987-bd3c66b8-d9c9-11e7-9759-d2e2a61b7014.jpg)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich 
![default](https://user-images.githubusercontent.com/33925750/33600041-ec2138a0-d9c9-11e7-9fd4-3047c3078b4f.jpg)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich 
![default](https://user-images.githubusercontent.com/33925750/33600219-6b36fdfa-d9ca-11e7-9f1f-7d72162ce0f2.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD @alecvert 

1. Пицца - чего-то пицца не аппетитная какая-то. Может, мы ее повернем как-нибудь? градусов на 30 против часовой. чтобы она была в той же плоскости, что и пассажир и груз; И можно вытащить один из ее углов за круг даже - но не острый, а левый нижний я бы вытащил;

2. Надписи - кстати надписи очень норм. но надо смотреть на общий макет - чтобы с тем же гитхабом не конфликтовал стиль.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich 
![2](https://user-images.githubusercontent.com/33925750/33604839-3eb419de-d9d9-11e7-80b4-97b5ca0f1469.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD о боги :)))) Я и раньше знал, что тебе идея с пиццей не очень по душе, но не думал, что на столько :))

**Comment by cptn-solo** [comment]
@alecvert я сдаюсь. давайте оставим коробку с галочкой. Если Рому идея не вдохновляет - думаю нет смысла упорствовать. Коробка была неплоха вполне. 
<img width="153" alt="screen shot 2017-12-05 at 14 31 47" src="https://user-images.githubusercontent.com/1105555/33605036-1ebcdfae-d9c9-11e7-80c1-0f3f6de5bddb.png">

**Comment by alecvert** [comment]
@RomaRAD 
1. ![image](https://user-images.githubusercontent.com/30151576/33612783-83bd6b5a-d9f4-11e7-9cdb-ed4348ab4019.png) норм

2. http://prntscr.com/hjexlm
![image](https://user-images.githubusercontent.com/30151576/33612851-b7f6d0e6-d9f4-11e7-9ec1-701e360d810d.png) контейнер не должен левитировать, это же не магнитная левитация или поезд на магнитной подушке

http://prntscr.com/hjeys4 freight только пишется

3. Услуги как вариант 
![image](https://user-images.githubusercontent.com/30151576/33615496-214cb07c-d9fc-11e7-9519-3186ae735a2f.png)

![image](https://user-images.githubusercontent.com/30151576/33617060-9253db48-da00-11e7-8e6c-94c9f50b0099.png)
![image](https://user-images.githubusercontent.com/30151576/33613265-014873ac-d9f6-11e7-8261-b586142cd6b4.png) 
![image](https://user-images.githubusercontent.com/30151576/33613317-29489832-d9f6-11e7-81c4-0447dbb5d9c8.png) 
![image](https://user-images.githubusercontent.com/30151576/33613475-8879e464-d9f6-11e7-9f6e-3cdf51ea747b.png)

Или во 
![image](https://user-images.githubusercontent.com/30151576/33613407-5fcd1fe0-d9f6-11e7-88e3-6b7873cab492.png) 
![image](https://user-images.githubusercontent.com/30151576/33613855-888a9d94-d9f7-11e7-998a-9f719851991c.png)
 тележка магазинная . 

Или play, всмысле то, что услуга это действие

Также почтовый голубь

Либо SHOP, иконка магазина 
![image](https://user-images.githubusercontent.com/30151576/33613829-743451b4-d9f7-11e7-912a-bf9961f2bb04.png)


Либо ветряк 
![image](https://user-images.githubusercontent.com/30151576/33613739-356e89ea-d9f7-11e7-9d2e-b6f95ee68e1d.png)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich 
Инструменты больше ассоциируются с ремонтом. Сделал тележку и магаз
![default](https://user-images.githubusercontent.com/33925750/33662969-de9ef2da-daaf-11e7-8836-796e4648249a.jpg)

**Comment by RomaRAD** [comment]
@alecvert  выложу сюда, ты это имел в виду? ![default](https://user-images.githubusercontent.com/33925750/33663275-2321ce04-dab1-11e7-9085-5f8e625db076.jpg)

**Comment by cptn-solo** [comment]
@alecvert @RomaRAD имхо - тележка - необходимое зло. предлагаю взять ее. первую причем. 
Умные активы норм. не испортили.

**Comment by alecvert** [comment]
@RomaRAD тележка ок, но как предложение тоже чашка кофе или чая.

Алмаз с кодом хорошо

**Comment by alecvert** [comment]
@RomaRAD тележка ок, но как предложение тоже чашка кофе или чая.

Алмаз с кодом хорошо

**Comment by RomaRAD** [comment]
Товар кофе
@alecvert 
![default](https://user-images.githubusercontent.com/33925750/33729507-bcce664a-db9f-11e7-8d99-9752930c6506.gif)

**Comment by cptn-solo** [comment]
1

**Comment by alecvert** [comment]
@RomaRAD первая, согласен

**Comment by RomaRAD** [comment]
Залил исходники https://github.com/u-transnet/www-teaser/commit/35e1112046178bfcb31008c6b2c1a0408e2ec0c9
@alecvert @kkrupovich 
![_](https://user-images.githubusercontent.com/33925750/33758665-f5a54b74-dc20-11e7-9520-c6b7916db3a2.jpg)

**Comment by cptn-solo** [comment]
Задачу закрываю, но @RomaRAD исправь пож. подпись "Freigh" на "Freight" и перезалей исходники поверх старого файла

BLOCK #22555950
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 60.00000 UTDEV
Спасибо!

**Comment by cptn-solo** [comment]
Продолжаем доработки в общей задаче и итерациях к ней #54
