### ISSUE TITLE
ДЛЯ САЙТА_иконки внизу схемы

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#29]
Отрисовать данные иконки примерно в этом же стиле.
Их нужно привести к общему знаменателю со всей стилистикой сайта, тк сейчас это просто на-черновую нарезанный джипег.

![default](https://user-images.githubusercontent.com/32764532/33317979-c4193570-d45a-11e7-8aa7-81d37d5c1de0.jpg)

**Comment by cptn-solo** [comment]
Делаем в составе #58
