### ISSUE TITLE
ДЛЯ САЙТА_иконка гитхаба

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#30]
Небольшая задачка отдельно отрисовать в векторе данную иконку + (что важно) сохранить отдельно "базу" данной иконки , чтоб на нее можно было поставить любую другую иконку

![default](https://user-images.githubusercontent.com/32764532/33318021-f5ab22ec-d45a-11e7-9f69-fb97bc1cd27b.jpg)

**Comment by cptn-solo** [comment]
Делаем в составе #58
