### ISSUE TITLE
ДЛЯ САЙТА_иконки для карты

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#31]
Нужно отрисовать иконки в стиле сайта. они встанут потом на карту.

### ТРАНС-ЛАЙН
это путевая структура - балки лежащие на опорах
### ТРАНС-БОТ
Вагончик багающий по балкам. (он по форме норм но не в стиле сайта)
### ТРАНС-СЕРВЕР
его мы отрисовывали выше (над картой) - нужно сделаеть его в более мелком масштабе, для чего естественно недостаточно просто уменьшить в размерах)
### ТРАНС-СЕРВИС
Пока что используем примерно тот же знак что нарисован.
@kkrupovich @alecvert давайте подумает что сюда можно сделать.

![default](https://user-images.githubusercontent.com/32764532/33318101-3bbcc588-d45b-11e7-9db1-fc012284df7f.jpg)

**Comment by alecvert** [comment]
@RomaRAD Trans-line, см. http://prntscr.com/hgc29d 0.25 см. видео http://prntscr.com/hgc987, но лучше изобразить её двухпутной как здесь http://prntscr.com/hgd0ua , см. видео 1:58 https://www.youtube.com/watch?v=VBhHanivY_Y

Trans-Bot, в принципе хорошо нарисовано, но надо изменить цвет и подкорректировать http://prntscr.com/hgc4x7 см. видео https://www.youtube.com/watch?v=nYjo9kQ9ugY и также см. фото , см. также видео https://www.youtube.com/watch?v=VBhHanivY_Y (1:40 юнибайк крутится в проекции)

Также подв состав см. фото 
![1](https://user-images.githubusercontent.com/30151576/33322924-b426e07e-d46c-11e7-8bbf-4a90e8c9b1f0.jpg)
![2](https://user-images.githubusercontent.com/30151576/33322925-b44a7a16-d46c-11e7-80a7-03c206f8ee99.jpg)
![3](https://user-images.githubusercontent.com/30151576/33322926-b46cbbb2-d46c-11e7-8a40-51aad519b054.jpg)
![4](https://user-images.githubusercontent.com/30151576/33322927-b48b3060-d46c-11e7-89b9-9f08cd4582c4.jpg)

Trans-Server нарисовано хорошо, просто примени свою версию, только не сильно разукрашенную

Trans-Service , да пока знак вопроса, можно подписать New ( типа новое направление )

**Comment by alecvert** [comment]
@jackal1527 @kkrupovich @RomaRAD   мужики, есть нюанс, что мы показываем в виде бота только юнибайк, а есть ещё юнитрак ( грузовой ) и юникар/юнибус (городской пассажирский) , надо ли отдельный другие иконки Trans-Bot или нагрузит сильно уже ?

**Comment by cptn-solo** [comment]
> @jackal1527 @kkrupovich @RomaRAD мужики, есть нюанс, что мы показываем в виде бота только юнибайк, а есть ещё юнитрак ( грузовой ) и юникар/юнибус (городской пассажирский) , надо ли отдельный другие иконки Trans-Bot или нагрузит сильно уже ?

Визуально - только юнибайк уникален. остальные - не ассоциируются с tn|sw

**Comment by cptn-solo** [comment]
@RomaRAD контекст, в котором можно посмотреть на эти иконки - в [задаче по макету сайта](https://github.com/u-transnet/www-teaser/issues/45)

**Comment by cptn-solo** [comment]
Итерация на 2 дня (до черверга, в течение дня смотрим)

**Comment by cptn-solo** [comment]
BLOCK #22380682
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 120.00000 UTDEV.SKILL
> Итерация на 2 дня (до черверга, в течение дня смотрим)

**Comment by cptn-solo** [comment]
@RomaRAD создал папку [map в бранче prototyping](https://github.com/u-transnet/www-teaser/tree/prototyping/map) под исходники

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich  
В ту степь? мне нужно понять, что бы продолжать.

![3_](https://user-images.githubusercontent.com/33925750/33658169-8f0d36bc-da9d-11e7-81ed-210f8fb0c9ba.jpg)

**Comment by cptn-solo** [comment]
так-то вроде в ту, но как это пополам разрезать, если оно не в профиль к нам повернуто не совсем понимаю.

**Comment by RomaRAD** [comment]
Правильно же понимаю, что мы для этого раздела делаем иллюстрашку? 
![33318101-3bbcc588-d45b-11e7-9db1-fc012284df7f](https://user-images.githubusercontent.com/33925750/33663586-6aba96e6-dab2-11e7-80ff-e1503c2874b8.jpg)

**Comment by alecvert** [comment]
@RomaRAD очень в ту, путевую структуру принял

**Comment by alecvert** [comment]
@RomaRAD Правильно же понимаю, что мы для этого раздела делаем иллюстрашку?- Да, Ром, все верно, правильно понимаешь

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich уффф.., транс-бот вроде доделал.
Пока торможу, не типичная задачка для меня
![default](https://user-images.githubusercontent.com/33925750/33712764-6ba1ec86-db6a-11e7-96f5-b0a23bbd5c54.jpg)

**Comment by alecvert** [comment]
@RomaRAD принимаю!

**Comment by cptn-solo** [comment]
Следующая итерация подготовлена, #51, просьба оставшиеся иконки прорабатывать в ней. 
По этой итерации предлагаю уже готовить файл с исходником и по мере приемки выкладывать в [map](https://github.com/u-transnet/www-teaser/tree/prototyping/map)

**Comment by RomaRAD** [comment]
Сделал упрощенный вариант. Оба варианта исходников залил сюда https://github.com/u-transnet/www-teaser/commit/68be79180f3650a816a333fc26655b9313c14f49
![default](https://user-images.githubusercontent.com/33925750/33759468-46a4eefa-dc24-11e7-8c27-628fd505f7c9.jpg)
@alecvert @kkrupovich

**Comment by alecvert** [comment]
@RomaRAD все хорошо, только у юнибайка затонированные стекла сделай пжлст, а не голубые

**Comment by RomaRAD** [comment]
@alecvert  норм?
![default](https://user-images.githubusercontent.com/33925750/33768169-c2566c82-dc46-11e7-9d74-a92f5c16eff7.jpg)

**Comment by alecvert** [comment]
@RomaRAD да , Рома, хорошо. Ждем станцию)

**Comment by alecvert** [comment]
@RomaRAD да , Рома, хорошо. Ждем станцию)
Ps а что обозначают голубые линии по середине путевой структуры?

**Comment by cptn-solo** [comment]
BLOCK #22478015
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV
@RomaRAD жду исходники того, что уже есть.
Спасибо!
