### ISSUE TITLE
ДЛЯ САЙТА_трилистник

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#32]
Отрисовать в векторе в стиле сайта. желательно оставить объем кружочкам.

![default](https://user-images.githubusercontent.com/32764532/33318323-1530918c-d45c-11e7-9763-31e257025ec6.jpg)

**Comment by alecvert** [comment]
@kkrupovich @jackal1527 @RomaRAD коллеги, просто стилизуем этот трилистник или же как фон кружочков тоже делаем что-то?

**Comment by jackal1527** [comment]
а вот пока хз - давайте сначала отрисуем потом соберем и посмотрим. не думаю что итерация много времени потребует

**Comment by cptn-solo** [comment]
Делаем в составе #58
