### ISSUE TITLE
ДЛЯ САЙТА_отрисовать карту в стиле сайта

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#35]
Отрисовать карту в стиле сайта. 
Сеть с точками должна быть "объемной" (то есть соединения между точками можно сделать не прямыми а "дугой", куак-будто она поднимается над землей и снова опускается в точку)

![default](https://user-images.githubusercontent.com/32764532/33336337-6775acea-d491-11e7-880d-5d84b85fcf1d.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD @alecvert подумать над стилистикой линий и точек, упростить, минимизировать детализацию.

**Comment by cptn-solo** [comment]
Продлолжаем в общей задаче #54 и итерациях к ней
