### ISSUE TITLE
Подготовить заготовки под Git, Facebook, VK, Twitter, Telegram, Medium

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#38]
Для верстки уже нужны иконки и понимание - где размещаем

**Comment by alecvert** [comment]
Социальные сети: github, bitcointalk, twitter, telegram, youtube, facebook, вконтакте, steemit, golos , medium.com, instagram

**Comment by jackal1527** [comment]
Готово.
https://github.com/u-transnet/www-teaser/blob/prototyping/icons_social
тут соцсети
