### ISSUE TITLE
Разобраться со структурой поддоменов для сайтов transnet.tech/transnet.space

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#39]
Настраиваем стуктуру поддоменов, dev. закрываем паролем, test. оставляем открытым - будем туда сливать соотв. бранчи сайтов (пока на space - будет только заглушка формы регистрации)

**Comment by DmitryUspensky** [comment]
@kkrupovich, прописал домены в DNS Digital Ocean. Подождем 1-2 часа NS обновятся.

**Comment by cptn-solo** [comment]
@UspenskyDritry @EvgeniyPolyakov вроде подцепились. дальше я так понимаю можно уже в nginx отстраивать? Если так - то эту задачу можно закрывать
