### ISSUE TITLE
Итерация №1 Верстка transnet.tech по предварительному макет

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#40]
Продолжаем верстку, пред. итерация #26 

1. Верстаем один блок до "принципов токенизации" включительно и смотрим верстку;
2. Уходим от нескольких элементов управления для выбора языка, делаем выпадающий список с названиями языков на нативном алфавите для каждого ( @jackal1527 предоставляет макет #37)
3. метки локализации: сделать один общий файл и запилить в следующей итерации совместно с переключателем локали
4. Настраиваем стуктуру поддоменов (пробуем мы @UspenskyDritry );
5. Заглушка под форму регистрации - проработать заготовку сайта transnet.space (уже есть [репозиторий](https://github.com/u-transnet/transnet.space) и сам сайт - там тоже надо сделать структуру поддоменов и положить заглушку туда  - @UspenskyDritry нам посмотреть)
6. Подготовить заготовки под ( @jackal1527 предоставляет макет #38 ), реальные ссылки готовятся в задаче #7 ( @alecvert @kkrupovich)
7. предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация) ;

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov предварительно согласовали приемку на утро пятницы, т.е. 2 дня

**Comment by cptn-solo** [comment]
[созвон](https://calendar.google.com/event?action=TEMPLATE&tmeid=MTRkbGp0ajRrMGUyc3RuYzYzY2xmNXRpZmEgYXJhZGY5OTAwOGVkZnVpMzA2cnU2ZmQyZ2tAZw&tmsrc=aradf99008edfui306ru6fd2gk%40group.calendar.google.com)

**Comment by EvgeniyPolyakov** [comment]
БЛОК #22217620
От | eugene-polyakov
-- | --
Кому | utd-web
Количество | 100.00000 UTDEV.SKILL

до утра пятницы (1.12.2017)

**Comment by cptn-solo** [comment]
Следующая итерация #43

**Comment by cptn-solo** [comment]
Результат:

> 1. Верстаем один блок до "принципов токенизации" включительно и смотрим верстку;

ОК

> 2. Уходим от нескольких элементов управления для выбора языка, делаем выпадающий список с названиями языков на нативном алфавите для каждого ( @jackal1527 предоставляет макет #37)

На след. итерацию, есть в итерации макета ( #42 )

> 3. метки локализации: сделать один общий файл и запилить в следующей итерации совместно с переключателем локали

ОК

> 4. Настраиваем стуктуру поддоменов (пробуем мы @UspenskyDritry );

ОК

> 5. Заглушка под форму регистрации - проработать заготовку сайта transnet.space (уже есть [репозиторий](https://github.com/u-transnet/transnet.space) и сам сайт - там тоже надо сделать структуру поддоменов и положить заглушку туда  - @UspenskyDritry нам посмотреть)

Не успели. В след. итерацию

> 6. Подготовить заготовки под ( @jackal1527 предоставляет макет #38 ), реальные ссылки готовятся в задаче #7 ( @alecvert @kkrupovich)

На след. итерацию, есть в итерации макета ( #42 )

> 7. предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация) ;

Переносим на задачу деплоя на prod #44

**Comment by cptn-solo** [comment]
Принимаем, переходим дальше #43

**Comment by cptn-solo** [comment]
BLOCK #22267037
TRANSFER |  
From | utd-web
To | eugene-polyakov
Quantity | 100.00000 UTDEV
