### ISSUE TITLE
Анимационные элементы для сайта

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#41]
### Языковая панель
сделать иконку + всплывашку с переключением языков для десктопа и для мобилок
### Анимация для меню
всплывашка, которая будет появляться по нажатию на "бургер"
незабываем про соцсети: на десктопе - они по центру на сайте, на мобиле - скрытые во всплывалке
### Анимация и всплывашка при наведении на "сервак"
Иконки должны подсвечиваться

**Comment by cptn-solo** [comment]
Лишняя задача, все расписано в других уже
