### ISSUE TITLE
Сформулировать процедуру (скрипт) деплоя сайта на прод

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#44]
Включить: предусмотреть прогонять механизм прогона исходников через систему сборки - webpack и тп (контенкация, минимизация)

**Comment by EvgeniyPolyakov** [comment]
Ближе к релизу, если от фронт-энда требуется минимальная функциональность могу взять это на себя.

Алгоритм:

добавляем папку public
webpack генерирует оптмизированные скрипты и картинки в нее
в гит заливаются исходники как обычно, для продакшена все в public
деплой на сервер идет с папки public
домен смотрит в public

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov объединяем с рефакторингом и комментированием блоков - и скиллуем в день на праздники.

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23074670

От | eugene-polyakov
Кому | utd-web
Количество | 60.00000 UTDEV.SKILL

до вечера 5.01.2018

**Comment by cptn-solo** [comment]
- загрузка картинок вне экрана после загрузки основной разметки
- facebook метатеги (для оптимизации шаринга)
- fav-icon

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23275171

От | eugene-polyakov
Кому | utd-web
Количество | 60.00000 UTDEV.SKILL

Доскилловываем еще один день к задаче + доп таски к полдню 8.01.18

**Comment by EvgeniyPolyakov** [comment]
Сделано:

- скрипт для Gulp, который производит контенкацию и минификацию html, css и js
- также подключена оптимизация изображений lossless алгоритмами
- оптимизированные файлы заливаются в /public
- загрузка изображений, не входящих в 1й экран в фоновом режиме
- добавлены метатеги open graph 
 
Open Graph
http://ogp.me

Gulp
https://gulpjs.com

**Comment by cptn-solo** [comment]
надо направить public на dev.transnet.tech
Создал задачу #85 @EvgeniyPolyakov @UspenskyDritry

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov эту задачу пока закрываем, 
BLOCK #23353276
TRANSFER |  
From | utd-web
To | eugene-polyakov
Quantity | 120.00000 UTDEV
Спасибо!
