### ISSUE TITLE
Зафиксировать выбор технологической платформы с краткой аннотацией - почему выбрана

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#5]
Какой фреймворк, бд и т.п. - по мере формирования команды выясним наш стек разработки и выберем.

**Comment by DmitryUspensky** [comment]
@kkrupovich выбрал стек: BackboneJS (JS фреймворк), Bootstrap 3 (html/css фреймворк), RequireJS (для организации модульности).

**Comment by cptn-solo** [comment]
[зафиксировал в wiki](https://github.com/u-transnet/www-teaser/wiki/Технологическая-платформа-для-сайта-(для-соискателей))
