### ISSUE TITLE
(Итерация №2) ДЛЯ САЙТА_иконки для карты

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#51]
Пред. итерация #31 

Продолжаем в том же духе 
<img width="182" alt="screen shot 2017-12-07 at 15 00 47" src="https://user-images.githubusercontent.com/1105555/33714301-82ed055c-db5f-11e7-94b6-b273812e1439.png">
<img width="195" alt="screen shot 2017-12-07 at 15 00 52" src="https://user-images.githubusercontent.com/1105555/33714302-8312ea4c-db5f-11e7-94a7-2beecc52c71f.png">

Папка для исходников та же, [map](https://github.com/u-transnet/www-teaser/tree/prototyping/map), новые версии одного и того же файла не складывать рядом, а перезаписывать поверх - github помнит историю, кроме того если позволяет формат - сохраняет только изменения.

**Comment by cptn-solo** [comment]
@RomaRAD две иконки до вечера пятницы (8 декабря 2017) , 2 дня , норм?

**Comment by cptn-solo** [comment]
BLOCK #22449661
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 120.00000 UTDEV.SKILL
>  две иконки до вечера пятницы (8 декабря 2017)

**Comment by RomaRAD** [comment]
карта на пробу
![_](https://user-images.githubusercontent.com/33925750/33769805-5ca42e22-dc4d-11e7-94c8-f54fd22d2af8.jpg)

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert все изменения можно будет доработать на итоговом прототипе, когда будет очевидно что и какого размера будет на сайте. Пока исходник этой карты залил по по ссылке https://github.com/u-transnet/www-teaser/commit/55584fc84fa47c7ee14d443548397bbe878aaf53

**Comment by alecvert** [comment]
@RomaRAD Рома, такая карта не катит, нужно, что- то в стиле 
![image](https://user-images.githubusercontent.com/30151576/33783710-a815b9de-dc7f-11e7-87fa-45c80e9547e8.png)

![image](https://user-images.githubusercontent.com/30151576/33783759-d6f646ce-dc7f-11e7-99ad-5a5b40d8dccc.png)
более детализированная версия, только по воде не надо, по океанам

Также не надо закрашивать в голубой или синий цвет юнибайк и зелёным струнные рельсы на путевой структуре.

**Comment by cptn-solo** [comment]
Подготовил след. итерацию #55 

BLOCK #22556173
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV

Спасибо!
