### ISSUE TITLE
Общая задача на оцифровку БП, распределение согласно БП и иконку гитхаба

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#54]
Объединяем 3 задачи в одну, т.к. они небольшие и так удобнее планировать время (инициатива @RomaRAD)
Оцифровка бизнесплана (БП) #34 
Распределение согласно БП #33 
Иконка гитхаба #30 

@RomaRAD исходники предлагаю грузить в [icons-misk](https://github.com/u-transnet/www-teaser/tree/prototyping/icons-misk)

**Comment by cptn-solo** [comment]
BLOCK #22555772
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL
Смотрим завтра утром, 12 декабря 2017

**Comment by RomaRAD** [comment]
@jackal1527 @kkrupovich @alecvert 
Я понимаю, что они будут разными по размеру, просто объединил пока в одну композицию
![_](https://user-images.githubusercontent.com/33925750/33867712-596d0438-df20-11e7-9206-31c7cacf1d62.jpg)

**Comment by alecvert** [comment]
@RomaRAD хорошо, но у github синенький лого должен быть , а не зеленый и у github должно быть подписано GITHUB

**Comment by cptn-solo** [comment]
@jackal1527 коллега, твои комментарии?
Мне в целом все нравится, но ИМХО "трилистник" надо снабдить немного бОльшими шайбами. В скетче смотрелось как-то по-другому. насчет хаба согласен, но с хабом можно хитрее:
<img width="219" alt="screen shot 2017-12-12 at 12 55 21" src="https://user-images.githubusercontent.com/1105555/33878203-c3dabcf0-df3b-11e7-907f-6b630da44cf6.png">
т.е. его вообще инвертировать можно. Но я согласен, что гитхаб должен быть максимально темным цветом сделан из нашей палитры

**Comment by RomaRAD** [comment]
@kkrupovich  @alecvert  @jackal1527  поправил ![git](https://user-images.githubusercontent.com/33925750/33879040-0d36cc5a-df4f-11e7-804b-dcbcf28f1457.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD ну, как вариант, да.

**Comment by cptn-solo** [comment]
Собираем иконки в один файл, выкладываем для @EvgeniyPolyakov исходники в [icons-misk](https://github.com/u-transnet/www-teaser/tree/prototyping/icons-misk)
Добавляем скилл +1 день (сегодняшний)
BLOCK #22585445
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
Продолжаем в #58

**Comment by cptn-solo** [comment]
BLOCK #22590702
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV
Спасибо!
