### ISSUE TITLE
(Итерация №3) ДЛЯ САЙТА_иконки для карты

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#55]
Пришли из #51 (там описаны доработки)
Возьмем работу на этапе общей сборки карты.
@alecvert дополняет:
> Такие же оранжевые элементы, Ром, сделай пжлст как на первом экране. То есть не полностью цветом путевую структуру и т д. Цветом оранжевым знак вопроса можн

**Comment by cptn-solo** [comment]
@RomaRAD решили совместить с #18 

BLOCK #23049908
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL

> Смотрим в субботу утром 30 декабря 2017

**Comment by RomaRAD** [comment]
Хорошего дня!
@alecvert @kkrupovich @jackal1527 @nat-brit 
Отдельно элементы и общая страница с оранжевым.
![30_](https://user-images.githubusercontent.com/33925750/34452652-17a4960c-ed66-11e7-9da8-dc577e4767d3.jpg)
![30](https://user-images.githubusercontent.com/33925750/34452653-1b1181e2-ed66-11e7-9a03-aeb323332346.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD вроде +- все гармонично, так сходу не подкопаюсь ни к чему

**Comment by nat-brit** [comment]
Все хорошо:)

**Comment by alecvert** [comment]
@RomaRAD все замечательно!

**Comment by cptn-solo** [comment]
@RomaRAD исходники туда же, [map](https://github.com/u-transnet/www-teaser/tree/prototyping/map)? 

Закрываем
BLOCK #23123694
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 70.00000 UTDEV

Спасибо!
