### ISSUE TITLE
Итерация 2 Общая задача на оцифровку БП, распределение согласно БП и иконку гитхаба

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#58]
Пред. итерация #54 

> шайба (распределение согласно БП):  

- убираем с пьедестала
- возвращаем шриховку

> трилистник (токенизация, три токена):

- возвращаем штриховку
- увеличиваем размер монеток
- уменьшаем толщину площадки (ближе к "инвестиционных данных")

> карта:

- углы не те (от @jackal1527)
- линии меняем, т.к. это не баллистические ракеты

> услуга/пассажир/груз

- токены делаем залитыми цветом, контуры изображения - белым
- что-то надо делать с углом поворота изображения, либо наклоном самой монетки
![screenshot_13_02](https://user-images.githubusercontent.com/1105555/33900741-9cea0714-df80-11e7-9427-bb326c316daa.jpg)

- добавить T во freighT
- [попробовать тень отбросить на площадки]

> Иконки в конце схемы

- это отдельная задача #29 , но решили объединить c текущей

> Общее

- толщина линий

**Comment by cptn-solo** [comment]
BLOCK #22644792
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL

Берем карту (поворот) и добавленную в описание задачи #29 

Смотрим 15 дек 2017 или утром в субботу, 16го

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @jackal1527 
давайте завтра обсудим, возможно на выходных смогу еще что-то сделать. 
![default](https://user-images.githubusercontent.com/33925750/34047041-d1e6da1c-e1d0-11e7-8991-706b9cc5aea1.jpg)
![default](https://user-images.githubusercontent.com/33925750/34047043-d2244f96-e1d0-11e7-8700-bdca7af72152.jpg)
![_](https://user-images.githubusercontent.com/33925750/34047045-d31b74c4-e1d0-11e7-901c-417b38262e1f.jpg)

**Comment by alecvert** [comment]
@RomaRAD у меня вопросов нет. Единственное может добавить преимущества заголовок, где иконки преимуществ.

Пиджак у институционала может лучше сделать серым , зеленый как-то не то

Думаю, что надо запариться и все таки сделать на отдельном языки иконки как service, freight и т д

**Comment by cptn-solo** [comment]
@RomaRAD агонь вообще! 
Чего увидел:
- у трилистника площадку по-тоньше забыл сделать по-моему
- институционалу влепите голубой пиджак, не перегибайте с фобиями своими, нормально будет все.
- иконки на карте - предлагаю подставки сделать с сеткой
- "базовый токен сети" имхо лишнее. Пусть помучаются и подумают чего это за монета новая. тизер же ж
- по цифровой и физической точке - на самом деле картинка на столько классная, что тексты рядом с ней выглядят вообще нелепо. Надо что-то придумывать 

Вообще - @alecvert - иконки преимуществ это не актуальная версия, т.е. по ней вопросов пока не надо думаю задавать. но, кстати, если влепить актуальную версию со смещенным влево сервером - было бы интересно глянуть.

**Comment by RomaRAD** [comment]
@alecvert иконки преимуществ - вроде обсуждали что будет всплывающее поля при наведении с подписью иконки, так их проще переводить на Рус и Engl. Или ушли от этой идеи?

@kkrupovich  верное замечание по трилистнику
![screenshot_31](https://user-images.githubusercontent.com/33925750/34068606-edb672d6-e25f-11e7-9ed9-849a4060525e.jpg)
фобию тоже преодалел
![screenshot_32](https://user-images.githubusercontent.com/33925750/34068607-edee5d40-e25f-11e7-82ad-01d578f8c9e3.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD @alecvert предлагаю исходники фиксировать, итерацию закрывать и переходить на шапку сайта - что вы, похоже, уже и сделали.

**Comment by RomaRAD** [comment]
В файле карта и другие изображения, кроме шапки сайта.
https://github.com/u-transnet/www-teaser/commit/32ddc944c679693f489fe289dd427848778818f9

**Comment by cptn-solo** [comment]
BLOCK #22751816
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 60.00000 UTDEV

Спасибо!

**Comment by cptn-solo** [comment]
для блога
<img width="184" alt="screen shot 2017-12-29 at 01 03 09" src="https://user-images.githubusercontent.com/1105555/34424492-185dde96-ec35-11e7-999c-2d33d82fd6c7.png">

[тут](https://golos.io/transnetspace/@cptn-solo/kak-rozhdayutsya-blokcheiny-vnezapno)
