### ISSUE TITLE
Итерация №2 Отрисовка иллюстрации по оцифровке точки системы

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#60]
Исходная задача #23 

Исходники в [prototyping/digital-point](https://github.com/u-transnet/www-teaser/tree/prototyping/digital-point)

От @alecvert :
- я думаю оцифровку на сайте покрупнее надо, а то теряется
- с кустом теряется ощущение , что струны находятся высоко. С деревом было лучше

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #23039341
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 140.00000 UTDEV.SKILL

> До вечера 28 декабря 2017

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
Я правильно понял задачу, что нужно актуализировать по цветам и подчеркнуть размер?
![default](https://user-images.githubusercontent.com/33925750/34407170-c2294b9c-ebde-11e7-88dc-5cbd02bd5ad2.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD цвета в нижнем варианте может даже в перебор - как бы карта потом не потерялась. Не плохо, просто нужно будет в целом по сайту тоже красок бахнуть тогда.
По поводу размера - есть две части проблемы:
- высота путевой структуры над землей 
- размер всего изображения на сайте.

**Comment by alecvert** [comment]
@RomaRAD я за второй вариант ниже, нужно смотреть на макете

@jackal1527 глянь что лучше пжлст

1. На опоре не полностью верх должен быть оранжевым, а нарисовать сенсор лучше оранжевым.
@kkrupovich как он будет выглядеть?

2. Высота нелогично, либо деревья выше либо юрибайк меньше размером, иначе юнибайк получается как грузовик большой)

**Comment by cptn-solo** [comment]
@alecvert
> На опоре не полностью верх должен быть оранжевым, а нарисовать сенсор лучше оранжевым.

 проснулся :) у нас на стартовом экране такие опоры. давайте там тоже тогда переделаем.

>Высота нелогично, либо деревья выше либо юрибайк меньше размером, иначе юнибайк получается как грузовик большой)

тоже бросилось в глаза - байк либо надо делать меньше (приближать к реальным пропорциям), либо наоборот - увеличить, чтобы акцентировать на схематичности подачи.

**Comment by RomaRAD** [comment]
Сделал пример с размещением.
- Верхняя часть опоры не вся оранжевая, только часть.
- Если бот сделать пропорционально меньше. Думаю тут уместно такое преувеличение.
- Согласен, что на сайте можно сделать иллюстрацию крупнее, я ее увеличил, немного вытянул.
@kkrupovich @alecvert @jackal1527 

![default](https://user-images.githubusercontent.com/33925750/34414007-a209b5f2-ec08-11e7-8a3e-90e0a7ba2746.jpg)

**Comment by nat-brit** [comment]
А почему цифровой байк имеет другую форму, болле округлую? Оранжевая надпись очень яркая, мы хотим в этом рисунке сделать акцент на TRANSNET SPACE? Неплохо, если мы хотим на этом сделать акцент, но картинка не отражает весь концепт, здесь речь лишь об оцифровке путевой структуры.

**Comment by RomaRAD** [comment]
@nat-brit  
- он так выглядит с этого раскурка
- это на общее усмотрение

**Comment by alecvert** [comment]
@RomaRAD сделай пжлст байк более векторным, оцифрованным.

Еще над байком , путевой структурой я бы сделал названия учеток . Как считаешь @kkrupovich @nat-brit ?

По надписям. Лучше на зеленой часьи TRANSNET светлым, а SPACE синим, и все это без выделения оранжевым. Лучше на юнибайке сделать оранжевую вставку как на 1 экране.

**Comment by cptn-solo** [comment]
@alecvert 
> Еще над байком , путевой структурой я бы сделал названия учеток . 

Слушайте, идея норм, если это можно аккуратно показать - я не против

> Лучше на юнибайке сделать оранжевую вставку как на 1 экране

тоже за. 

ПО надписи - соглашусь, что, наверное, это слишком, лучше как-то смягчить акцент

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit 
Залил отдельно картинку сюда
 ![image](https://user-images.githubusercontent.com/33925750/34454807-d320974a-ed94-11e7-9773-f7f8eb3d746b.png)

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @jackal1527 если вопросов нет - предлагаю закрывать, исходники заливать.
Просто без увеличения оценки трудозатрат я бы с этой задачей больше не возился.

**Comment by nat-brit** [comment]
Вопросов нет. Закрываем.

**Comment by cptn-solo** [comment]
@RomaRAD исходники!

BLOCK #23108334
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 140.00000 UTDEV

Закрываем
