### ISSUE TITLE
Сформулировать заголовки и краткие тексты на первые блоки сайта transnet.tech

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#61]
Нулевая итерация, чтобы определить уровень понимания процесса работы и взаимодействия в команде. 
Результат (тексты для первых 3-4 блоков сайта) оформляем в [**документ**](https://docs.google.com/document/d/1n6wiNzSI3t-awgT84UKOWwni-tEUhGYsCshhYzfasbc/edit?usp=sharing) гугл или в графический файл - "стикеры" на изображение макета из #56 

Была когда-то задача, подобная этой ( #9 ), но она слишком общая. И, вероятно, вообще ее надо будет удалить. Но там есть любопытная идея - нумерованные блоки-скриншоты. Можно попробовать повторить что-то подобное.

**Comment by cptn-solo** [comment]
BLOCK #22762834
TRANSFER |  
From | n-yalinski
To | utd-content
Quantity | 59.00000 UTDEV.SKILL

Смотрим в среду, 20 дек. 2017 (созвон создал на 14:00 мск)
Работаем ;)

**Comment by NYalinski** [comment]
Весь вторник был в дороге, да еще и клавиатура на ноутбуке не работает из-за того, что пролил воду и отошли контакты
Вот ссылка на гугл док

https://docs.google.com/document/d/1n6wiNzSI3t-awgT84UKOWwni-tEUhGYsCshhYzfasbc/edit?usp=sharing

**Comment by cptn-solo** [comment]
@alecvert @NYalinski откомментил, формат +- норм, т.к. удобно обмениваться комментариями и править документ совместно. Надо решить, куда двигаться дальше - вниз по сайту? Если да, то ссылка на +- полный макет доступна тут: #56 , предлагаю расширять гуглодок вставляя туда скриншоты на фрагменты с заготовками текстов, как я делал это в #9

**Comment by NYalinski** [comment]
Думаю да, стоит закончить скелет сайта, а потом можно начинать расширать и углублять разные отделы/всплывающие окна

**Comment by cptn-solo** [comment]
- Оплата промежуточного результата
BLOCK #22817990
TRANSFER |  
From | utd-content
To | n-yalinski
Quantity | 59.00000 UTDEV

- Продолжаем:
BLOCK #22817038
TRANSFER |  
From | n-yalinski
To | utd-content
Quantity | 59.00000 UTDEV.SKILL
> смотрим 21 декабря 2018.

**Comment by NYalinski** [comment]
[Гугл документ](https://docs.google.com/document/d/1H7mjMG7z4MpVgHx--YTAZ3DL5wa-3oOmOj0CfwJ1LG8/edit) сайта, разделённого на блоки.

**Comment by NYalinski** [comment]
Разделил [документ](https://docs.google.com/document/d/1n6wiNzSI3t-awgT84UKOWwni-tEUhGYsCshhYzfasbc/edit) по блокам. Таблицы созданы для перевода (слева русский, справа английский).

**Comment by alecvert** [comment]
@NYalinski меня устраивает, более подробные правки, если обнаружу , внесу позже.

Далее пойдем также по разделам вниз.

**Comment by cptn-solo** [comment]
см. иконки преимуществ #36 - от них надо думать тексты для каждого преимущества

**Comment by cptn-solo** [comment]
По проделанной работе:
BLOCK #22844009
TRANSFER |  
From | utd-content
To | n-yalinski
Quantity | 59.00000 UTDEV
Спасибо!

@NYalinski добавь пожалуйста еще день скила на текущую итерацию, созвон завтра в 15 поставил.

**Comment by cptn-solo** [comment]
@NYalinski 
BLOCK #22872574
TRANSFER |  
From | utd-content
To | n-yalinski
Quantity | 59.00000 UTDEV

Продолжаем:

- преимущества - всем иконкам сочинить тексты;
- актуализировать перевод;
- свободный поиск по документу;
- глоссарий;

@NYalinski Просьба добавить скилл на 2 дня, смотрим вечером 25 декабря 2017

**Comment by cptn-solo** [comment]
@NYalinski 
BLOCK #22873520
TRANSFER |  
From | n-yalinski
To | utd-content
Quantity | 118.00000 UTDEV.SKILL
> Смотрим 25 декабря 2017

**Comment by NYalinski** [comment]
[Иконки](https://docs.google.com/document/d/1o_W2LbFLJQyLpq7JobgPLtHUHXqp31NiecxWCixSESQ/edit?usp=sharing). По поводу трёх (9, 10 и 11) есть вопросы.

[Переводы в основном документе](https://docs.google.com/document/d/1n6wiNzSI3t-awgT84UKOWwni-tEUhGYsCshhYzfasbc/edit?usp=sharing), чтобы лишний раз не листать вверх.

[Глоссарий](https://github.com/u-transnet/info/wiki/%D0%93%D0%BB%D0%BE%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%B9) и [гугл документ](https://docs.google.com/document/d/11HhqX4pTWsmG2ysHOF1qBJIo8jTpPH-EIQTYzx33X5c/edit?usp=sharing) для правки текстов.

**Comment by cptn-solo** [comment]
@NYalinski 
- просьба перенести все-таки статьи из гуглодока в глоссарий и пометить сомнения италиком.
- продолжаем иконки
- продолжаем общий документ с текстами. Просьба добавить скилл еще на день, смотрим завтра 26 декабря 2017

**Comment by cptn-solo** [comment]
@NYalinski 
BLOCK #22962975
TRANSFER |  
From | utd-content
To | n-yalinski
Quantity | 118.00000 UTDEV

Спасибо, продолжаем:

BLOCK #22961352
TRANSFER |  
From | n-yalinski
To | utd-content
Quantity | 59.00000 UTDEV.SKILL

> ПРОДОЛЖАЕМ, смотрим 26 декабря 2017

**Comment by nat-brit** [comment]
[Тексты для сайт - логика, наброски](https://docs.google.com/document/d/1hAgcv3REB7H0T6E_Nx1eDO718lG49JmUla21ClTXtdY/edit?usp=sharing)
