### ISSUE TITLE
Дизайн контентной страницы сайта. (сборный файл)

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#62]
Создать сборный файл на примере контентной страницы.
Учесть максимальное количество элементов на странице. В том числе и поведения всех элементов.

**Comment by jackal1527** [comment]
![transnet_](https://user-images.githubusercontent.com/32764532/34160606-69c39c32-e4ef-11e7-8943-57c636043c32.jpg)

**Comment by cptn-solo** [comment]
BLOCK #22788430
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
19 декабря 2017

**Comment by cptn-solo** [comment]
Нужны исходники, и закрываем.

**Comment by cptn-solo** [comment]
Добавляем скилл на подготовку исходников.

BLOCK #22788791
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 50.00000 UTDEV.SKILL

Складываем исходники в [prototyping/content-template](https://github.com/u-transnet/www-teaser/tree/prototyping/content-template)

**Comment by jackal1527** [comment]
Исходники тут
https://github.com/u-transnet/www-teaser/tree/prototyping/Inside_pages/content_page

**Comment by cptn-solo** [comment]
BLOCK #22838875
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 150.00000 UTDEV
