### ISSUE TITLE
Дизайн страницы с дорожной картой проекта

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#63]
Создание Дизайна страницы дорожной карты проекта.
Пересекается с [задачей](https://github.com/u-transnet/www-teaser/issues/48)

Референсы:
от Владимира
![2345](https://user-images.githubusercontent.com/32764532/34152046-0adf5f82-e4cf-11e7-8372-0264afca6a9e.jpg)
от Алексея
![photo_2017-12-05_20-12-00](https://user-images.githubusercontent.com/32764532/34152059-1aa26900-e4cf-11e7-877f-afd726cc8011.jpg)
![photo_2017-12-05_20-29-02](https://user-images.githubusercontent.com/32764532/34152060-1ac46000-e4cf-11e7-822b-28e58cff1b11.jpg)

Придумать хорошую концепцию

**Comment by jackal1527** [comment]
![transnet_](https://user-images.githubusercontent.com/32764532/34160595-55c4c56c-e4ef-11e7-8b1d-58ced47846d7.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 
Вариант развиваем:
- добавляем макет мобильной версии

**Comment by cptn-solo** [comment]
Графика для шапки пилится в #66

**Comment by cptn-solo** [comment]
BLOCK #22788140
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
Уходим в #67 и #66 

BLOCK #22789082
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 100.00000 UTDEV

Спасибо!
