### ISSUE TITLE
Цвета для сайта - попробовать альтернативные цветовые схемы

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#65]
@nat-brit предложила несколько вариантов - надо сюда прикрепить картинки с предложениями и @jackal1527 попробовать перекрасить макет.

**Comment by cptn-solo** [comment]
BLOCK #22788914

TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 150.00000 UTDEV.SKILL

смотрим четверг вечер 21 декабря 2017

**Comment by nat-brit** [comment]
Вариант первый - по существующим цветам макета: различные оттенки зеленого и красный.
![000](https://user-images.githubusercontent.com/30142436/34199570-e33a750e-e576-11e7-9486-87d6eb840153.jpg)
![000-1](https://user-images.githubusercontent.com/30142436/34199572-e37a193e-e576-11e7-9cf4-4c2eca3aae8b.jpg)
![000-2](https://user-images.githubusercontent.com/30142436/34199573-e3bf6868-e576-11e7-8714-eadc7b3f6dc9.jpg)
![000-green](https://user-images.githubusercontent.com/30142436/34199575-e3f48b06-e576-11e7-93d6-edc72b0a91ab.jpg)

**Comment by nat-brit** [comment]
Вариант второй
![var1-0](https://user-images.githubusercontent.com/30142436/34199675-3a2566d0-e577-11e7-8275-d57047b92e6a.jpg)
![var1-1](https://user-images.githubusercontent.com/30142436/34199676-3a62162a-e577-11e7-8d6d-96e74c9ff932.jpg)
![var1-3](https://user-images.githubusercontent.com/30142436/34199677-3aa0f836-e577-11e7-9517-97a3e57a374e.jpg)

**Comment by nat-brit** [comment]
Вариант третий: красный либо один, либо второй (оба не использовать). Все остальное комбинируется.
![var2](https://user-images.githubusercontent.com/30142436/34199842-baedda4a-e577-11e7-806c-1899e9046a44.jpg)
![var2-1](https://user-images.githubusercontent.com/30142436/34199843-bb2dada0-e577-11e7-9f4b-28795bd8fe84.jpg)
![var2-2](https://user-images.githubusercontent.com/30142436/34199844-bb67d58e-e577-11e7-8fdd-470880014290.jpg)
![var2-3](https://user-images.githubusercontent.com/30142436/34199845-bba8b752-e577-11e7-9bb8-aee180f26a7d.jpg)

**Comment by nat-brit** [comment]
Вариант четвертый: 
![var4-1](https://user-images.githubusercontent.com/30142436/34199964-14a5fa90-e578-11e7-9515-a66f5214b103.jpg)
![var4-2](https://user-images.githubusercontent.com/30142436/34199965-14e4f66e-e578-11e7-9c3f-6fd452394188.jpg)
![var4-3](https://user-images.githubusercontent.com/30142436/34199966-15227232-e578-11e7-8465-70ca3e1acb4c.jpg)

**Comment by nat-brit** [comment]
Вариант 5, основа в зеленом, из красных брать либо оранжевый, либо лиловый (оба не использовать):
![5-0](https://user-images.githubusercontent.com/30142436/34200192-dbafa6cc-e578-11e7-8398-e44350a788fa.jpg)
![5-2](https://user-images.githubusercontent.com/30142436/34200194-dbf59236-e578-11e7-8bee-f4846b2f34c9.jpg)
![5-3](https://user-images.githubusercontent.com/30142436/34200195-dc2bbece-e578-11e7-8a5c-a28276137e1a.jpg)
![51](https://user-images.githubusercontent.com/30142436/34200197-dca88bde-e578-11e7-86c5-5f6e4a98896f.jpg)
![var5-4](https://user-images.githubusercontent.com/30142436/34200198-dd17067c-e578-11e7-889a-18e8cd019660.jpg)

**Comment by nat-brit** [comment]
Вариант шестой (отталкиваясь от "дорожной карты": лиловый можно ярче, в зависимости от назначения (для букв взять более насыщенный цвет, для заливки этот)
![6-0](https://user-images.githubusercontent.com/30142436/34200286-27ccffbe-e579-11e7-8607-17dcb6e8da8e.jpg)
![6-1](https://user-images.githubusercontent.com/30142436/34200287-280c3fda-e579-11e7-9fb9-9d64ccfe8695.jpg)
![6-2](https://user-images.githubusercontent.com/30142436/34200288-284a014e-e579-11e7-8841-1f53f43e3f5b.jpg)

**Comment by jackal1527** [comment]
1
![01](https://user-images.githubusercontent.com/32764532/34261489-1700d79c-e68b-11e7-9063-3ff25b0743a1.jpg)
2
![02](https://user-images.githubusercontent.com/32764532/34261490-1724e8c6-e68b-11e7-98c0-5dfab442380c.jpg)
3
![03](https://user-images.githubusercontent.com/32764532/34261491-174751fe-e68b-11e7-9222-5a53604545fe.jpg)
4
![04](https://user-images.githubusercontent.com/32764532/34261492-176e5e7a-e68b-11e7-9c96-93a2a6328f7b.jpg)

**Comment by cptn-solo** [comment]
1 за основу 
- болотный на зеленый из 4го.
- бирюзовый меняем на оранж или красный из 3, подходящий под мятный и сиреневый.
- ярко-зеленый оставляем

**Comment by cptn-solo** [comment]
BLOCK #22846426
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 150.00000 UTDEV

Спасибо, продолжаем в #69

**Comment by jackal1527** [comment]
1
![01](https://user-images.githubusercontent.com/32764532/34299114-05debf70-e743-11e7-86aa-ca0139a9b1c9.jpg)
2
![05](https://user-images.githubusercontent.com/32764532/34299120-0c26762a-e743-11e7-80d9-54bd079db893.jpg)
