### ISSUE TITLE
Дорожная карта - графика для шапки дорожной карты

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#66]
@alecvert собирает референсы, потом выбираем и согласовываем задачу для @RomaRAD 
Эта задача для #67  

Исходники в [prototyping/roadmap](https://github.com/u-transnet/www-teaser/tree/prototyping/roadmap)

**Comment by cptn-solo** [comment]
![img_19122017_200532_0](https://user-images.githubusercontent.com/1105555/34163305-6ed72bba-e4e7-11e7-8fe7-4735a6f872e5.png)

<img width="195" alt="screen shot 2017-12-19 at 18 08 58" src="https://user-images.githubusercontent.com/1105555/34163455-d542fb9a-e4e7-11e7-9fe2-5805163cef28.png">

Колонну делаем чертежом, потом байк, потом - цифра

**Comment by cptn-solo** [comment]
@RomaRAD можно брать после шапки. Пока не берем

**Comment by cptn-solo** [comment]
@alecvert просьба поделиться исходником фотки байка в хорошем качестве

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #22980213
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 140.00000 UTDEV.SKILL
> смотрим вечером 27 декабря 2017

**Comment by RomaRAD** [comment]
![_](https://user-images.githubusercontent.com/33925750/34383651-71eb17a6-eb38-11e7-8088-2559c3019528.jpg)
еще работаю над проработкой бота, по поводу фона у кого какие мысли?
@alecvert @kkrupovich @jackal1527 @nat-brit

**Comment by cptn-solo** [comment]
Я вообще не имею вопросов. @RomaRAD просто супер.

**Comment by nat-brit** [comment]
Мне тоже очень нравится. Но мы вообще ушли от фото. Даже не фоне не оставим ничего? Может быть добавить прозрачности? Или полностью от фото отказываемся?

**Comment by cptn-solo** [comment]
Имхо фото было бы уместно если бы на стартовом экране осталось что-то с фото, а сейчас не факт. Но решайте

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich @nat-brit мне все нравится, прям Рома как будто мысли читать учится потихоньку

Единственное доя полноты цветовой гаммы и наомоничности я бы сделал снег , а не траву. С точки зрения гуманитарной можно воепить где то вдали в реальной части снеговика😉

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit 

![default](https://user-images.githubusercontent.com/33925750/34402845-47626154-ebc6-11e7-8461-1f8503b6460e.jpg)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit
![_](https://user-images.githubusercontent.com/33925750/34403101-ea07b336-ebc7-11e7-9e2c-789c576db164.jpg)

**Comment by nat-brit** [comment]
Красиво. Снеговичок прикольный, может его вправо перенести, а то центр загружен, а справа пустота

**Comment by RomaRAD** [comment]
@kkrupovich  Исходник по ссылке
https://github.com/u-transnet/www-teaser/tree/prototyping/roadmap

**Comment by cptn-solo** [comment]
> Красиво. Снеговичок прикольный, может его вправо перенести, а то центр загружен, а справа пустота

@nat-brit тогда он оцифруется :) в любом случае - если на след. итерацию только, не отвлекаемся пока.

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #23039181
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 140.00000 UTDEV

Спасибо!

**Comment by RomaRAD** [comment]
@nat-brit я руководствуюсь той логикой, что реальный мир у нас посередине. Чертеж снеговика или или цифровой его вид будет сбивать с толку, зачем? Поэтому оставил его посередине.
