### ISSUE TITLE
Итерация №1 Дизайн страницы с дорожной картой проекта

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#67]
Пришли из #63 

Параллельно с #66 развиваем макет:

Вариант развиваем:
- добавляем макет мобильной версии
- объекты на карте разные

Исходники в [prototyping/roadmap](https://github.com/u-transnet/www-teaser/tree/prototyping/roadmap)

BLOCK #23472291
From | utd-romarad
To | utd-design
Quantity | 140.00000 UTDEV.SKILL
2 дня. Смотрим 15 января

**Comment by cptn-solo** [comment]
@alecvert просьба тут высказываться

**Comment by alecvert** [comment]
@RomaRAD по самому виду дорожной карты и концепции, это то, что предлагал @jackal1527 
![image](https://user-images.githubusercontent.com/30151576/34707480-91761a3e-f52f-11e7-8411-f0aea7c0f425.png)
 ,
опишу более детализированно как прорисовать, чтобы не было повторений и однообразия. 

1. Станция, которую ты отрисовал с ветряком и солнечной батареей
2-3. однопутная путевая структура, как на первом экране, соответственно 2-первая промежуточная опора , 3- вторая. + юнибайк
3. Поворотный участок в виде подковы см. 
![image](https://user-images.githubusercontent.com/30151576/34707890-def35388-f531-11e7-9953-66ca98818d9c.png) 
![image](https://user-images.githubusercontent.com/30151576/34707910-fad44d14-f531-11e7-81fe-fbaa691632dd.png)
4. Далее уходим вверх на провисающую путевую структуру 
![image](https://user-images.githubusercontent.com/30151576/34707944-28a99f78-f532-11e7-89ae-d83b6b59ad4b.png) , 
![image](https://user-images.githubusercontent.com/30151576/34707962-43a40a66-f532-11e7-960c-0d618e53955a.png) , или см. видео https://www.youtube.com/watch?v=b73qOymqXkk (1.24 -1.36 ), по ней перемещается как на этом видео городской пассажирский общественный юнибус как на видео, более близко см. https://www.youtube.com/watch?v=b73qOymqXkk (1.43-2.18).
5. Одна , две промежуточных высотных опоры провисающей путевой структуры.
6. Путевая структура поднимается и входит станцию сервер высотную (отрисовывали, см. карту на сайте ) по аналогии как здесь https://www.youtube.com/watch?v=b73qOymqXkk (3.17-3.30)
7. Отдельно стоящая подобная станция https://www.youtube.com/watch?v=b73qOymqXkk (1.35 - 1.42) 
8. От неё отходит такая же ферма как на видео или см. https://www.youtube.com/watch?v=b73qOymqXkk (1.30-1.34) , https://www.youtube.com/watch?v=b73qOymqXkk (2.53 -2.57).
9. Подвижной состав такой https://www.youtube.com/watch?v=JlySgpaPQ3s (см. 1.55 - 1.59 ), https://www.youtube.com/watch?v=JlySgpaPQ3s (2.22 - 2.25 )
10. Приходит в такую же станцию.

**Comment by cptn-solo** [comment]
@RomaRAD я так понимаю надо эту задачу делать после [логотипа](https://github.com/u-transnet/www-teaser/issues/84)

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
я правильно понял последовательность и объекты?
![default](https://user-images.githubusercontent.com/33925750/34870182-2d1f8f56-f7ab-11e7-89c8-18d7ccba4b2e.jpg)

**Comment by alecvert** [comment]
@RomaRAD 

![image](https://user-images.githubusercontent.com/30151576/34870718-bc1d7050-f7ac-11e7-9c2c-fc74b032f4a3.png)

Да, выходит путевая структура.

![image](https://user-images.githubusercontent.com/30151576/34870809-091bc9c4-f7ad-11e7-93b7-ba43713c4064.png)

 И в зависимости от пунктов дорожной карты, мы что-то на промежуточной опоре разместить можем. Либо вставить вторую такую же станцию.

![image](https://user-images.githubusercontent.com/30151576/34870921-7a34b9fe-f7ad-11e7-8312-6c43540e9e17.png)

Давай сделаем, что выходит высокоскоростная ферма прям из той же станции, а то нагромождение и нелогично будет, то есть уйдёт от решения стоящих рядом двух станций
![image](https://user-images.githubusercontent.com/30151576/34871305-ff30273c-f7ae-11e7-8506-a44adbac2e53.png)

![image](https://user-images.githubusercontent.com/30151576/34870989-aee2c7d6-f7ad-11e7-8219-ed4163aa79e4.png)

Приходит в малоэтажную станция, см. пример. или вот например такого вида 

![image](https://user-images.githubusercontent.com/30151576/34871455-8903c72a-f7af-11e7-8d8e-233ff71ebb11.png)


По фону: давай пока без фона, посмотрим далее.

**Comment by RomaRAD** [comment]
@alecvert  @kkrupovich Я бы заложил 2 дня, с учетом вноса не критичных правок в ПН в течении дня.
Скилую?

**Comment by alecvert** [comment]
@RomaRAD да, Ром, скиллуй

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit 
![rail_](https://user-images.githubusercontent.com/33925750/34928630-c3f57c24-f9e0-11e7-8b32-c1ba329e75c5.jpg)

![image](https://user-images.githubusercontent.com/33925750/34930088-888c3930-f9e9-11e7-8587-a29fb5b52582.png)

![rail_back](https://user-images.githubusercontent.com/33925750/34928631-c42d2958-f9e0-11e7-82f8-f8b721708bdc.jpg)

**Comment by alecvert** [comment]
@RomaRAD по дизайну и стилистике всё круто

![image](https://user-images.githubusercontent.com/30151576/34931598-6a2322f8-f9f1-11e7-91e8-50fe8286cd57.png)

1. На станции крыша должна быть зелёная, либо там тоже кустики должны быть.

2. Можно поставить юнибайк ещё.

3. Опору нужно по выше, чтоб типа этого было 
![image](https://user-images.githubusercontent.com/30151576/34931681-bf15df9e-f9f1-11e7-9f4f-d6c2142cec39.png)
не с таким резким углом , как я нарисовал, но чтоб видно было. И по путвевой структуре тоже за юнибусом едет юнибайк как в 2

4. Нужны промежуточные опоры на скоростной , так как пролёт большой. Посмотри пжлст так какие на видео.

![image](https://user-images.githubusercontent.com/30151576/34931707-e04a57d0-f9f1-11e7-9b83-2b900eb314e2.png)

5. Саму скоростную трассу нужно опустить пониже, последнюю станцию сделай пжлст поменьше размерами, опустив скоростную пониже, а то она огромная

6. От Высотных станций ещё должен отходить по верху юнибус как здесь https://www.youtube.com/watch?v=jYAh-HdBFqg с 3.17- 3:48 , иначе нелогично, см. пример 
![image](https://user-images.githubusercontent.com/30151576/34931982-fa980e24-f9f2-11e7-92b3-27ddd26fcb1d.png)

У второй высотной трассы уходит за экран куда то провисающая.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
![rail 222](https://user-images.githubusercontent.com/33925750/34951242-74fac7f8-fa37-11e7-8449-4d809b40a2f6.jpg)

**Comment by RomaRAD** [comment]
![rail 3](https://user-images.githubusercontent.com/33925750/34951589-9ce61db6-fa38-11e7-8704-76285034963a.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD откатываемся к [первому варианту](https://github.com/u-transnet/www-teaser/issues/63#issuecomment-352761074)

Просьба залить исходники, в шапке есть путь - для игрового направления наработки по этой задаче очень хорошо подходят

BLOCK #23561795
TRANSFER |  From | utd-design
To | utd-romarad
Quantity | 140.00000 UTDEV

Спасибо!

Пока тормозим эту задачу

**Comment by RomaRAD** [comment]
Исходник по ссылке @kkrupovich @alecvert 
https://github.com/u-transnet/www-teaser/commit/8f8fc300d217f6602962ba2e6d73f6b786acf64b
