### ISSUE TITLE
Итерация №1 Шапка сайта - планшет - проработка концепции и отрисовка

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#68]
Пришли из #13 

Доработки и мнения пишем в комментариях и пробуем зайти на следующий круг

**Comment by cptn-solo** [comment]
BLOCK #22818308
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL
> созвон 12:00спб 21 декабря 2017

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich @jackal1527 @nat-brit предлагаю первый экран сделать в логике этого

![image](https://user-images.githubusercontent.com/30151576/34219329-a2663912-e5d2-11e7-9d74-cb5f25cabcca.png)

Сетка у нас присутствует, концепцию , дизайн сайта не нарушает, размер первого экрана соблюдается и показывает сразу, что мы оцифровываем и направлены на реальное применение. Карта и иконки у нас тоже на такой же сетке.

Давайте обсудим и представим на главной экосистему Transnet Space, то есть опоры-подвижные составы на струнах-станции, люди, заводы, банки, энергетика, мобильная связь, интернет вещей, и всё это связывается с друг другом ( можно визуально сделать перемещение Utt), можно потом на корпоративной версии заморочиться сделать анимацию.

Смысл: мы показываем, что Transnet Space действительно блокчейн цифровое пространство, объединяющее многое.

В целом экран такой и будет , только без планшета и с сеткой в изометрии , деталями Transnet Space 

![image](https://user-images.githubusercontent.com/30151576/34219569-6af06164-e5d3-11e7-9e24-50d0c190d52f.png)


Пока давайте подумаем хороша ли эта идея?

**Comment by cptn-solo** [comment]
@alecvert 
> Смысл: мы показываем, что Transnet Space действительно блокчейн цифровое пространство, объединяющее многое.

Ни слова больше. Делаем. 
Готов отказаться от "полей". Но я так понимаю, от "джойстика" сверху мы так же отказываемся в таком случае?

**Comment by RomaRAD** [comment]
Эскизы по прошлым обсуждениям
@alecvert @kkrupovich @jackal1527 
![_ 1](https://user-images.githubusercontent.com/33925750/34245832-a5332bc0-e64d-11e7-9e60-69b06dc5f790.jpg)
![_ 2](https://user-images.githubusercontent.com/33925750/34245833-a568bb14-e64d-11e7-8ed0-98bc9df8d2d9.jpg)
![_ 3](https://user-images.githubusercontent.com/33925750/34245834-a59bc950-e64d-11e7-9f61-3bb5fcd7b14c.jpg)
![_ 4](https://user-images.githubusercontent.com/33925750/34245835-a5cfc610-e64d-11e7-8327-1706981804db.jpg)

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich все таки придется сделатб слайдер похоже)

**Comment by cptn-solo** [comment]
За основу берем 2й вариант
- нужно сместить акцент с транснет на окружение, на спейс вокруг него
- показать симбиоз реальной и цифровой системы. Совместить первый и второй экран, оцифровать элементы.
- станция / банк (доллар + ют) / завод / грузовик / люди / мир интернет вещей
- Размер объектов больше - [примерно](https://www.streamr.com)
- Сервер - это не сервер, сервера спрятаны по всей сети. Т.е. если он будет на слайде, через него должна проходить путевая структура. В масштабе он должен быть гораздо больше зданий. Поэтому на слайде его не нужно.
- По элементам делаем завод, добавляем машинки, людей, вышки, строительство, солнечные панели
- Небоскреб строящийся на сваях как сервер?
- пытаемся показать консенсус каким-то образом.
- - У каждого объекта рисовать бар (бары)?

**Comment by cptn-solo** [comment]
К вопросу о dPoS: от @jackal1527 
![photo_2017-12-21_12-18-21](https://user-images.githubusercontent.com/1105555/34249031-3be112b2-e649-11e7-8b5a-dfbac86b6f39.jpg)

**Comment by cptn-solo** [comment]
Доп. скилл:
BLOCK #22839286
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 60.00000 UTDEV.SKILL
Смотрим вечером 21 дек 2017

**Comment by RomaRAD** [comment]
Эта задача конечно не на один день. Тут еще деталей добавлять и добавлять, но давайте посмотри основу, правильно ли бы друг друга поняли @kkrupovich @alecvert @jackal1527 

![_5](https://user-images.githubusercontent.com/33925750/34268102-44886ea8-e6a1-11e7-9dac-89a7ebbc8432.jpg)

**Comment by cptn-solo** [comment]
@alecvert @RomaRAD @nat-brit @jackal1527 
Вообще, ИМХО, выглядит довольно мило. Удивительно. Мне даже кажется, что не стОит разрывать кольцо - пускай это будет символом объединения, не пытаться вкладывать в это какой-то глубокий практический смысл. 

И юнибайки я не оч. понял зачем сверху? выбрать чтобы? Или это "оцифровка" - но тогда порядок должен быть другой - "проволочный" (цифровой, первый слева на рисунке) должен идти последним.

**Comment by alecvert** [comment]
@RomaRAD @nat-brit @kkrupovich @jackal1527 

1. Юнибайки вверху нужно убрать , зачем они?

2. Бары вместо этого http://prntscr.com/hqvks5 предлагаю в таком виде 

![image](https://user-images.githubusercontent.com/30151576/34289731-b4440b5c-e715-11e7-9e5b-2bbd1713e9cb.png)
, только вместо иконок может быть либо цифра либо другим видом баланс ( в виде ленты например). Сейчас бары смотрятся как флаги или солнечные батареи.

3. 
![image](https://user-images.githubusercontent.com/30151576/34289861-4fef3fb8-e716-11e7-8a0b-dbb11c186724.png) все опоры по юнибайкам сделай пжлст как исправил

4. 
![image](https://user-images.githubusercontent.com/30151576/34289886-682aeb22-e716-11e7-8f65-d150eb2b31d4.png) станцию лучше отрисовать конечно как на видео

5. Юнибайк должен быть меньше, иначе нет логики со зданиями, но с другой стороны он тогда теряется. 
![image](https://user-images.githubusercontent.com/30151576/34289982-e5a802f6-e716-11e7-81b8-d026e4dc82c2.png) Тогда , кстати имеет смысл сверху поставить.

6. Предлагаю не ставить никакие флаги DPOS , типа вертолётной площадки и надпись DPOS  , вертолётик можно поставить с логичным размером юнибайка либо взлетевший уже.

![image](https://user-images.githubusercontent.com/30151576/34290161-c364a75c-e717-11e7-9a71-55e7bc30126d.png)

Вот исправил без байков

![image](https://user-images.githubusercontent.com/30151576/34290859-5bce1d9a-e71b-11e7-93ae-9a9db3b9458f.png)

**Comment by cptn-solo** [comment]
- "объект" в центр вместо флага (отсылка к EOS)
- на объекте надпись DPoS
- линии поверхности от бъекта к зданиям
- знак U отделить от остальных цветом, под цвет #69 
- голосовалки убираем, флаги убираем, заменяем на капли с галочками и крестиками
- в верхней части истории сохранить баланс, возможно - добавить сельское хозяйство

**Comment by cptn-solo** [comment]
BLOCK #22866677
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 120.00000 UTDEV
Спасибо!
Уходим на #71
