### ISSUE TITLE
Итерация №2 Шапка сайта - планшет - проработка концепции и отрисовка

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#71]
Пришли из #68 

- "объект" в центр вместо флага (отсылка к EOS)
- на объекте надпись DPoS
- линии поверхности от бъекта к зданиям
- знак U отделить от остальных цветом, под цвет #69 
- голосовалки убираем, флаги убираем, заменяем на капли с галочками и крестиками
- в верхней части истории сохранить баланс, возможно - добавить сельское хозяйство

**Comment by cptn-solo** [comment]
BLOCK #22866768
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 120.00000 UTDEV.SKILL

Смотрим в понедельник, скилл с учетом выходных

**Comment by RomaRAD** [comment]
Посмотрелд свежим взглядом сегодня, понял, что перебор. сейчас упрощаю.
@kkrupovich @alecvert @jackal1527 
![main](https://user-images.githubusercontent.com/33925750/34318187-2b38f056-e7e3-11e7-8288-f16fe25c1bc0.jpg)

**Comment by alecvert** [comment]
@kkrupovich @RomaRAD @nat-brit @jackal1527 

1. Атомную энергетику точно выкидываем, давай заменим его футбольным стадионом ( логика- здоровый образ жизни) или стадионом для бега, вообщем спортивное сооружение.

![image](https://user-images.githubusercontent.com/30151576/34318221-74cda83c-e7e4-11e7-92c3-18d4d6867776.png)

2. Перейдём к тому, что внутри круговой путевой структуры

![image](https://user-images.githubusercontent.com/30151576/34318313-8a5aa784-e7e6-11e7-968a-ae6f2162f3d0.png)

Добавь логику - медицина (госпиталь) и школа (образование) . 

Где производство поставь крестик , иначе везде галочки.

На крышу одного здания высокого добавь неоновую надпись DEX, у меня в примере написано DAC, исправлять уже не буду ( лучше здание сделать цифровым ), перемести его чуть левее, а остальные убери.

Юнибайк сделай поменьше, а то он огромен) 

Станции расположи подальше пжлст , а то нелогично, короткое расстояние , можно обе того типа как ты отрисовал.

3. Я бы поубирал то, что зачеркнул и соединил бы линии электропередач. 

![image](https://user-images.githubusercontent.com/30151576/34318355-732ff9e6-e7e7-11e7-9696-9ad41d5e1414.png)

4. Пьедестал DPoS тоже наверное сделать либо стеклянным, либо как-то, но не белым.

Внутри круга, см. Выше

**Comment by RomaRAD** [comment]
сразу докину упрощенный вариант
![main_2](https://user-images.githubusercontent.com/33925750/34318398-6d05192e-e7e8-11e7-9b9c-84b720d46926.jpg)

**Comment by RomaRAD** [comment]
@kkrupovich @jackal1527 
Так и не увидел ваших комментариев, поэтому внес правки только @alecvert
![default](https://user-images.githubusercontent.com/33925750/34327000-3f9c010c-e8db-11e7-877c-669a0bee700e.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD последний вариант вполне хорош. 
Что нравится:
- дорожки токопроводящие
- иконки над зданиями (это лучше, чем галочки)
- DPoS - норм+, хоть и весьма дерзко отсылает к EOS ;))
- цифровое "здание" - но с оговоркой (см. ниже)

Что НЕ нравится (может вызвать вопросы):
- теплицам в левом нижнем углу несколько тесновато
- если и делать дэкс в виде здания (что само по себе ставит вообще крест на идее DEX как _децентрализованной_ обменной площадке), то надо делать его еще более цифровым, эфемерным (как и саму вывеску)

Вообще ощущение у меня опять скорее положительное, а я - человек ощущения. Если нравится - просто кидаю в корзину и иду дальше, не приглядываюсь ни к ценникам, ни к ингредиентам ;)

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich согласен с комментами Кости по Dex, пример , что еще надо зачеркнуть сброшу в телегу в личку. С моб. приложения не прикрепляется(

**Comment by RomaRAD** [comment]
Шапка с добавлением оранжеговго
@kkrupovich @alecvert @jackal1527 
![default](https://user-images.githubusercontent.com/33925750/34333824-706ee812-e962-11e7-82eb-e0193a3c971f.jpg)
![_](https://user-images.githubusercontent.com/33925750/34333825-727b3ea8-e962-11e7-96ff-aa4c61ffcfa4.jpg)

**Comment by jackal1527** [comment]
### По первому экрану:
- выбивается угловатый стиль по отношению ко всем остальным изображениям (эт наверное самое главное)
- очень много Зеленого цвета, как то бы его сократить
- по моему сейчас композиционно потерялась сеть скайвей. сейчас просто ощущается какая-то инфраструктура. и если не знать что такое ДПОЗ - тогда вообще не понятно что происходит
- опять же - очень много голубого (окна зданий) его бы поменять на серый или очень бледно голубой. 
### По основному сайту
- штриховочка грубовата и толстовата, ее бы скопировать с моего макета... (там НЕпрозрачность всего 6-10 процентов + штриховка чуть-чуть чаще идет)

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich согласен с комментами Кости по Dex, пример , что еще надо зачеркнуть сброшу в телегу в личку. С моб. приложения не прикрепляется(

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert Внес правки - убрал лишнее, выделил центр, успокоил цвета.
 
![default](https://user-images.githubusercontent.com/33925750/34338573-b788c26c-e98b-11e7-89c2-e086cae768f4.jpg)
@jackal1527  "выбивается угловатый стиль по отношению ко всем остальным изображениям (эт наверное самое главное)"  ниже у нас идут совсем другого плана картинки, но они едины за чет ракурса. В главную иллюстрацию, где было уместно, я добавил скругления (дороги, агро, убрал высотки).

**Comment by jackal1527** [comment]
Стало лучше Ром)
зеленого все еще многовато.
ну и синивы тож.

**Comment by cptn-solo** [comment]
@alecvert @jackal1527 скиллуем еще день? сегодняшний уже точно, мне кажется, надо оплачивать. Завтра смотрим. Финальный список жду в комменты, и уходим на итерацию, смотрим завтра утром, и нормально решаем - продолжать, или брать следующие задачи по [списку](https://github.com/u-transnet/www-teaser/projects/3)

**Comment by nat-brit** [comment]
Хорошо. Мне не очень нравится больница рядом с центром и ДЕПОСом - перенести куда-нибудь можно? И футбольное поле слишком грамоздко смотриться из-за стенок. Либо тоже перенести, либо облегчить стадион другими трибунами. Не очень поняла назначение станции (внизу справа с лесенкой) - может быть вообще убрать и не перегружать картинку?
Очень классно белые линии по земле с узлами, их можно продолжить и к другим зданиям - все взаимосвязано.
Надписи DPoS и DEX я бы сделала тоньше.

**Comment by cptn-solo** [comment]
BLOCK #22958199
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
> Доп. скилл под финальную попытку, смотрим утром 26 декабря 2017

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich @jackal1532 @nat-brit

1. Теплицы стали гармоничнее.

2. Нельзя путевую структуру так выделять, иначе кажется как будто в прозрачной трубе.

3. У станции есть смысл, когда естб вторая станция, но только если они располагаются от друг-друга на расстоянии.

4. Стадион футбольный можно заменить на беговой стадион либо турники и т д, вообщем что-то без трибун.

5. Госпитать можно сделать менее высотным зданием скругленным , убрать красный крест и написать HOSPITAL, а иконку вверху крест можно сделать

6 . Еще бы куда то надпись IoT ( интернет вещей вставить ) на здание или на стоянку авто 

7. Давайте иконки над зданиями сделаем может оранжевыми? А то Вова прав, что много зеленого и синевы.

**Comment by alecvert** [comment]
8. Токопроводящие дорожки лучше все здания соединить да.

9. Юнибайк надо чуть уменьшить

10. Вторую станцию как была в прошлом виде лучше добавить , но чтоб не нагружало, а то не логично , что одна станция. Подвижной состав должен куда-то приезжать и откуда-то уезжать

**Comment by alecvert** [comment]
@kkrupovich скилуем конечно

**Comment by RomaRAD** [comment]
Надписи на зданиях все убрал, по барами так все понятно.
Для здания DEX сеста со второй станцией не осталось, предлагаю сделать ее не в виде здания.
Все остальные пожелания внес.
Над центральным элементом еще подумаю, завтра еще свежим взглядом доделаю два варианта. 
@kkrupovich @alecvert @jackal1527 
![25 _](https://user-images.githubusercontent.com/33925750/34342251-aa4d18b0-e9cb-11e7-9671-432aaa01d19d.jpg)

**Comment by cptn-solo** [comment]
@alecvert @RomaRAD @jackal1527 @nat-brit - стекляха в центре - это чип! Добавьте туда чип (а-ля процессор) и  надо его просто подписать (DPoS)

От @jackal1527:
- сейчас не выделена кольцевая линия - получился просто "город будущего", надо выделить кольцо и инфраструктурные объекты, которые к нему подключены (отдельным цветом, или поднять его выше, вытащить НАД окружением)
- маркеры (оранжевые) - усиливают акцент на городской, а НЕ на транспортной. А надо бы наоброт. 

И, судя по всему, все-таки не удастся нам уйти на другую задачу, если завтра утром не получится родить какой-то устраивающий всех результат. Коллеги, не увлекайтесь. Хотя я вас понимаю :) классно получается.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich  @jackal1527 @nat-brit 
Доделал варианты центрального элемента 
![_](https://user-images.githubusercontent.com/33925750/34347035-0d709184-ea20-11e7-89cf-39ee45a9fe59.jpg)

**Comment by RomaRAD** [comment]
С "алмазом" и без оранжевых маркеров
![25 _5](https://user-images.githubusercontent.com/33925750/34347311-9d7dab9c-ea23-11e7-9cce-53189ee2a417.jpg)

**Comment by alecvert** [comment]
@RomaRAD заменить остроугольный алмаз на тот, который я указал в телеге и все хорошо, думаю можно уходить на след.задачу.

Я даже согласен на оранжевую путевую структуру для выделения путевой структуры. Может какой-то оранжевый элемент небольшой еще на юнибайке.

**Comment by RomaRAD** [comment]
@alecvert  ![26 _6](https://user-images.githubusercontent.com/33925750/34349527-560ef350-ea33-11e7-8461-b4461ad156ef.jpg)

**Comment by RomaRAD** [comment]
![26 _7](https://user-images.githubusercontent.com/33925750/34349729-ab858ac8-ea34-11e7-86b2-143f6fdf740c.jpg)

**Comment by RomaRAD** [comment]
https://github.com/u-transnet/www-teaser/tree/prototyping/mainscreen
@kkrupovich выложил исходник и файл для прототипа сайта

**Comment by RomaRAD** [comment]
![_](https://user-images.githubusercontent.com/33925750/34352325-b3994f60-ea43-11e7-806d-f4c3851a15aa.jpg)

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #22982032
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 190.00000 UTDEV

Спасибо!
