### ISSUE TITLE
Изменение цветовой схемы сайта

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#72]
Согласно сэмпла макета ниже меняем:
- графику под макет (@RomaRAD оцени время плз)
- макет (@jackal1527 оцени время плз)

Перевыкладываем исходники! (полагаю, вы уже знаете где что лежит)

На выходе @EvgeniyPolyakov должен получить новый материал для работы. 

![05_03](https://user-images.githubusercontent.com/1105555/34300927-750f1136-e73b-11e7-8b59-c8f3af07e9d2.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #22873480
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
> Отгружаем под верстку макет к коцу понедельника 25 декабря 2017

**Comment by alecvert** [comment]
1. @jackal1527 @RomaRAD пиджак у институционального инвестора сделайте синего цвета, а не зелёного

![image](https://user-images.githubusercontent.com/30151576/34311055-d7852ac6-e77c-11e7-9efb-1d41631f48a9.png)

![image](https://user-images.githubusercontent.com/30151576/34311053-cda00170-e77c-11e7-91c6-6b43b564be4e.png)


2. http://prntscr.com/hr5b13
![image](https://user-images.githubusercontent.com/30151576/34311024-91873852-e77c-11e7-8e89-6b1ed0f7640c.png)
 здесь видимо не та версия прогрузилась , путевая структура не должна прерываться.

3. http://prntscr.com/hr5bjq 
![image](https://user-images.githubusercontent.com/30151576/34311036-a92303c4-e77c-11e7-8f26-9431c96d009b.png) здесь и везде не надо элементы выделять цветом ( часть опоры, путевую структуру)

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @jackal1527 

 
![_](https://user-images.githubusercontent.com/33925750/34333814-5b7137ee-e962-11e7-901d-28ad54dcf453.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 c тебя исходники, надо что-то решить, куда мы их будем складывать. Беру на карандаш

BLOCK #22966097
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 100.00000 UTDEV

Спасибо!
