### ISSUE TITLE
Адаптивная верстка - проработка макета

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#74]
адаптив - рисуем карту под 5-6 размеров - как выглядят элементы
+ контроль реализации гибкости (формула изменения элементов)

**Comment by cptn-solo** [comment]
BLOCK #22966724
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 150.00000 UTDEV.SKILL
Скилл включает сверхурочные - помощь @EvgeniyPolyakov в адаптации верстки под макет
Результат 27 декабря 2017

**Comment by jackal1527** [comment]
### 1920
![1920_transnet_](https://user-images.githubusercontent.com/32764532/34376235-8fed7cde-eb0c-11e7-89f2-fc7f0233910b.jpg)
### 1280
![1280_transnet_](https://user-images.githubusercontent.com/32764532/34376239-9353b0b4-eb0c-11e7-881a-af2c9d4fde8f.jpg)
### 1024
![1024_transnet_](https://user-images.githubusercontent.com/32764532/34376243-951507ae-eb0c-11e7-9389-70ae7e0cb4f9.jpg)
### 768
![768_transnet_](https://user-images.githubusercontent.com/32764532/34376245-96582b3c-eb0c-11e7-90b0-58036180300e.jpg)
### 640
![640_transnet_](https://user-images.githubusercontent.com/32764532/34376246-97734a06-eb0c-11e7-9ef2-285b51afc92f.jpg)

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov обратить внимание на сокращенную версию языков в выпадашке переключения языка.

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23039486
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 150.00000 UTDEV
Спасибо!

ЗЫ: насчет исходников - вопрос. Сделать-то мы может сделаем, но чего дальше-то? @jackal1527 @EvgeniyPolyakov надо что-то решать.

**Comment by jackal1527** [comment]
Все исходники тут
https://github.com/u-transnet/www-teaser/tree/prototyping/slicing/adaptive_elements
@EvgeniyPolyakov
