### ISSUE TITLE
Доработка макета мобильной верстки

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#75]
Нужно доработать и актуализировать макет с новыми элементами + сервер (в мобильной версии нет сервера)

**Comment by cptn-solo** [comment]
BLOCK #22966795
TRANSFER |  
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
Смотрим 28 декабря 2017

**Comment by jackal1527** [comment]
Все исходники тут
https://github.com/u-transnet/www-teaser/tree/prototyping/slicing/adaptive_elements
@EvgeniyPolyakov

**Comment by EvgeniyPolyakov** [comment]
@jackal1527 ок

**Comment by jackal1527** [comment]
![320_transnet_ _14](https://user-images.githubusercontent.com/32764532/34412316-5a2a1ca4-ebfe-11e7-8027-a83d5ddb787f.jpg)
### Вариант номер 1
![320_transnet_ _12](https://user-images.githubusercontent.com/32764532/34412319-5d73734c-ebfe-11e7-9305-6bb6d61d7ac4.jpg)
### Вариант номер 2
![320_transnet_ _13](https://user-images.githubusercontent.com/32764532/34412320-5d943082-ebfe-11e7-98fd-194c275a1883.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 огонь. 
- Надо только сразу будет под новую графику заложить время - в шапке сайта изменения есть
- кнопка в "подписаться" - радиус не бьется с филдом
- все же думаю лучше лентой листать преимущества, а не ушами - палец в мобиле не там лежит, не удобно будет. Хотя выглядит красивее бесспорно

**Comment by alecvert** [comment]
@jackal1527 движемся супер!

1. Первый экран в моб.версии так и останется или же отдельный макет будет?

2. По преимуществам согласен. Иначе будет теряться желание листать вниз, хотя обсудим, подумаем, есть мысль

3. Помните мы говорили про заголовки разделов? Над видами инвесторов и т д  . Делаем их или нашли другое решение, чтобы не терялась логика ?

**Comment by jackal1527** [comment]
по 3 пункту:
Я в общем пока так сделал, логика очень плохо на 320 дается

**Comment by cptn-solo** [comment]
@jackal1527 
- ушастую оставляем листалку для преимуществ
- главный экран - подумать, может закинуть картинку наверх, переставить местами блоки
- думаем про порядок и состав шагов - моб. версия - проводник, гид
- интерактив и точки входа - "выберите роль" - и погнали сразу на нужный раздел

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23045956
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 100.00000 UTDEV

Продолжаем еще день, завтра закинем скилл

**Comment by cptn-solo** [comment]
@jackal1527 мы так и не закинули скилл. А продолжали ли мы еще один день? ;)

**Comment by jackal1527** [comment]
Block #23077630
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL

До завтра 30 декабря 2017

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23077798
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 50.00000 UTDEV

Половину для тренировки закину, остаток после завершения работ

**Comment by jackal1527** [comment]
# Тестим разные стартовые экраны для моб.версии
Скинул @EvgeniyPolyakov  промежуточный вариант для верстки мобильной версии
Исходники [тут](https://github.com/u-transnet/www-teaser/tree/prototyping/slicing/mobile%20version%20320)
### 1
![320_transnet_ _01](https://user-images.githubusercontent.com/32764532/34560215-d40937ae-f166-11e7-874c-6f0543612422.jpg)
### 2
![320_transnet_ _02](https://user-images.githubusercontent.com/32764532/34560229-db87e638-f166-11e7-9ecf-7044d60a8aa4.jpg)
### 3 (одна кнопка действия)
![320_transnet_ _03](https://user-images.githubusercontent.com/32764532/34560240-e5005286-f166-11e7-8a5f-6500001222e7.jpg)
### 4
![320_transnet_ _04](https://user-images.githubusercontent.com/32764532/34560260-f3086922-f166-11e7-9518-cfaa5d66732b.jpg)

**Comment by jackal1527** [comment]
![320_transnet_ _05](https://user-images.githubusercontent.com/32764532/34561619-b4379370-f16c-11e7-92ff-9ee542d99055.jpg)

**Comment by cptn-solo** [comment]
Последний (пятый) вариант оставляем (с элементом раскрытия блока описания + версия в инверсии)

Кнопки: 
- концепция
- вход в блокчейн
- блог

@jackal1527 просьба актуализировать исходники и тогда мы закрываем

**Comment by cptn-solo** [comment]
@jackal1527  клянется, что обновил исходники, посему отправляю остатки:

BLOCK #23353453
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 50.00000 UTDEV

Спасибо!

**Comment by jackal1527** [comment]
@EvgeniyPolyakov Исходники [тут](https://github.com/u-transnet/www-teaser/tree/prototyping/slicing/mobile%20version%20320)
@kkrupovich закрываем
