### ISSUE TITLE
Проработка концепции "корпоративного" многостраничного сайта (под размещение)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#79]
@jackal1527 @alecvert коллеги, надо здесь формулировать вИдение корпоративного сайта - кто что вкладывает в это понятие.

**Comment by cptn-solo** [comment]
@alecvert @nat-brit предалаю начать прорабатывать вопрос, возможно, на каком-то этапе надо будет рассмотреть вопрос найма подрядчика на эту задачу

**Comment by EvgeniyPolyakov** [comment]
Мне кажется стоит начать с "карты сайта" - этакое обычное техзадание для любого сайта: список страниц и небольшое описание их функционала

**Comment by nat-brit** [comment]
Насколько я понимаю, для формулирования ТЗ сначала необходим список вопросов с ответами. Что мы хотим получить в результате.
