### ISSUE TITLE
макетирование - мокапы, проволока, эскизы - сбор вариантов

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#8]
Коллеги, тут можно предлагать варианты (скриншоты фрагментов сайтов, желательно - аннотировать с нумерацией и пояснениями к номерам под скриншотом) и обсуждать то, что фиксируется в [wiki](https://github.com/u-transnet/www-teaser/wiki):
Изначально, поток сознания, фиксирующий наши представления о содержимом, живут в [этом](https://github.com/u-transnet/www-teaser/wiki/Контент-и-разделы)  посте и обсуждаются в задаче #9, пожелания по стилистике - в [этом](https://github.com/u-transnet/www-teaser/wiki/Пожелания-по-стилистике), и их мы будем дополнять после обсуждения в комментариях к настоящей задаче

**Comment by kkrupovich** [comment]
TBD: добавить UX дизайнера - Володя пока у нас на это планируется, как добавим в тим - назначим его ответственным.

**Comment by jackal1527** [comment]
Так, ну я тут)

**Comment by cptn-solo** [comment]
@jackal1527 назначил :) ща еще пройдусь по тикетам посмотрю что сразу на тебя кинуть

**Comment by jackal1527** [comment]
Так вот первый Эскиз/ прототип сайта. тексты какието брал из обсуждения, какие- то просто писал рыбу.
На главном экране референсный рисунок. тут мы с ваней его изображения доработаем. будет стильно. пока дляобщего понимания этот.

![transnet_main](https://user-images.githubusercontent.com/32764532/31967146-7572988e-b926-11e7-9aba-9cb6f6767656.jpg)

**Comment by iSergeevich** [comment]
Сделал сюда иконки в стиле в котором начал работать 
![default](https://user-images.githubusercontent.com/31988874/31982565-d1db21e4-b972-11e7-97af-5286c3e961e9.png)
полноразмерные ниже:
![7](https://user-images.githubusercontent.com/31988874/31982592-e5fd8e8c-b972-11e7-9bc3-9858b75a54a3.png)

**Comment by iSergeevich** [comment]
ЦВЕТА
![default](https://user-images.githubusercontent.com/31988874/31984247-453b8208-b97a-11e7-9f7a-3386df6bda19.jpg)


ШРИФТЫ
https://www.behance.net/gallery/23503137/TT-Supermolot 
![image](https://user-images.githubusercontent.com/31988874/31376069-1d6b9862-adbd-11e7-91eb-2ea8c75b4e86.png)

https://www.behance.net/gallery/24780201/TT-Days-Sans
![image](https://user-images.githubusercontent.com/31988874/31376095-35fbbc18-adbd-11e7-8614-a667ec685bed.png)

https://www.behance.net/gallery/25065941/TT-Russo-Sans
![image](https://user-images.githubusercontent.com/31988874/31376111-46060ffa-adbd-11e7-8e72-5b928c4e2663.png)

Пока взяли за основу Casper
![image](https://user-images.githubusercontent.com/31988874/31984281-6abc447c-b97a-11e7-86cd-8c93691626a0.png)

**Comment by alecvert** [comment]
Коллеги @kkrupovich @jackal1527 @iSergeevich 

1. http://prntscr.com/h1wij1 тут надо сдвинуть надпись вверх. С планшетом смотрится хорошо, но если мы экранчик внутри подвижного состава будем делать не факт, что его даже частично будет видно на экране прокрутки сразу.

Варианты: https://prnt.sc/h1u2vg , https://prnt.sc/h1u3bp

Сама идея с картой мира хороша, но надо сделать сеткой типа как уже транснет построен, а ля https://user-images.githubusercontent.com/31988874/31064353-ced0a9ea-a754-11e7-965b-a5e4eda95cff.png . Но надо добавить иконки сюда: http://prntscr.com/h1xbg7 , например горы, лес, пустыня, шельф ( берег ) и т д. Как реально на этих территориях. Если удастся показать грузовое направление, пассажирское как-то иконками то супер.

http://prntscr.com/h1xcan здесь всё хорошо, ленты стилизовать надо под тренды биржи можно типа этого. Где тренд падения, например закраска более красным, где взлёт зелёным , см. http://prntscr.com/h1xdi6

Слева можно добавить потом видосы ссылки с переходами, которые обсуждали

3. Необходимо добавить схематичное обозначение нашего токена : http://prntscr.com/h1wysq

4. http://prntscr.com/h1wjko новое цифровое пространство после Internet of Things, основанное на  технологии транспорта "второго" уровня  . Но это не точно :)

5. http://prntscr.com/h1x5p4 1. зарегистрироваться в блокчейн  2. введите ваш email: подписаться  
Ещё надо добавить иконку :  скачать white paper

6. Следующим экраном нужно добавить эволюцию от мобильности 0.0 к мобильности 5.0 в стиле: 
https://www.google.ru/search?newwindow=1&biw=1893&bih=1018&tbm=isch&q=%D1%8D%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D1%8F+%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA%D0%B0+%D0%BF%D1%80%D0%B8%D0%BA%D0%BE%D0%BB%D1%8B&sa=X&ved=0ahUKEwjb0OztoYzXAhXlJ5oKHdggB5IQhyYIJg

Мобильность 0.0 – когда человек первобытный ходил пешком
1.0  – человек сел на лошадь
2.0  приделал колесо
3.0  на телегу поставил двигатель в начале паровой , а далее бензиновой
4.0  когда в эту телегу с двигателем, поставили мозги электронику, даже подсоединяют интернет и эти телеги пытаются связать между собой.

Мобильность 5.0 – это упорядоченная распределённая децентрализованная транспортная сеть, увязывающая внутри себя взаимодействие всех объектов Мобильности 5.0 (умный подвижной состав, умная дорога, умная станция)

Далее уже как всё работает.


7. На сэндвиче добавить: graphene http://prntscr.com/h1xmdx , bitshares http://prntscr.com/h1xmdx , EOS https://media.coindesk.com/uploads/2017/05/eos_logo_horizontal_bw-1.png . Что ещё @kkrupovich  ? Что убираем?

8. http://prntscr.com/h1xopa тут должна быть trans-server станция (он же для грузового направления погрузочно разгрузочный модуль), trans-bot подвижной состав , trans-line путевая структура.

9. Далее 2 типа человека: обычный пользователь Transnet Space и Инвестор Transnet Space
Под каждым преимущества укажем.

**Comment by iSergeevich** [comment]
@alecvert отвечаю попунктово:
1. работаю над графикой реального экрана а не планшета

2. по лентам принято в работу
услышал про сетку, принял в работу, по иконкам - горы, лес, пустыня, шельф (берег)тоже принял, рассмотреть весь мир или отдельно часть? африка, индия, оаэ например? 
по ТН - грузовое и пассажирское тоже будет, благо не зря я по ночам у компа сижу) уже нарисовано)

3. принял, работаю, делаю на основе сдвоенной U или просто U?

4. - 

5. иконку white paper нарисую

6. продумаем с Володей о эволюции

7. принял, добавлю, жду утвержденный список

8. продумаем

9. по пиплам тоже уже есть графика уже, один одет кэжуал, второй в деловом костюме, есть так же вариант М и Ж, если это имеет какое то значени, можно сделать мж и МЖ 


теперь квэсчензы от меня:
делать графику пасс. состава на несколько модулей? 
имею ввиду не ограничиваться юнибайком на 2 места?

**Comment by alecvert** [comment]
@iSergeevich принял, работаю, делаю на основе сдвоенной U или просто U? Как я сбросил пример.

услышал про сетку, принял в работу, по иконкам - горы, лес, пустыня, шельф (берег)тоже принял, рассмотреть весь мир или отдельно часть? африка, индия, оаэ например?
по ТН - грузовое и пассажирское тоже будет, благо не зря я по ночам у компа сижу) уже нарисовано) - я думаю в этом случае вся карта, посмотреть надо как лучше.

теперь квэсчензы от меня:
делать графику пасс. состава на несколько модулей? - что ты имеешь ввиду?
имею ввиду не ограничиваться юнибайком на 2 места? - да, полный спектр.

Ещё нюанс по станции: http://prntscr.com/h1y2o2 , крыша должна быть зелёная
http://prntscr.com/h1y3mk бред по опорам и как путевая структура расположена, посмотри видео подробнее.

**Comment by iSergeevich** [comment]
@alecvert ок

**Comment by cptn-solo** [comment]
> 4. новое цифровое пространство .... Но это не точно :)

ООО даа, это Очень неточно ;)

> 5  1. зарегистрироваться в блокчейн 2. введите ваш email: подписаться
Ещё надо добавить иконку : скачать white paper

Отличный план!

> 7. На сэндвиче добавить: 

DPoS, Graphene, Bitshares, EOS (пунктиром, это "будущее"), UTT (лого, монохром, @iSergeevich ?)

> 8. тут должна быть trans-server станция (он же для грузового ...

я бы тут поставил не просто бот-путь-сервер, а "экономику", треугольник общения этой троицы в процессе взаимодействия 
<img width="742" alt="screen shot 2017-10-25 at 23 45 39" src="https://user-images.githubusercontent.com/1105555/32022319-abc94c6c-b9de-11e7-9781-a528b085f89c.png">

У меня есть идея насчет Мобильности 5.0
На самом деле, мы можем смело объявлять о Мобильности 5.1 , потому что наша мобильность еще и со встроенной экономикой. И это кстати означает, что мы можем на этом доп. экране использовать символику экономическую какую-то - но это сложно показать ненавязчиво, поэтому я просто оставлю это здесь, как говорится :)

**Comment by alecvert** [comment]
@kkrupovich @jackal1527 @iSergeevich 

1. http://prntscr.com/h255tw "пассажир" нужно заменить на "пользователь"

2. На сэндвиче оставить http://prntscr.com/h258a3 http://prntscr.com/h258eb http://prntscr.com/h258id
Тут вставить лого U-TECH , который бывший UNITY с лого http://prntscr.com/h258qx 

3. Тут преимущества лучше убрать и вставить роли : пользователь и инвестор, см. http://prntscr.com/h259pc Естественно прорисованные в единой стилистике. Возле каждой роли то, чем будет обладать та или иная роль. У инвестора и пользователя есть одинаковые : - возможность использования основных услуг сети;
концепция мгновенного перемещения из т. А в т. B
использование скоростного экологичного транспорта
возможность заработка внутри сети
возможность получения квалификационного токена
проживание в "умных" городах 
возможность приобретения жилья в "умном" доме и т д

У инвестора дополнение: - приобретение базового токена сети
- возможность обмена базового токена сети на блага сообщества сети
- финансирование и запуск адресного проекта сети
- возможность выкупа токена адресного проекта за базовый актив сети
Что- то ещё подумать нужно.

4. http://prntscr.com/h1wjko U-TRANSNET операционная система для синхронизации/объединения реальной экономики с цифровой в транспортных/инфраструктурных проектах и на глобальном рынке услуг.

5. http://prntscr.com/h25fse @kkrupovich нужно добавить U-TECH

**Comment by jackal1527** [comment]
![transnet_main_02](https://user-images.githubusercontent.com/32764532/32143769-6ffd7f06-bcd0-11e7-92c5-f6c54d774e64.jpg)

**Comment by jackal1527** [comment]
Так вот вторая версия нашей схемы на главной странице. 
![transnet_main_02](https://user-images.githubusercontent.com/32764532/32143801-0ab8ccc6-bcd1-11e7-89b8-8190f047ff3f.jpg)

**Comment by jackal1527** [comment]
Вторая схемы (параллельная), которую обсуждали с Костей, еще в процессе. делаю.
можем по этой схеме в скайп собраться прямо сегодня.

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert @githleo @iSergeevich 
Коллеги, предлагаю в этой задаче сконцентрироваться над структурой и макетом как таковым (стиль, подача, акценты, общая компоновка). 
Непосредственно шлифовкой отдельных блоков необходимо заниматься в задаче #9 по контенту и [документе](/u-transnet/www-teaser/wiki/Контент-и-разделы) wiki, которые для этих целей созданы ранее

**Comment by cptn-solo** [comment]
По структуре хотел свои наблюдения отметить:
1. не забыть добавить раздел про мобильность 5.1
2. логотип - Алексей сказал, заменить на u-tech (желательно вместо "-" нарисовать точку/шарик. И "U" в u-tech наверное надо как-то подсветить что ли. Посмотрите, как в t-mobile сделано в каком-нибудь
3. надо начинать продумывать "выноски" - как будут выезжать (если будут) и в каком вообще виде все это будет - под мышкой будет всплывать что-то или нет

4. Отдельно по целевой аудитории мне интересно - нужно ли нам где-то на сайте вообще показывать процесс эмиссии, пиринговый шлюз, вот это все? Про делегатов, про голосование за проекты и за делегатов/комитет? Или ограничиваем раскрытие архитектуры решения на стартовой страницы минимальным присутствием (в виде логотипа dPoS на ноде) - этот логотип, кстати, может быть неплохим пасхальным яйцом. Если кто-то узнает этот логотип - он очень заинтересуется нами - и если ткнет в лого dPoS - может быть ознакомлен с внутренним экономическим движком Пространства, реализованном на Graphene

5. надо понять какие еще разделы информации должны присутствовать на стартовой ленте - например, дисклеймеры и т.п. по-идее должны быть, надо это как-то тоже в макет включать @jackal1527 чтобы нам их потом предметно обсуждать в #9

**Comment by iSergeevich** [comment]
графика по поводу планшета
![3](https://user-images.githubusercontent.com/31988874/32153391-018f476c-bd4c-11e7-8124-209f7d1e27fa.png)
и как вариант использовать иконки ниже на картах любых как схематичное обозначение объектов - деревья и всякая прочая природная сущность
![stock-vector-isometric-d-forest-camping-elements-for-landscape-design-tent-and-deer-camp-and-bear-272952812](https://user-images.githubusercontent.com/31988874/32153478-a2a337bc-bd4c-11e7-9484-d64d7ccb2619.jpg)


два вида планшета из салона скину позже в течении дня, будет два положения,не знаю какой удобнее поэтому буду доделывать оба...

Вова предложил делать графику в стиле предложенного им сайта который сейчас взяли за основу - окей делать буду так.

вопросы далее, выбираем графику таймлайн по эволюции, это референсы но я сделаю тако й же вариант без проблем, выбрал минималистичные но разные по стилю. смотрим. выбираем - я делаю:
![stock-vector-auto-colorful-icons-set-collection-of-gear-lever-chassis-station-wagon-and-other-elements-also-697140757](https://user-images.githubusercontent.com/31988874/32153433-643c0116-bd4c-11e7-82e4-7b6ddaa5f36e.jpg)
![stock-vector-infographic-report-template-with-place-for-your-text-vector-illustration-337662302](https://user-images.githubusercontent.com/31988874/32153434-645e1d6e-bd4c-11e7-93c0-1d3a56717cb8.jpg)
![stock-vector-road-infographic-vector-template-with-red-isometric-car-business-road-infographic-start-finish-and-730871998](https://user-images.githubusercontent.com/31988874/32153435-64811c6a-bd4c-11e7-80a2-512037fff694.jpg)
![stock-vector-timeline-infographic-design-template-vector-illustration-for-workflow-layout-diagram-number-324860372](https://user-images.githubusercontent.com/31988874/32153436-64a56688-bd4c-11e7-9cac-dc412a079531.jpg)
![stock-vector-vector-infographic-company-milestones-timeline-template-with-pointers-and-photo-placeholders-on-a-593032475](https://user-images.githubusercontent.com/31988874/32153437-64c56136-bd4c-11e7-9b1f-406155a48e0b.jpg)
![stock-vector-vector-infographic-company-milestones-timeline-template-with-pointers-on-a-curved-road-line-631597076](https://user-images.githubusercontent.com/31988874/32153438-64e5f522-bd4c-11e7-8cce-b1dcc2de00dd.jpg)
![stock-vector-vector-infographics-timeline-design-template-with-d-paper-label-integrated-circles-background-566586028](https://user-images.githubusercontent.com/31988874/32153439-65050fb6-bd4c-11e7-9bcf-6026a3ad2108.jpg)

мысли насчет транспорта по таймлайну с раскадровкой разных степеней мобильности от 0 до 5
![stock-vector-equestrian-sports-polo-dressage-contest-man-on-horse-isometric-vector-flat-d-illustration-620542754](https://user-images.githubusercontent.com/31988874/32153465-86e48684-bd4c-11e7-8caa-b0e1dbe4e948.jpg)
![stock-vector-isometric-retro-coaches-brougham-icon-flat-illustration-of-brougham-vector-isolated-on-white-583466623](https://user-images.githubusercontent.com/31988874/32153466-87057b14-bd4c-11e7-8c9b-6e5d9f12d506.jpg)
![stock-vector-set-of-th-century-and-modern-mine-workers-with-work-tools-horse-drawn-cart-with-coal-mining-730959583](https://user-images.githubusercontent.com/31988874/32153467-87245340-bd4c-11e7-928a-01d3955e47dc.jpg)
![stock-vector-wagon-icon-isometric-illustration-of-wagon-icon-for-web-728834989](https://user-images.githubusercontent.com/31988874/32153468-8747deb4-bd4c-11e7-8065-5739db30efed.jpg)

касательно схемы эволюции мое мнение стоит сравнивать поэтапно транспорт но с уклоном в поезда, так как транспортные средства skyway почти на 100% относятся к подвижному составу этого типа. 
человек, потом человек на лошади, потом повозка с лошадью, потом локомотив с паровым двигателем, потом электровоз, потом типа сапсан и потом skyway как вершина техники

мысли насчет слов про передачу данных между транспортными средствами - давайте организовывать это примерно вот в таком виде. удобно для сайта использовать тоже
![stock-vector-scheme-of-railway-station-system-with-different-trains-platform-rails-tunnel-and-other-elements-472727095](https://user-images.githubusercontent.com/31988874/32153498-cc3b7fee-bd4c-11e7-881e-d1123c53b6ca.jpg)
![stock-vector-smart-city-internet-of-thing-solutions-managing-safety-energy-supply-communication-and-transport-607020269](https://user-images.githubusercontent.com/31988874/32153499-cc5f88a8-bd4c-11e7-9169-dca87a0134b6.jpg)
![stock-vector-transportation-integrated-d-web-icons-digital-network-isometric-interact-concept-connected-618150332](https://user-images.githubusercontent.com/31988874/32153500-cc7f93c8-bd4c-11e7-86ca-9cca19a7e240.jpg)

пользователей (обычный пользователь Transnet Space и Инвестор Transnet Space) 
нарисовал на 1 картинке в шапке этого месаджа. цвета кожи, волос и одежды любые

касательно графики - если что-то референсов на ваш взляд ну прям очень нам подходит, я просто покупаю эту графику и оперируем ей в дальнейшем, для этого и созжданы стоковые сайта - не можешь сделать сам - купи =)

**Comment by jackal1527** [comment]
НЕкст вершн оф ауэ бьютифул сайт.
![transnet_main_03](https://user-images.githubusercontent.com/32764532/32274572-4174314c-bf29-11e7-8a54-c43dceb8584e.jpg)

**Comment by jackal1527** [comment]
Кароче по основным правкам сделал 4-ю по счету версию.
давайте обсуждать
![transnet_main_04](https://user-images.githubusercontent.com/32764532/32488845-d8ebf1d6-c3cf-11e7-8e71-2bea5e888614.jpg)

**Comment by cptn-solo** [comment]
1. название (UNITY -> U|TECH)
2. планшет: 
2.1. вертикальный планшет (а-ля юнибайк);
2.2. юани убираем;

2а. Инвестиции/пользователи:
2а.1. Институциональные инвесторы;
2а.2. Частные инвесторы (краудфандинг);
2a.3. Пользователи сети;
2а.4. Добавляем "mob" про whitepaper на линии от инвестора и краудфандинга:
<img width="254" alt="screen shot 2017-11-07 at 15 12 24" src="https://user-images.githubusercontent.com/1105555/32493224-224ff900-c3ce-11e7-9202-4588c850426c.png">

3. как все работает - переход физ. в цифру - тут можно использовать путевую структуру вместо точечного объекта (точечный у нас уже будет в виде узла сети ниже). Наглядно можно посмотреть в видосах:
3.1. физическая (рендер): https://youtu.be/h-s5kNqrxJ4?t=1m41s
3.2. цифровая (проволока): https://youtu.be/h-s5kNqrxJ4?t=1m27s

4. Карта:
4.1. Убираем иконки (возвращаемся к шарикам);
4.2. Справа фиксированно отображаем схематично три типа объектов (с выносками - направо к объектам - типа такого:
<img width="256" alt="screen shot 2017-11-07 at 15 01 10" src="https://user-images.githubusercontent.com/1105555/32492799-9423b000-c3cc-11e7-8320-10a4577defcd.png">) 

5. выход из карты - перед трилистником - добавить упоминание бизнес-плана (визуально - в виде иконки "чек-листа"):
<img width="134" alt="screen shot 2017-11-07 at 15 03 57" src="https://user-images.githubusercontent.com/1105555/32492918-f9de2cfe-c3cc-11e7-9332-4e831377db96.png">

6. на трилистник - на каждый кружок - иконку соотв. физич. объекта

7. Выход из токенизации - убрать разделение возврата инвестиций на институционалов и крауд - сделать общую панельку - "рост". При этом _под этой частью_ все остается разделенным на три части (инст, крауд, пользователь)

8. Промо-видео TRANSNET SPACE - это развитие задачи [вводной презентации](https://github.com/u-transnet/info/issues/15) (которая потом и будет анимирована, задачи пока нет, но есть [карточка](https://github.com/u-transnet/info/projects/1#card-4829544) на доске проекта)

9. Раздел "варианты участия" (для программистов, переводчиков и т.п.)


PS: возможно, после финальной проработки текстового наполнения блоков, добавим "водяные знаки" на задник (не чисто белый фон)

**Comment by alecvert** [comment]
1. @iSergeevich http://prntscr.com/h7wnmy здесь нужно сделать как планшет в юнибайке выглядит, см. http://prntscr.com/h7wqaf. Только слева направо разворот планшета, тут справа налево.
Лицо не знаю наверное не надо, руку возможно надо, надо посмотреть.

По Валютам, где юань замени на биток.

В прошлой версии, вот эти элементы выглядели симпатично http://prntscr.com/h7woim , но их нужно не просто вставить, а прорисовать. 
http://prntscr.com/h7wp3t что это несёт в себе? Почему только иконка гор , а где остальные обозначения, пустыня, лес, джунгли, тайга, тундра и т д. То есть разные виды поверхности и рельефа , но главное, чтоб не перегрузить

2. http://prntscr.com/h7wqy0 возможно имеет смысл пододвинуть вверх , тогда будет виден экран планшета сразу.

3. http://prntscr.com/h7wrpp добавить иконку Концепция ( paper v. 1.0)

4. Где цифровой и реальный мир взять по стилю типа http://prntscr.com/h7wvf0 , но с нашими иконками станций. Цифру сделать проволокой, смысл: http://prntscr.com/h7ww9h , разделительной полосы и вообще разделения между реальным и цифровым миром быть не должно, плавный переход в проволоку а ля http://prntscr.com/h7wxkt

5. Добавить Институциональные инвесторы, изменить иконку на образ "капиталиста".

6. Добавить  Частные инвесторы , изменить иконки на разношёрстную публику, офисный работник, хипстер, домохозяйка, медик, учитель, студент и т д.

7. Тут заменить на U TECH http://prntscr.com/h7wzou лого 

8. Иконки а ля преза, но наверное тут лучше 2d, хотя можно попробовать http://prntscr.com/h7x066
Добавить автономность.

**Comment by alecvert** [comment]
1. @iSergeevich http://prntscr.com/h7wnmy здесь нужно сделать как планшет в юнибайке выглядит, см. http://prntscr.com/h7wqaf. Только слева направо разворот планшета, тут справа налево.
По Валютам, где юань замени на биток.
В прошлой версии, вот эти элементы выглядели симпатично http://prntscr.com/h7woim , но их нужно не просто вставить, а прорисовать. 
http://prntscr.com/h7wp3t что это несёт в себе? Почему только иконка гор , а где остальные обозначения, пустыня, лес, джунгли, тайга, тундра и т д. То есть разные виды поверхности и рельефа , но главное, чтоб не перегрузить

2. http://prntscr.com/h7wqy0 возможно имеет смысл пододвинуть вверх , тогда будет виден экран планшета сразу.

3. http://prntscr.com/h7wrpp добавить иконку Концепция ( paper v. 1.0)

**Comment by alecvert** [comment]
1. @iSergeevich http://prntscr.com/h7wnmy здесь нужно сделать как планшет в юнибайке выглядит, см. http://prntscr.com/h7wqaf. Только слева направо разворот планшета, тут справа налево.
По Валютам, где юань замени на биток.
В прошлой версии, вот эти элементы выглядели симпатично http://prntscr.com/h7woim , но их нужно не просто вставить, а прорисовать. 
http://prntscr.com/h7wp3t что это несёт в себе? Почему только иконка гор , а где остальные обозначения, пустыня, лес, джунгли, тайга, тундра и т д. То есть разные виды поверхности и рельефа , но главное, чтоб не перегрузить

2. http://prntscr.com/h7wqy0 возможно имеет смысл пододвинуть вверх , тогда будет виден экран планшета сразу.

3. http://prntscr.com/h7wrpp добавить иконку Концепция ( paper v. 1.0)

**Comment by alecvert** [comment]
1. @iSergeevich http://prntscr.com/h7wnmy здесь нужно сделать как планшет в юнибайке выглядит, см. http://prntscr.com/h7wqaf. Только слева направо разворот планшета, тут справа налево.
По Валютам, где юань замени на биток.
В прошлой версии, вот эти элементы выглядели симпатично http://prntscr.com/h7woim , но их нужно не просто вставить, а прорисовать. 
http://prntscr.com/h7wp3t что это несёт в себе? Почему только иконка гор , а где остальные обозначения, пустыня, лес, джунгли, тайга, тундра и т д. То есть разные виды поверхности и рельефа , но главное, чтоб не перегрузить

2. http://prntscr.com/h7wqy0 возможно имеет смысл пододвинуть вверх , тогда будет виден экран планшета сразу.

3. http://prntscr.com/h7wrpp добавить иконку Концепция ( paper v. 1.0)

**Comment by cptn-solo** [comment]
@alecvert я чего-то так и не понял -  у тебя новая нумерация пунктов, или ты с какой-то из предыдущих нумераций продолжаешь?

**Comment by jackal1527** [comment]
![transnet_main_05](https://user-images.githubusercontent.com/32764532/32786686-75e4856a-c976-11e7-9c61-57a52f8a0e15.jpg)

**Comment by cptn-solo** [comment]
0. Задача по проработке шапки выделена отдельно: #13 

1. Ссылка на краткую ознакомительную презентацию из [info/#14](https://github.com/u-transnet/info/issues/14)

2. Карту попробуем повернуть в фас (не изометрия) и во всю ширину. По цвету - блекло, в стиле серых заголовков разделов (можно с тенью)

3. От Карты провести линии к иконкам типов объектов справа

4. Меняем "бизнес-план" после карты: 
иконка "чеклист" выходит из карты и "отображается" в "проволочный" бизнес-план. При этом сам по себе заголовок секции меняется - это не распределение, это оцифровка. "Распределение" переезжает вниз. При этом можно подписать "бумажный" бизнес-план именно как Бизнес-план, а "проволочный" - больше текста, например "токенизация адресного проекта"

<img width="577" alt="screen shot 2017-11-14 at 18 33 57" src="https://user-images.githubusercontent.com/1105555/32788530-7bfad9e2-c96a-11e7-994a-f9da4bcfc745.png">

5. Внизу, после "шайбы" - убираем иконки бизнес-плана вообще, а заголовок/подпись "Распределение..." перемещаем к диаграмме (справа, сверху, куда-то в общем - но лучше справа)

6. Подписи к выходным картинкам - оставляем по одной подписи к картинке - т.е. одна подпись к возврату инвестиций и одна - к планированию маршрута. А уже внизу - в замыкающей части - можно и нужно оставить три колонки, т.к. надо объяснить разницу интереса для институциональных и крауд-инвесторов

**Comment by cptn-solo** [comment]
Насчет команды: возможно, имеет смысл сделать граф с центром = блокчейн u-transnet (наш основной наниматель, в лице основного подрядчика - U-TECH и советников и т.п.) 

Концепт:

<img width="984" alt="screen shot 2017-11-14 at 19 39 54" src="https://user-images.githubusercontent.com/1105555/32792167-ccc0d9c2-c973-11e7-9d8c-26c8ec6e78f9.png">

**Comment by cptn-solo** [comment]
Вообще-то я думал мы ее закрыли, т.к. теперь уже идут доработки макета в итерациях, первая итерация #14
