### ISSUE TITLE
Мобильная версия на 320px (новая концепция)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#82]
Источник в #75

@jackal1527 просьба расписать - почему это отдельная версия концепции, чтобы понимали, в чем суть задачи

**Comment by jackal1527** [comment]
Итак.
Адаптированный макет из 1920 в 320 все, общим мнением сочли неудачным.
Нужна новая и отдельная концепция. Она будет состоять из нескольких ключевых блоков (типа пошаговая структура) у каждого блока будет ключевое действие ( кнопка"подробнее"), которое будет открывать поп-ап с подробной информацией (её мы частично возьмем с уже сделанной версии).
Моя задача состоит в разработке данной концепции

**Comment by jackal1527** [comment]
@kkrupovich 

Block #23241335
Transfer
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
Смотрим: Суббота 6.01.2018

**Comment by jackal1527** [comment]
# весь макет
![320_transnet_ _15](https://user-images.githubusercontent.com/32764532/34772088-aff769dc-f628-11e7-80c7-db97f286439e.jpg)
# фрагмент поп-апа
![320_transnet_ _16](https://user-images.githubusercontent.com/32764532/34772110-c1d3b156-f628-11e7-82ae-1b9b8d825e59.jpg)

**Comment by jackal1527** [comment]
что сделано:
1) переработал подачу информации в центральной части макета (там у нас основная схема)
теперь там четыре распределяющих блока - при клике на кнопку действия - открывается поверх окно с более подробным описанием (части того что было на старом макете с подробными иллюстрациями)
2) немного переделал иллюстрации ( они состоят из уже использованных элементов и представляют более компактную иллюстрацию)

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert @nat-brit 
Коллеги, решили подход к разметке информационного блока (заголовок+иллюстрация+текст) и по отображению подробностей в попапе. 
Теперь ждем окончания доработок [документа](https://docs.google.com/document/d/1YVSPuuhYEkJnb-Y-H7ADx6Qv96yKYGDDnarQ0iPUoXg/edit) и начинаем адаптировать макеты (общий и мобильный) под новую подачу информации, новую последовательность блоков. 

Текущую задачу закрываем

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23444144
TRANSFER |  
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV

Спасибо!
