### ISSUE TITLE
Адаптация основного макета сайта под промежуточные разрешения

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#83]
Происходит из #75 #80 

@jackal1527 @EvgeniyPolyakov аналогично - просьба расписать что будет входить в эту задачу

**Comment by jackal1527** [comment]
Задача сделать промежуточные экраны (макет 1920) на 1280, 1024, 768, 640.
Это нужно для того, что бы @EvgeniyPolyakov построил правила адпаптивности сайта.

**Comment by jackal1527** [comment]
### Смотрят
@kkrupovich @EvgeniyPolyakov @nat-brit или @alecvert 

Block #23444219
Transfer
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
Смотрим: Суббота 13.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
# 1280
![1280_transnet_](https://user-images.githubusercontent.com/32764532/34938696-24d74f16-fa0b-11e7-8837-67ba14831be0.jpg)
# 1024
![1024_transnet_](https://user-images.githubusercontent.com/32764532/34938720-2fc17924-fa0b-11e7-8462-156b950ee455.jpg)
# 768
![768_transnet_](https://user-images.githubusercontent.com/32764532/34938737-39ff825a-fa0b-11e7-8e71-cdf69d4e6459.jpg)
# 640
![640_transnet_](https://user-images.githubusercontent.com/32764532/34938758-47a96c72-fa0b-11e7-9b28-e67639ddda33.jpg)
# 320
![320_transnet_ _15](https://user-images.githubusercontent.com/32764532/34938780-5ad391f6-fa0b-11e7-830e-01ca486d4bdf.jpg)

**Comment by jackal1527** [comment]
Что сделано:
1) для разрешений 1280, 1024, 768 адаптировано по 4 блока сверху.
2) для разрешения 640 - адаптация будет по типу мобильной версии (см.макет), чтобы не запутываться с большой схемой, которую сложно стыковать.
в принципе для 768 можно сделать так же (предоагаю обсудить)
3) скидываю сразу Жене макеты, так как он очень просит.

**Comment by cptn-solo** [comment]
@jackal1527 @EvgeniyPolyakov можно попробовать блок "как все работает" из варианта 768 сделать основной для десктоп-версии стартовой страницы сайта - картинку сделать во всю ширину, а тексты пустить над и под картинкой, а не в диагональных углах

**Comment by cptn-solo** [comment]
@jackal1527 все-таки надо переключаться на #89 , текущий макет оставляем пока без изменений
BLOCK #23561665
TRANSFER |  From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV

Спасибо!
