### ISSUE TITLE
Доработка логотипа

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#84]
Для сайта:
- Попробовать максимально упрощенные варианты
- fav-icon
- отталкиваемся от исходной [задачи](https://github.com/u-transnet/info/issues/11)

Исходники просьба заливать в бранч/папку [logo_refactoring/logo](https://github.com/u-transnet/info/tree/logo_refactoring/logo)

BLOCK #23410194
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
1 день. 10 января

Добавил за второй день
BLOCK #23447134
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
1 день. 11 января

Третий день - финал
BLOCK #23471980
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
12 января

**Comment by cptn-solo** [comment]
@RomaRAD просьба скиловать на день, попробуем посмотреть итерацию завтра, 9 января

**Comment by EvgeniyPolyakov** [comment]
Размеры favico

16x16: browser favicon
32x32: taskbar shortcut icon
96x96: desktop shortcut icon (and Google TV)
120x120: iPhone Retina (iOS 7)
180x180: iPhone 6 Plus (iOS 8+)
152x152: iPad Retina (iOS 7)
167x167: iPad Pro (iOS 8+)

формат файлов -  png

**Comment by RomaRAD** [comment]
Я пошел по пути упрощения.
Постепенно отказываясь от деталей и градиентов, т.к. они перегружают лого и усложняют его в производстве (будь то печать в не большом размере, объемное решение или наклейки).
Скажите свое мнение и под 1-2 варианта я оформлю подачу.
@alecvert @kkrupovich @jackal1527 @nat-brit  @EvgeniyPolyakov  
![unity_](https://user-images.githubusercontent.com/33925750/34721201-ac15d670-f563-11e7-9d0d-04b2988b0989.jpg)

**Comment by nat-brit** [comment]
Трудно выбрать. Мне оранжево-синий нравится, наверное, больше всего из этих, и 
![default](https://user-images.githubusercontent.com/30142436/34732636-7ed62ccc-f56e-11e7-88fc-dbb9ded411a8.jpg)
да, с квадратиками лучше смотрятся. Но цвета просятся поярче:)

**Comment by EvgeniyPolyakov** [comment]
Мне нравятся 1 и 2 во 2 ряду и 1й в 3-м - идея с дорожками печатной платы прям очень имхо! :)

**Comment by nat-brit** [comment]
У меня тоже глаз сначала упал на 2 на 2-м ряду, с черными дорожками, но как он будет смотреться в маленьком размере?

**Comment by cptn-solo** [comment]
@RomaRAD 
1. не проскиловал задачу
2. я за классику, пожалуй: 
<img width="279" alt="screen shot 2018-01-10 at 01 32 19" src="https://user-images.githubusercontent.com/1105555/34746750-4a5fc97a-f5a6-11e7-9e44-41d901530674.png">

хотя мне лично оч. понравился вариант 
<img width="165" alt="screen shot 2018-01-10 at 01 32 44" src="https://user-images.githubusercontent.com/1105555/34746790-6d080078-f5a6-11e7-97eb-67d0daf20363.png">

но я не уверен, что это читается как U

**Comment by RomaRAD** [comment]
Считаю, что все эти варианты имеют право на существование. 
Сделал простые примеры, что бы было понятно как это может выглядеть в жизни.
@alecvert @nat-brit @jackal1527  @EvgeniyPolyakov 

@kkrupovich про скилование,  я запамятовал. Можешь еще раз показать как это делается?

![-1](https://user-images.githubusercontent.com/33925750/34762108-5954e7aa-f608-11e7-8e0f-dd9b30e8a5f3.jpg)
![_2](https://user-images.githubusercontent.com/33925750/34762112-5aa64be4-f608-11e7-8ad4-23375f7c9c1f.jpg)

  
![untitled-1_](https://user-images.githubusercontent.com/33925750/34762209-cbb9d2b0-f608-11e7-82ca-8de790ba21a9.jpg)

**Comment by EvgeniyPolyakov** [comment]
Все выглядят здорово, но последний, на мой взгляд самый стильный/лаконичный/аристократичный :)
  
ps возможно зеленый заменить на синий

![](https://user-images.githubusercontent.com/33925750/34762209-cbb9d2b0-f608-11e7-82ca-8de790ba21a9.jpg)

**Comment by jackal1527** [comment]
Прикольную работу проделал @RomaRAD !!! Круто.
мне кажется для сайта нужно точно оливковый оставить.
но от оранжево-синего точно отказываться не нужно, ибо он просто офигительно смотрится с оцифрованным байком на плакате.

Ну и офис с оранжевым смотрится круче. светлее чтоли..

**Comment by nat-brit** [comment]
Круто смотрятся. Но я все-таки за второй, думаю, что по причине цвета. Мне последний тоже очень нравится по стилю, но зеленый цвет не нра. Когда белый на черном фоне - отлично, стильно. Когда в рекламе или не стенде - не хватает яркости, не знаю, как по психологии, будет ли запоминаться... Может попробовать в третьем заменить зеленый цвет на другой, синий, например?

**Comment by alecvert** [comment]
Мои предпочтения  , но с цветами надо что-то думать. 

Токопроводящие дорожки хорошо, но что-то не то, как будто ещё что-то доработать надо.

![image](https://user-images.githubusercontent.com/30151576/34763637-ac9b86d0-f60d-11e7-84ce-d5fd11f3f473.png)
@kkrupovich @EvgeniyPolyakov @RomaRAD @nat-brit @jackal1527 Ещё главный вопрос на концепции лого на такой и останемся? Может у Ромы что-то ещё в голове родилось в ходе работы.
 
Очень хорошо на тёмном фоне смотрится яркая классика 
![image](https://user-images.githubusercontent.com/30151576/34763785-27be2e9e-f60e-11e7-9790-540632972133.png)
Может края обвести оранжевым тонко?

**Comment by RomaRAD** [comment]
Эскизы в разных цветовых моделях.
![logo color](https://user-images.githubusercontent.com/33925750/34763966-c79540ba-f60e-11e7-9db3-688db6bc963e.jpg)

**Comment by nat-brit** [comment]
![logo](https://user-images.githubusercontent.com/30142436/34764095-0ba4b31c-f5f6-11e7-9719-099f044640c2.jpg)

**Comment by alecvert** [comment]
![image](https://user-images.githubusercontent.com/30151576/34764963-e425b072-f611-11e7-9845-c20eac768821.png)

Есть логика, то, что рельсы - струны - дороги с одной стороны и токопроводящие дорожки с другой.

По деталям , может подобным образом добавить элемент, и тогда лого смотрится целостным
 
![image](https://user-images.githubusercontent.com/30151576/34765232-cb51a320-f612-11e7-8c8c-9c4576c19f75.png)

![image](https://user-images.githubusercontent.com/30151576/34765268-de45e810-f612-11e7-8b1a-d0811dbcf6d9.png)

**Comment by RomaRAD** [comment]
![image](https://user-images.githubusercontent.com/33925750/34766327-dbcaba2c-f615-11e7-9c80-17afe9260a84.png)

**Comment by RomaRAD** [comment]
![image](https://user-images.githubusercontent.com/33925750/34766418-26ab2a9a-f616-11e7-8b03-0f07458c0790.png)

**Comment by RomaRAD** [comment]
Если везде делать одинаковое расстояние, то мне кажется гробоздковато получается.
Я за левый вариант.
![image](https://user-images.githubusercontent.com/33925750/34767275-818a181a-f619-11e7-8cad-7b29eeac76e1.png)

**Comment by alecvert** [comment]
![image](https://user-images.githubusercontent.com/30151576/34767846-f7d2185a-f61a-11e7-9a7f-3c70004f8ee9.png)

Думаю, что стоит чуток поднять правую токопроводящую дорожку по высоте
В этом случае и левый и правый варианты по высоте находятся одинаково и тогда нет ощущения несимметричности и то, что режет глаз

**Comment by RomaRAD** [comment]
@alecvert  
![image](https://user-images.githubusercontent.com/33925750/34770620-5fbe7b40-f623-11e7-9acd-19bc8a61de85.png)

**Comment by alecvert** [comment]
@RomaRAD давай попробуем две линии 

![image](https://user-images.githubusercontent.com/30151576/34773460-95e3902a-f62d-11e7-91c5-65e5e22a2642.png)

Этот вариант, но что-то надо сделать с моментами, которые отметил стрелочкой как-то оптимизировать и сделать более симметричными

**Comment by alecvert** [comment]
@RomaRAD по цветам , лучше яркие сочные , но не кислотные
![image](https://user-images.githubusercontent.com/30151576/34773730-949083bc-f62e-11e7-94b2-8f59ae1b112c.png) здесь как пример хорошо, но не обязательно эта цветовая гамма,  решим

**Comment by kkrupovich** [comment]
@RomaRAD делай, плз, цитату из блока в след. раз, когда скилуешь/докидываешь скилл в задачу (dashboard->activity->transfer):
BLOCK #23410194
TRANSFER |  
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
> 10 января до конца дня

**Comment by cptn-solo** [comment]
@RomaRAD по сути твоих трудов - за "дополненную реальность" - от души спасибо, выглядит это весьма эффектно. 
Из вариантов:
> @RomaRAD Считаю, что все эти варианты имеют право на существование.

полностью поддерживаю, более того, предлагаю ввести за правило регулярный ребрендинг - сделать саму картинку результатом выбора сообщества - как и доменные имена - все это должно быть плывущим, дрейфующим. 

По новому "упрощенному" логотипу мой фаворит:
<img width="229" alt="screen shot 2018-01-11 at 01 49 47" src="https://user-images.githubusercontent.com/1105555/34799696-cc4d3fc8-f671-11e7-9965-f6ee8317090b.png">

@alecvert @nat-brit @RomaRAD друзья, предлагаю закругляться с итерацией, подводить какой-то итог - и закрывать/уходить на следующую итерацию - здесь слишком много графики стало, тяжелеет ветка.

**Comment by alecvert** [comment]
@RomaRAD @kkrupovich Рома сегодня обещал подготовить ещё что-то, посмотрим и решим

**Comment by nat-brit** [comment]
![25](https://user-images.githubusercontent.com/30142436/34830362-4de265de-f6ec-11e7-8047-ff7317323fba.jpg) А может левую сторону закрасить?

**Comment by cptn-solo** [comment]
@RomaRAD, я так понимаю, с тебя скилл еще на день (сегодняшний, 11 января 2017), раз уж решили новую итерацию пока не создавать.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit @EvgeniyPolyakov 
Поиски элемента
![logo unity444](https://user-images.githubusercontent.com/33925750/34834442-d555b33c-f713-11e7-8362-cb72a97c8fdc.jpg)

Я вижу суть так
![logo unity_2](https://user-images.githubusercontent.com/33925750/34834245-62266122-f713-11e7-867d-327170d33322.jpg)

Тут еще на такую штуку наткнулся...
![screenshot_51](https://user-images.githubusercontent.com/33925750/34834469-de5e466a-f713-11e7-9d77-d078fae131b1.jpg)

**Comment by Dima-Iron** [comment]
С двумя полосками смотрится живее, не так громоздко, как с тремя, imho
Думается, что если левую сторону сделать сплошной (одной полосой), а правую в две полосы (крайняя с разрывом посередине), то будет стильнее и динамичнее
![3](https://user-images.githubusercontent.com/35292330/34836209-3c8203d2-f708-11e7-91de-a3c96f4bd2d5.png) ![default](https://user-images.githubusercontent.com/35292330/34835817-0fc37bc4-f707-11e7-943b-61aa9ed9358f.png) ![2](https://user-images.githubusercontent.com/35292330/34836183-2372b4a4-f708-11e7-8cf2-a471e36f1d5d.png)

**Comment by jackal1527** [comment]
к стати с двумя полосками довольно таки прикольно

**Comment by RomaRAD** [comment]
@Dima-Iron  Можно и со сплошной, только ее нужно делать светлее по тону, что бы не "перевешивала"
![image](https://user-images.githubusercontent.com/33925750/34836821-daf32d0e-f71a-11e7-88b9-4fae27926043.png)

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Dima-Iron @RomaRAD коллеги, мне последний вариант очень нравится, я бахнул сердечко! Предлагаю вам тоже как-то откомментить и оплатить/закрыть эту задачу, при необходимости сформировав новую под след. итерацию.

**Comment by Dima-Iron** [comment]
@RomaRAD да, то, что надо) просто я в пэйнте стандартный зеленый выбрал))

**Comment by alecvert** [comment]
@RomaRAD  
![image](https://user-images.githubusercontent.com/30151576/34837922-23a5b028-f71e-11e7-9857-d6100acd2bd0.png)
Очень круто!

![image](https://user-images.githubusercontent.com/30151576/34838021-6f4c53c4-f71e-11e7-86f7-66595d8483c8.png)
Тоже класс объяснение лого

Вообщем мне нравится новая или доработанная концепция

Лого, я лично принимаю, и это лучший вариант.

Осталось определиться с цветовой гаммой

**Comment by alecvert** [comment]
@RomaRAD Моё предложение остановиться на 

![image](https://user-images.githubusercontent.com/30151576/34842567-b32dccb2-f72d-11e7-95d4-d5bcc9fa9229.png)

Рома, сделай пжлст различные подборки фона, не только серый пжлст.

На мой взгляд цельнее и фирмовее смотрится в монохроме.

Для отдельных применений можно уже градиенты и т д под презы или как креатив сети ( кто-то космос захочет вставить и т д)

Можно также попробовать на белом фоне в логике иконок преимуществ стилистики на сайте

![image](https://user-images.githubusercontent.com/30151576/34842728-27d21f96-f72e-11e7-952f-177ee3886d59.png)
Может тогда и 2 цвета подойдут в лого

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 @nat-brit @EvgeniyPolyakov @Dima-Iron 
![logo unity_8](https://user-images.githubusercontent.com/33925750/34864314-8059c710-f795-11e7-943a-6d32f567dfd1.jpg)

**Comment by RomaRAD** [comment]
![image](https://user-images.githubusercontent.com/33925750/34864475-513ba330-f796-11e7-94c4-461431cdff74.png)
@nat-brit

**Comment by nat-brit** [comment]
Все варианты хорошо смотрятся. Мне больше нравится в цвете, когда правые полоски голубые. Я бы еще попробовала сделать комбинацию, когда левая широкая-темносиняя, а два правые-голубые. Для белого фона, естественно. Для темного фона комбинация: левая широкая-белым, а две правые - голубым:) Но вообще, уже можно закругляться, как мне кажется:) Вариант хороший и на нем можно остановится.
![67](https://user-images.githubusercontent.com/30142436/34864951-47c19efc-f77f-11e7-8adc-e75e4d81aed5.jpg)

**Comment by alecvert** [comment]
![image](https://user-images.githubusercontent.com/30151576/34864995-a737b3d0-f798-11e7-920b-4b6b619900c4.png)

Вот это сочетание очень нравится, надо посмотреть на белом.
Смысл: экогенная технология инженерная - зелёный градиент, линия сплошным
Голубой и синий градиент, линия в виде токопроводящих двух дорожек, разделение сплошной = децентрализация - цифра

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert  @jackal1527  

![logo u-tech](https://user-images.githubusercontent.com/33925750/34866856-d529d7ee-f79f-11e7-87b7-048da4a7fcaf.jpg)

исходники по ссылке [logo_refactoring/logo](https://github.com/u-transnet/info/tree/logo_refactoring/logo) (реп. info)

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov @RomaRAD @jackal1527 перенес исходники в реп. info, [logo_refactoring/logo](https://github.com/u-transnet/info/tree/logo_refactoring/logo)

**Comment by RomaRAD** [comment]
@EvgeniyPolyakov @kkrupovich  фав иконки в большом и минимальном размерах

![logo u-tech_](https://user-images.githubusercontent.com/33925750/34867313-7d3755dc-f7a1-11e7-84f4-89391bba4104.jpg)
![logo u-tech_2](https://user-images.githubusercontent.com/33925750/34867314-7d7316b2-f7a1-11e7-9b5f-398068fc5b5b.jpg)


![fav_u-tech](https://user-images.githubusercontent.com/33925750/34867256-44038cea-f7a1-11e7-95ac-22dddfdb8c03.jpg)
![fav u-tech](https://user-images.githubusercontent.com/33925750/34867257-4439771a-f7a1-11e7-805b-ad5530d3b1a7.jpg)

**Comment by alecvert** [comment]
@RomaRAD класс!

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #23475944
TRANSFER |  
From | utd-design
To | utd-romarad
Quantity | 210.00000 UTDEV

Спасибо!
