### ISSUE TITLE
Рефакторинг css

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [u-transnet/www-teaser#86]
Рефакторинг css:

- Определение общих параметров для устоявшихся блоков и вынос их в общие стили
- Оптимизация БЭМ
- Оптимизация существующих блоков
- Добавление комментариев в исходник

Смотрят @kkrupovich

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23445061

От | eugene-polyakov
Кому | utd-web
Количество | 120.00000 UTDEV.SKILL

до вечера 13.01.2018

**Comment by EvgeniyPolyakov** [comment]
Сделано:


    Определение общих параметров для устоявшихся блоков и вынос их в общие стили
    Оптимизация БЭМ
    Оптимизация существующих блоков
    Добавление комментариев в исходник

**Comment by EvgeniyPolyakov** [comment]
ps Из интересного что можно еще отрефакторить на будущее - асинхронная загрузка Google Fonts (Google Webfonts Loader) - пока изучаю вопрос на предмет целесообразности

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 
BLOCK #23511880
TRANSFER |  
From | utd-web
To | eugene-polyakov
Quantity | 120.00000 UTDEV
Спасибо!

> пока изучаю вопрос на предмет целесообразности

Это называется SPIKE - у нас в codebase этих спайков - больше чем реального кодинга раз в 10-15 примерно ;))) Т.ч. ты можешь создавать спайки и упоминать их в оцениваемых в скилле задачах (а иногда и сами спайки оценивать приходится, т.к. копать не день и не два иногда надо) - а в комментах к спайку просто фиксировать результат своих раскопок. Это же OpenSource - тут после тебя будут другие люди, и им очень полезно видеть ход наших мыслей.
