### ISSUE TITLE
Модификация 1 экрана и картинки TRANSNET SPACE под арабский мир

### ISSUE THREAD

**Issue by alecvert** [u-transnet/www-teaser#88]
@RomaRAD 
![](https://user-images.githubusercontent.com/33925750/34665460-048e2d1c-f482-11e7-8b76-3d2e1b4473b4.png) 
![](https://user-images.githubusercontent.com/33925750/34665458-04587faa-f482-11e7-8859-493f808b0532.png)

Рома, переделай пжлст эти 2 картинки под арабский мир.
Где-то нужно вставить достопримечательности, обязательно бурдж халифу (можно вместо кристалла где DPoS), бурдж аль араб , другие небоскрёбы ( 
![image](https://user-images.githubusercontent.com/30151576/34904330-8f7a8308-f865-11e7-97f4-1dcf1153fcd5.png) 
вместо домов на первом экране, машины заменить на спорткары, синий пол заменить на песок, футбольное поле на [искусственный остров](https://www.google.ru/search?q=%D0%B4%D0%BE%D1%81%D1%82%D0%BE%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8+%D0%9E%D0%90%D0%AD&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi4y8TawdTYAhWFESwKHYinC6oQ_AUICygC&biw=2133&bih=1215#imgrc=atJFyTqHThlahM) , [или тут](https://www.google.ru/search?q=%D0%B4%D0%BE%D1%81%D1%82%D0%BE%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8+%D0%9E%D0%90%D0%AD&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi4y8TawdTYAhWFESwKHYinC6oQ_AUICygC&biw=2133&bih=1215#imgrc=dsUm08EqvOos1M:) ,  подумай ещё над атрибутикой, но избегая конкретики в виде флага и тд

На Transnet Space , лучше сделать вид оцифровки высокоскоростной трассы со скоростными модулем, добавить надпись 500-600 km/h , траву также на песок.

**Comment by cptn-solo** [comment]
@alecvert когда это нужно сделать, или к какой части проекта это относится? Нельзя оставлять такие висящие задачи, нужно их к чему-то привязывать, к проекту хотя бы к какому-то, к дорожной карте - есть [проект](https://github.com/orgs/u-transnet/projects/2) такой, можно ссылку на какую-нибудь веху из дорожной карты хотя бы вставить. Ты мне просто своими словами ответь, а я подумаю, как это оформить.

**Comment by alecvert** [comment]
@kkrupovich на следующей недели к нашей поездке к арабам. Она 19-21 января.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @jackal1527 
Если нужно к пятнице, то надо сегодня или завтра с утра начинать. Их архитектуру в наш ракурс впихнуть дело не самое простое.  Я правильно понял, что это будет заставка для презентауии, значит нужен формат 16х9 или 4х3? 
Посмотрите, какие элементы можно оставить а какие еще добавить?
![image](https://user-images.githubusercontent.com/33925750/34929878-2a93bd36-f9e8-11e7-858a-ce5914d41de8.png)

**Comment by alecvert** [comment]
@RomaRAD Хорошо, а самолёт к чему? В остальном логика хороша, считаю , что добавлять ничего не надо.

По второй картинке скоростной трассе, перетекающей в цифровую скоростную и песку, думаю, что всё понятно?

По формату , будем показывать на проекторе или буке. Но в апреле понадобится и в большом формате.

**Comment by nat-brit** [comment]
Предлагаю отдельный созвон по требованиям к картинкам для презентации на вторник 16.01 @alecvert @jackal1527 @RomaRAD

**Comment by RomaRAD** [comment]
BLOCK #23576940
TRANSFER 
From | utd-romarad
To | utd-design
Quantity | 140.00000 UTDEV.SKILL
Изменение главной иллюстрации под "арабский мир". Смотрим предварительный вариант вечер 17-го
@alecvert @kkrupovich

**Comment by RomaRAD** [comment]
Промежуточный вариант. Пока это выглядит вот так
![arabian](https://user-images.githubusercontent.com/33925750/35028332-6595c9b6-fb77-11e7-84b8-d33f734db486.jpg)

**Comment by Arteg0r** [comment]
Мне бы в игру такой арт.

**Comment by RomaRAD** [comment]
@alecvert  
![arabian _2](https://user-images.githubusercontent.com/33925750/35043436-7b13f150-fbae-11e7-979c-20c59ddaf273.jpg)
![arabian 33](https://user-images.githubusercontent.com/33925750/35043442-7f9f4170-fbae-11e7-96d7-9d6cfa5d3db0.jpg)
![arabian22](https://user-images.githubusercontent.com/33925750/35043444-81cc0910-fbae-11e7-89fd-8243062bb3a1.jpg)

**Comment by RomaRAD** [comment]
остановились на таком ![1111](https://user-images.githubusercontent.com/33925750/35050593-00d52316-fbc5-11e7-95e4-f2ac16d5dc27.jpg)

**Comment by nat-brit** [comment]
Красота, лучше чем первая:) Еще бы станцию посовременней сделать:)

**Comment by cptn-solo** [comment]
@RomaRAD @nat-brit @alecvert нужен еще скилл или к следующей задаче? К следующей, то исходники в [prototyping/mainscreen](https://github.com/u-transnet/www-teaser/tree/prototyping/mainscreen) и закрываем, иначе - скилл в студию.

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich  @nat-brit  если других пожеланий нет, то заливаю исходники. Уложились в одну итерацию![arabian bot](https://user-images.githubusercontent.com/33925750/35086923-247c2068-fc50-11e7-901d-e4aa430401f4.jpg)

**Comment by nat-brit** [comment]
Заливай:)

**Comment by alecvert** [comment]
@RomaRAD Заливай, Рома, отлично!

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich  исходник по ссылке.
Алексею вышлю отдельно джипежки под форматы презентации 4х3 и 16х9
https://github.com/u-transnet/www-teaser/commit/542123e1eb6f67d32b03105a0146a31157169f01

**Comment by cptn-solo** [comment]
@RomaRAD 
BLOCK #23641780
TRANSFER |  From | utd-design
To | utd-romarad
Quantity | 140.00000 UTDEV

Спасибо!

@alecvert @nat-brit @RomaRAD какая следующая задача в итоге? Скилл по ней отгружен?

**Comment by RomaRAD** [comment]
@Arteg0r как с сайтом разберемся, я только за)
