### ISSUE TITLE
Верстка главной страницы сайта в новом стиле

### ISSUE THREAD

**Issue by nat-brit** [u-transnet/www-teaser#89]
Текст для страницы взять[ отсюда](https://docs.google.com/document/d/1yV0gj_Api5i7j1EXlf6xAfo8QiQFeDB1KzJ4ivo14Iw/edit) ([задача](https://github.com/u-transnet/info/issues/51) )
Стилистика: вид страницы по дизайну в [таком стиле ](https://user-images.githubusercontent.com/32764532/34160595-55c4c56c-e4ef-11e7-8b1d-58ced47846d7.jpg)
@kkrupovich @alecvert @EvgeniyPolyakov  @jackal1527 @Dima-Iron

**Comment by cptn-solo** [comment]
@jackal1527 похоже, ты первый кандидат на эту задачу

**Comment by Dima-Iron** [comment]
Коллеги, приветствую! Планирую также принимать участие в приемке данной задачи.

**Comment by jackal1527** [comment]
Смотрят
@kkrupovich @EvgeniyPolyakov @nat-brit или @alecvert

Block #23583787
Transfer
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
Обсуждаем задачу: вторник 16.01.2018
Смотрим: среда 17.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
Напишу сюда сайты из вики которые мне понравились
https://populous.co/
https://www.streamr.com/
https://ethlend.io/ru/     (видос на стартовом прикольный)
https://district0x.io/        (анимация прикольная, тут и по дорожной карте примерно наша идея)

**Comment by cptn-solo** [comment]
@jackal1527 
Я за https://populous.co/
@nat-brit @alecvert в этой задаче нам не нужно тоже какое-то резюме сформулировать?

**Comment by RomaRAD** [comment]
![53b073748eb3da2c38d34057706cb22599ecfa200bd2811b88 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/33925750/34989792-ad358e7e-fae5-11e7-8f2e-d1276c955310.png)

**Comment by cptn-solo** [comment]
@RomaRAD это не в #90 лучше ли закинуть?

**Comment by jackal1527** [comment]
![transnet_ _02](https://user-images.githubusercontent.com/32764532/35037586-c4f740de-fb99-11e7-8253-c44fc2f1f8e7.jpg)

**Comment by jackal1527** [comment]
1) Мы создаем решения.... куда впихнуть оффер?
2) текст с синего блока "транснет-это..." - перенести выше чем "как все работает"
3) блок с картой перенести на синий блок
4) блок "как все работает" (которого сейчас нету в макете) поставить по типу предыдущего, но на синем фоне
5)

**Comment by jackal1527** [comment]
Задачу обсудили @kkrupovich прими пожалуйста и закроем 
Следующая итерация [ #91](https://github.com/u-transnet/www-teaser/issues/91)

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23614793
TRANSFER |  From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV
Спасибо, продолжаем.
