### ISSUE TITLE
Переработка шапки сайта (стартового экрана) под новуый макет

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#90]
Источник задачи - #89 - новый макет главной страницы сайта.

Предложения от @alecvert 

![photo_2018-01-16_12-14-13](https://user-images.githubusercontent.com/1105555/34980928-07c4d0cc-fab7-11e7-8f3f-3ab03fca07fa.jpg)

**Comment by cptn-solo** [comment]
@alecvert @jackal1527 @RomaRAD @nat-brit 
На самом деле много проговорили сегодня и было бы неплохо сюда скинуть свои замечания. 
Мой вариант в итоге - упрощение текущей шапки в направлении:
- оставляем токопроводящие дорожки;
- убираем дома, заменяем их либо блоками, либо чипами на "материнской плате" платформы Transnet Space;
- над блоками/чипами можно разместить "проекции", или изометрические объемные иконки
- блоки/чипы можно подписать
- желательно избавиться от визуального центра, либо отвязать этот визуальный центр от какого-то конкретного единственного блока на плате.
- логотип U-TECH можно разместить на поверхности платы, как клеймо производителя. 
- логотипы вендора инвесторов, пользователей (человечки) - можно размещать на блоках
- логотипы технологий (DPoS, nginx, Graphene, Bitshares, etc.) - так же нужно размещать на самой плате - т.к. это части платформы, распределенные по всем ее узлам.

**Comment by RomaRAD** [comment]
BLOCK #23666311
From | utd-romarad
To | utd-design
Quantity | 70.00000 UTDEV.SKILL
1 день. Смотрим 19.01

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @nat-brit @jackal1527 
![1](https://user-images.githubusercontent.com/33925750/35140557-8a5b0588-fd19-11e7-9f45-c6e6ce82ab3c.jpg)

Вторая не по задаче, не для шапки, но мне кажется тоже неплохо выглядит 
![2](https://user-images.githubusercontent.com/33925750/35140606-aff41208-fd19-11e7-9b45-3434a6710346.jpg)

**Comment by nat-brit** [comment]
Отлично с чипами смотриться, но хочется прозрачности. Может убрать заливку и оставить только контуры? Станции осовременить тоже как-то, слишком уж игрушечно смотрятся. Для игровой страницы нормально, но не для главной.

**Comment by Dima-Iron** [comment]
Как вариант сделать всё монохромным, а неоновым подсветить названия "DPOS", "DEX" и т.д.
Согласен с Наташей насчёт "осовременить". Даже добавить футуризма немного, всё-таки цифровая революция, все дела

**Comment by alecvert** [comment]
@RomaRAD слишком много всего, деталей и людей не надо. Подробнее дам инфу голосом в чате или напишу позже

**Comment by alecvert** [comment]
@RomaRAD слишком много всего, деталей и людей не надо. Подробнее дам инфу голосом в чате или напишу позже

**Comment by cptn-solo** [comment]
@nat-brit @Dima-Iron осовременить - это совсем поменять концепцию графики. Ну не знаю, не рано? 
Мне кажется достаточно будет действительно просто разгрузить. 
+ Обратите внимание на то, что @RomaRAD реализовал в итоге не то, о чем мы так долго спорили - а то, что было зафиксировано в задаче, причем реализовал буквально, и довольно точно. На будущее всем урок - фиксируйте требования в задаче, не ленитесь, иначе ваши требования останутся мыслями вслух.

BLOCK #23686470

TRANSFER |  
-- | --
From | utd-design
To | utd-romarad
Quantity | 70.00000 UTDEV

**Comment by cptn-solo** [comment]
@RomaRAD скилуем еще день?

**Comment by RomaRAD** [comment]
@kkrupovich @alecvert @nat-brit @Dima-Iron  прошлый день не скилую, т.к. с виндой провозился. Если будут объемные доработки к предложенному варианту, тогда  добавлю еще день
Эскиз на основе скайпа с Алексеем
![321](https://user-images.githubusercontent.com/33925750/35183180-a2417368-fe03-11e7-81ac-9d0373252cab.jpg)

**Comment by RomaRAD** [comment]
Без стрелочек
![333323](https://user-images.githubusercontent.com/33925750/35183293-4f8df6f8-fe05-11e7-894e-13919f165e43.jpg)

**Comment by nat-brit** [comment]
Все отлично. Предлагаю пока остановится и закрыть эту задачу, сначала надо решить другие вопросы по внешнему виду и наполнению сайта.

**Comment by cptn-solo** [comment]
@RomaRAD 
> прошлый день не скилую, т.к. с виндой провозился. Если будут объемные доработки к предложенному варианту, тогда добавлю еще день

Ок.

> Все отлично. Предлагаю пока остановится и закрыть эту задачу, сначала надо решить другие вопросы по внешнему виду и наполнению сайта.

@RomaRAD @nat-brit @alecvert @jackal1527 
Мне нравится последний вариант - мне кажется, это объединение вообще всего, что было - и графика в изометрии (в меру мультяшная) и лаконичность (теперь) и реализация пожеланий к изменению стилистики. 
Куда двигаемся дальше, как масштабируем, как выглядит на мобильном макете?

**Comment by cptn-solo** [comment]
@RomaRAD @jackal1527 исходники там же в [prototyping/mainscreen](https://github.com/u-transnet/www-teaser/tree/prototyping/mainscreen)?

**Comment by nat-brit** [comment]
> Мне нравится последний вариант - мне кажется, это объединение вообще всего, что было - и графика в изометрии (в меру мультяшная) и лаконичность (теперь) и реализация пожеланий к изменению стилистики. 

Мне тоже нравится:) 

> Куда двигаемся дальше, как масштабируем, как выглядит на мобильном макете? 

Предлагаю все-таки чуть вернуться назад и еще раз сформулировать глобальные задачи по дизайну, которые примерно (да, примерно:) мне представляются такими: 

1. Сайт-клиент-точка входа в блокчейн (регистрация, пользотельский интерфэйс и пр)  
2. Сайт-клиет-точка входа в информационное пространство Transnet Space, 
3. Сайт-клиент-точка входа на игровую платформу, 
4. Сайт-клиент-точка входа в U-Tech (да, именно сайт, откуда расходятся по веткам "проекты" и "двери" в разные проекты), возможно именно на нем стоит сейчас сконцентрировать наши усилия в первую очередь.  

Все эти клиенты интегрируются с блокчейном. У них разная визуальная подача и контентное наполнение. Разный уровень сложности. В каком порядке они появляются на свет и в какие сроки? 
На какую ЦА ориентированы?

Дополнительно ко всему вышеперечисленному необходимы **презентационные материалы**. Это тоже отдельная задача (для кого? внешний вид? фирменный стиль? срочность?) + остается открытым вопрос по соц.сетям с теми же самыми нюансами.

У нас уже накопилось много отличных работ @RomaRAD, чтобы их дорабатывать, нужно, в первую очередь, чтобы у всех появилось единое понимание и видение того, что хотим получить в итоге. 

Предлагаю созвон (понедельник  22/01 в 17-00 по мск?) именно по стратегии и этапам (также относится к [задаче 59 ](https://github.com/u-transnet/info/issues/59#issuecomment-359194702) и #56. В итоге созвона хочется сформировать основные mailstones, в том числе требования по направлению дизайна для проекта вообще и сайтов (лэндингов, платформ, приложений) в частности, определить порядок по постановке задач и приемке работ по дизайну. 

@kkrupovich @alecvert @Dima-Iron @rossul @jackal1527

**Comment by alecvert** [comment]
@RomaRAD Рома, супер. Ты воплотил то, что обсуждали и добавил своих изюминок. Теперь достойно для стартового экрана

**Comment by cptn-solo** [comment]
@nat-brit 
> Предлагаю созвон (понедельник 22/01 в 17-00 по мск?) именно по стратегии и этапам

Я не против, но нужен план. Создал [документ](https://docs.google.com/document/d/1DLpWe-TV9X8ma2ibIuSyCvkH3kYB5Dyp7cOefm6UfBE/edit?usp=sharing)

**Comment by RomaRAD** [comment]
@kkrupovich исходники по ссылке 
https://github.com/u-transnet/www-teaser/commit/d4f658ed7cee3fb1cc7bc8803d63c3fc58f00d7d
