### ISSUE TITLE
02_Итерация Верстка главной страницы сайта в новом стиле

### ISSUE THREAD

**Issue by jackal1527** [u-transnet/www-teaser#91]
Предыдущая задача [#89](https://github.com/u-transnet/www-teaser/issues/89)

1) Мы создаем решения.... куда впихнуть оффер?
2) Текст с синего блока "транснет-это..." - перенести выше чем "как все работает"
3) Блок с картой перенести на синий блок
4) Блок "как все работает" (которого сейчас нету в макете) поставить по типу предыдущего, но на синем фоне
5) Подумать как сделать блок "больше чем блокчейн..."
6) Додумать целевое действие (призыв к инвесторам)

**Comment by nat-brit** [comment]
Да, ждем завтра после полудня, напиши, когда будешь готов и созвонимся

**Comment by jackal1527** [comment]
Смотрят
@kkrupovich @EvgeniyPolyakov @nat-brit или @alecvert

Block #23614645
Transfer
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
Смотрим: среда 18.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
![transnet_ _03](https://user-images.githubusercontent.com/32764532/35097592-96f7c26a-fc72-11e7-89cd-67afb12f9f09.jpg)

**Comment by cptn-solo** [comment]
@jackal1527 
- может все слайдеры сделаем в одну ширину? "какие-то свойства блокчейна" + "больше чем инвестиции"
- а блок "больше чем блокчейн" лучше вообще раскрыть и привести к виду предыдущих двух больших блоков с графикой
- возможно, нижний блок "больше чем инвестиции" - можно убрать
- "какие то свойства" можно убрать заголовок или сделать "основные преимущества" но заголовок поменьше
- вставить абзац целиком как есть в блок "больше чем блокчейн"
- написать "меню" рядом с бургером
- поработать над цветом блоков (применить градиент)

**Comment by cptn-solo** [comment]
@jackal1527  дальше #92 
BLOCK #23652210

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 100.00000 UTDEV
