### ISSUE TITLE
03_Итерация Верстка главной страницы сайта в новом стиле

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#92]
Пред. итерация #91 

@jackal1527

- может все слайдеры сделаем в одну ширину? "какие-то свойства блокчейна" + "больше чем инвестиции"
- а блок "больше чем блокчейн" лучше вообще раскрыть и привести к виду предыдущих двух больших блоков с графикой
- возможно, нижний блок "больше чем инвестиции" - можно убрать
- "какие то свойства" можно убрать заголовок или сделать "основные преимущества" но заголовок поменьше
- вставить абзац целиком как есть в блок "больше чем блокчейн"
- написать "меню" рядом с бургером
- поработать над цветом блоков (применить градиент)

**Comment by jackal1527** [comment]
Смотрят
@kkrupovich @EvgeniyPolyakov @nat-brit или @alecvert

Block #23672554
Transfer
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
Смотрим: пятница 19.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
## Сделал две версии цвета
## Сделал первый экран с ориентировкой набок (в задачу не входило но я должен был попробовать)
## Предложил видение блока "больше чем блокчейн"
## В принципе постарался все причесать

![transnet_ _04](https://user-images.githubusercontent.com/32764532/35195374-63dadede-fee4-11e7-918c-0005e73ef55b.jpg)
![transnet_ _05](https://user-images.githubusercontent.com/32764532/35195378-67a61826-fee4-11e7-89e6-ff5f1867492d.jpg)

**Comment by rossul** [comment]
А тех задание на сайт, которое можно прочитать существует? @kkrupovich @nat-brit

**Comment by nat-brit** [comment]
@rossul @kkrupovich @alecvert 
Вся информация по разработке сайта [тут ](https://github.com/u-transnet/www-teaser/issues?page=1&q=is%3Aissue+is%3Aclosed)
Я отталкивалась от [этого документа](https://github.com/u-transnet/www-teaser/wiki/%D0%9A%D0%BE%D0%BD%D1%86%D0%B5%D0%BF%D1%86%D0%B8%D1%8F), но у меня до сих пор [много вопросов.](https://docs.google.com/document/d/1DLpWe-TV9X8ma2ibIuSyCvkH3kYB5Dyp7cOefm6UfBE/edit?ts=5a648999). Поэтому и хочу вернуться в начало, к составлению ТЗ для сайта. Возможно я что-то упустила и есть еще описания на Гитхабе.

**Comment by nat-brit** [comment]
@jackal1527 @kkrupovich 
Шапка смотрится гораздо лучше предыдущей, ИМХО, и блок "Больше чем блокчейн" классно придуман. По остальным блокам смогу откомментировать, когда решим окончательно вопрос по наполнению главной страницы. Эту итерацию предлагаю закрывать.

**Comment by EvgeniyPolyakov** [comment]
1й вариант графически смотрится более закончено на мой взгляд. Но длинный однотонный  фон в "Как все работает" немного смущает - может там либо градиент, либо, как ты уже Владимир намечал в 1м макете -  разный бэк в частях

**Comment by rossul** [comment]
@nat-brit Посмотрел. Это скорее описание стуктуры первой страницы. Например "Предварительное знакомство с проектом". Где-то если обсуждение, что мы считаем нужно прокоммуникировать, в этом разделе, что бы юзер полез дальше с понимамием основных вещей?

**Comment by nat-brit** [comment]
@rossul 
Нет. Обсуждение было, на записей и ТЗ нет. Это правильный вопрос
@kkrupovich @alecvert

**Comment by jackal1527** [comment]
Доскилловываем еще день потому что:
- была выполнена задача по дизайну главного экрана (в двух цветовых вариациях)
- был немного переработан второй экран (и вообще прибрал все сомнительные элементы, шрифты и блоки)
- обёмнее поработал над экраном "больше чем блокчейн", получилось оч. неплохо.

ДОСКИЛЛОВЫВАЕМ:
Block #23768014
Transfer
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
Посмотрели: понедлеьник 22.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
отправил @EvgeniyPolyakov оба макета

**Comment by cptn-solo** [comment]
@jackal1527 
BLOCK #23768517

TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 200.00000 UTDEV

Спасибо!
