### ISSUE TITLE
Макет для страницы описания токенов

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#93]
Источник - [задача](https://github.com/u-transnet/info/issues/56) по документу о токенизации

Нужно продумать макет страницы, показывающей визуализацию токенов Transnet Space: 
skill - dev - [core|game|kit] - utt

Дополнительно - привлечь @RomaRAD  к разработке графики, иллюстрирующей смысл токенов платформы

**Comment by jackal1527** [comment]
Смотрят
@kkrupovich @EvgeniyPolyakov @nat-brit или @alecvert

Block #23672554    +    Block #23768452
Transfer
From | jackal1527
To | utd-ux
Quantity | 200.00000 UTDEV.SKILL
Смотрим: среда-четверг 24.01.2018 - 25.01.2018
@kkrupovich
