### ISSUE TITLE
Верстка элементов макета, реализованного в новой стилистике 

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/www-teaser#94]
Источник - #92 #90 #80

@EvgeniyPolyakov предварительно договорились переверстать шапку и блок "больше чем блокчейн" с новой (#92 #90) графикой - возможно, кроме этих блоков потребуется поменять цветовую схему, что думаешь, @jackal1527 ?

@jackal1527  - если необходимо - просьба передать @EvgeniyPolyakov графику для шапки и блока "больше чем блокчейн"

**Comment by EvgeniyPolyakov** [comment]
Графику для декстопа получил от @jackal1527 начинаю, жду завтра адаптивные версии

**Comment by EvgeniyPolyakov** [comment]
БЛОК #23763238

От | eugene-polyakov
Кому | utd-web
Количество | 140.00000 UTDEV.SKILL

до вечера 24.01.18

**Comment by jackal1527** [comment]
Готовлю для @EvgeniyPolyakov макет на верстку + адаптив 2 блоков под все разрешения (главный экран и "больше чем блокчейн")

Block #23768515
Transfer
From | jackal1527
To | utd-ux
Quantity | 100.00000 UTDEV.SKILL
Отправляю: вторник 23.01.2018
@kkrupovich

**Comment by jackal1527** [comment]
# 1280
![1280_transnet_ 02](https://user-images.githubusercontent.com/32764532/35326189-ba15a2ea-0117-11e8-8618-bc9dc11f3891.jpg)
# 1024
![1024_transnet_ 02](https://user-images.githubusercontent.com/32764532/35326139-8f163b18-0117-11e8-8c3a-f409b824ed28.jpg)
# 768
![768_transnet_ 02](https://user-images.githubusercontent.com/32764532/35326142-90a2087c-0117-11e8-8438-1226b4a8bd22.jpg)
# 640
![630_transnet_ 02](https://user-images.githubusercontent.com/32764532/35326144-92026b30-0117-11e8-8323-e4d0b64600f0.jpg)
# 320
![320_transnet_ 02](https://user-images.githubusercontent.com/32764532/35326146-93865796-0117-11e8-91f4-a675085d6a55.jpg)

**Comment by jackal1527** [comment]
Исходники для @EvgeniyPolyakov [тут](https://github.com/u-transnet/www-teaser/tree/jackal1527-patch-1/slicing/adaptive%20elements_02)

**Comment by EvgeniyPolyakov** [comment]
Исходики получил. 

БЛОК #23815419

От | eugene-polyakov
Кому | utd-web
Количество | 70.00000 UTDEV.SKILL

Добавление скилла на 1 день. Смотрим вечером 25.01.18

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert @nat-brit @rossul 

Считаю, что если мы останавливаемся сейчас на дизайне для привлечения внимания крипто-энтузиастов и потенциальных участников - этот вариант довольно четко выполняет свою задачу. Что я увидел:
- Текст ссылки "Узнать что это" можно заменить на "Больше, чем блокчейн" - сразу и акцент для сообщества, и понимание, что будет открыто по ссылке
- я бы добавил эту же ссылку на десктоп-версию - и сделал частью или "преамбулой" к тексту про операционную систему (который тоже лучше бы заменить - может на что-то про "строим вместе - пользуемся сообща" - чтобы прям бац - и всем все понятно - но это не в текущей задаче лучше обсуждать)

**Comment by rossul** [comment]
А поставить заглушку — срочно? Если да то можно обсудить как ее улушчить, что бы она работала.  
@kkrupovich "Узнать что это" можно заменить на "Больше, чем блокчейн"  - нельзя :) еще более непонятно.

**Comment by cptn-solo** [comment]
@rossul 
> А поставить заглушку — срочно

там уже стоят заглушки на обоих доменах, поэтому нет, не думаю. Но там сейчас просто gif (transnet.tech/transnet.space)

> @kkrupovich "Узнать что это" можно заменить на "Больше, чем блокчейн" - нельзя :) еще более непонятно.

ок, я пытался :)

**Comment by rossul** [comment]
Если нет, то я бы заморозил дезайн активность на несколько дней пока не развберебся с основными вещами. Что бы не пришлось переделывать...

**Comment by nat-brit** [comment]
Согласна с @rossul

**Comment by cptn-solo** [comment]
BLOCK #23829216


TRANSFER |  
-- | --
From | utd-ux
To | jackal1527
Quantity | 100.00000 UTDEV

@jackal1527 спасибо!

**Comment by cptn-solo** [comment]
@alecvert добавил от себя пунктов к "больше чем блокчейн"
- Мгновенность транзакций
- Большое количество операций в секунду
- p2p - децентрализация

**Comment by jackal1527** [comment]
и куда их?

**Comment by cptn-solo** [comment]
@jackal1527 

> и куда их? 

пока никуда, но вообще - это фидбэк с югов. Болтали и я записал.

**Comment by EvgeniyPolyakov** [comment]
Выложил 2й блок https://github.com/u-transnet/transnet.tech/commit/d477b60ca8cd0b5cc0102532fdccb2793a384461 (1й выложил в день 1го видеочата с @rossul )

По дате сдвинулось - был выходной + паралелльно был занят в задачах по сборке билда докера https://github.com/u-transnet/dockerfiles/commits/master и сегодня в "user story" (появится в jira)

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 
BLOCK #23999819

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 140.00000 UTDEV

Спасибо!

**Comment by cptn-solo** [comment]
@EvgeniyPolyakov 

> БЛОК #23815419

BLOCK #24019476

TRANSFER |  
-- | --
From | utd-web
To | eugene-polyakov
Quantity | 65.00000 UTDEV

(-5 которые приплюсовались в другой транзакции)
