### ISSUE TITLE
Создание бренд бука и фирменного стиля

### ISSUE THREAD

**Issue by alecvert** [u-transnet/www-teaser#95]
@RomaRAD Рома, исходя из всеми ранее согласованной  и опробованной даже на одежде конечной версии логотипа , сделай пжлст фирменный стиль с цветами и символикой U-tech.

Навскидку: 1. Визитка
2. Шаблон слайда для презентации.
3.  Шаблон бланка
4. Лого на одежде.

Что ещё ?
Делаем на белом фоне?

**Comment by RomaRAD** [comment]
@alecvert @kkrupovich @nat-brit 
В стандартный фирм.стиль входит:
- Логотип (система построения, фирменные цвета, варианты использования);
- Фирменные паттерны, стилеобразующие элементы;
- Бланк для деловой переписки в формате Word;
- Визитка;
- Шаблоны слайдов презентации ( Power Point) 
- Краткое руководство по использованию фирменного стиля.

Я думаю, что это все необходимо. Обычно делаю это за 7-9 дней.
Пока загрузка не большая, могу уложиться успею за 4. 
Поподробнее о фир.стилях есть в моем предложении https://cloud.mail.ru/public/CrDk/ghBpaPiyE

Если добро, ставьте лайк я заскилую и начну с ПН работать

**Comment by alecvert** [comment]
@RomaRAD Добро, Рома
